// Package seamgen post-processes a compiled grammar schema for cross-grammar
// embedding. Every seam (a field that references a dependency-provided rule)
// becomes a google.protobuf.Any, and the embedded type is recorded in a seam
// map the runtime codec consults. Because seams are Any, a grammar's proto
// imports only any.proto — never another grammar — so grammars stay independent
// and mutually-recursive (cyclic) embeddings are free.
package seamgen

import (
	"fmt"
	"sort"
	"strconv"
	"strings"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"

	"github.com/accretional/gluon/v2/builddep"
	"github.com/accretional/gluon/v2/compiler"
)

const (
	anyProto = "google/protobuf/any.proto"
	anyType  = ".google.protobuf.Any"
)

// ExternalizeToAny rewrites every field whose type is a dependency-provided rule
// into a google.protobuf.Any seam. It records the embedded type in the returned
// seam map (key ".pkg.Msg.field" -> "deppkg.Rule"), drops the now-unreferenced
// local placeholder messages, and adds the any.proto import. external_rules name
// EBNF productions; they are matched against the compiled message via
// compiler.PascalCase. Returns the seam map plus human-readable notes.
func ExternalizeToAny(fdp *descriptorpb.FileDescriptorProto, pkg string, deps []builddep.GrammarDep) (map[string]string, []string) {
	remap := map[string]string{} // ".pkg.Msg" -> "deppkg.Msg"
	dropMsg := map[string]bool{}
	for _, d := range deps {
		for _, rule := range d.ExternalRules {
			msg := compiler.PascalCase(rule)
			remap["."+pkg+"."+msg] = d.ProtoPackage + "." + msg
			dropMsg[msg] = true
		}
	}
	seam := map[string]string{}
	if len(remap) == 0 {
		return seam, nil
	}
	var notes []string
	var walk func(m *descriptorpb.DescriptorProto, fqn string)
	walk = func(m *descriptorpb.DescriptorProto, fqn string) {
		for _, f := range m.GetField() {
			if f.GetType() != descriptorpb.FieldDescriptorProto_TYPE_MESSAGE {
				continue
			}
			if target, ok := remap[f.GetTypeName()]; ok {
				seam[fqn+"."+f.GetName()] = target
				notes = append(notes, fmt.Sprintf("%s.%s: %s -> Any(%s)", fqn, f.GetName(), f.GetTypeName(), target))
				f.TypeName = proto.String(anyType)
			}
		}
		for _, n := range m.GetNestedType() {
			walk(n, fqn+"."+n.GetName())
		}
	}
	for _, m := range fdp.GetMessageType() {
		walk(m, "."+pkg+"."+m.GetName())
	}
	var kept []*descriptorpb.DescriptorProto
	for _, m := range fdp.GetMessageType() {
		if dropMsg[m.GetName()] {
			notes = append(notes, "drop placeholder "+m.GetName())
			continue
		}
		kept = append(kept, m)
	}
	fdp.MessageType = kept

	present := false
	for _, dep := range fdp.GetDependency() {
		if dep == anyProto {
			present = true
		}
	}
	if !present {
		fdp.Dependency = append(fdp.Dependency, anyProto)
		sort.Strings(fdp.Dependency)
	}
	return seam, notes
}

// FormatSeamMap renders the seam map as a generated Go source file declaring
// `var SeamType map[string]string` in the given package. It mirrors the
// prefix/separator map generators so the codec can consult all three uniformly.
func FormatSeamMap(goPackage string, seam map[string]string) string {
	keys := make([]string, 0, len(seam))
	for k := range seam {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var b strings.Builder
	b.WriteString("// Code generated by genproto. DO NOT EDIT.\n\n")
	b.WriteString("package " + goPackage + "\n\n")
	b.WriteString("// SeamType maps a \"" + `.pkg.Message.field` + "\" key to the fully-qualified\n")
	b.WriteString("// message type the field's google.protobuf.Any seam embeds (e.g.\n")
	b.WriteString("// \"css.CssStyleSheet\"). The codec reads it to know what grammar to parse a\n")
	b.WriteString("// seam's text as; the render direction reads the Any's own type_url.\n")
	b.WriteString("var SeamType = map[string]string{\n")
	for _, k := range keys {
		b.WriteString("\t" + strconv.Quote(k) + ": " + strconv.Quote(seam[k]) + ",\n")
	}
	b.WriteString("}\n")
	return b.String()
}
