// Package servicegen emits a grammar's Parse/Render service definition as a
// .proto file. Each gluon-built grammar project owns its service surface as a
// committed proto artifact (html_service.proto, css_service.proto, …) emitted
// by its genproto alongside the schema and tables; the generated server stubs
// are implemented by a thin per-project adapter that delegates to the gluon
// codec (v2/codec) for the actual parsing and rendering.
//
// The service shape is uniform across grammars: Render (typed root message →
// source text), RenderStream (same, chunked), and Parse (source text → typed
// root message). Rooting both directions at the grammar's start symbol is what
// makes the surface complete — every message in the schema is reachable from
// the root — and registering the generated service with gRPC reflection
// exposes the whole grammar schema to clients.
//
// Both directions also accept arbitrary grammar subtrees: ParseRequest.type
// names any registered message to parse as (the result comes back Any-packed
// in ParseResponse.node), and RenderRequest.node renders an Any-packed subtree
// in place of the root. This is what lets tooling (gallery generators,
// round-trip gates) drive every grammar path through the service itself.
package servicegen

import (
	"fmt"
	"strings"
)

// Spec describes one grammar's service surface. Package, GoPackage, Import and
// Root are required; the rest default from them (see Format).
type Spec struct {
	// Package is the proto package the grammar's messages live in (e.g.
	// "html"). The service proto is emitted into the same package so the root
	// message is referenced unqualified.
	Package string
	// Import is the grammar schema file to import (e.g. "html.proto").
	Import string
	// GoPackage is the go_package option for the generated service bindings
	// (e.g. "github.com/accretional/proto-html/proto/pb/htmlservice;htmlservicepb").
	// It must differ from the schema's go_package: protoc-gen-go-grpc emits a
	// separate Go package for the service.
	GoPackage string
	// Root is the grammar's start symbol message (e.g. "HtmlDocument").
	// Every message in the schema is reachable from it, so the service is
	// rooted there.
	Root string
	// Service is the service name. Defaults to Title(Package)+"Service"
	// (e.g. "HtmlService").
	Service string
	// RootField is the field name carrying the root message in requests and
	// responses. Defaults to "root" (proto-html uses "document", proto-css
	// "sheet").
	RootField string
	// TextField is the field name carrying source text. Defaults to Package
	// (e.g. "html", "css").
	TextField string
	// Lang is the human-readable language name used in comments. Defaults to
	// upper(Package) (e.g. "HTML").
	Lang string
}

// withDefaults returns s with the optional fields filled in.
func (s Spec) withDefaults() Spec {
	if s.Service == "" && s.Package != "" {
		s.Service = strings.ToUpper(s.Package[:1]) + s.Package[1:] + "Service"
	}
	if s.RootField == "" {
		s.RootField = "root"
	}
	if s.TextField == "" {
		s.TextField = s.Package
	}
	if s.Lang == "" {
		s.Lang = strings.ToUpper(s.Package)
	}
	return s
}

// Format renders the grammar's service .proto source. The output is a
// committed, protoc-compilable artifact; the implementing server delegates to
// the gluon codec for both directions.
func Format(spec Spec) (string, error) {
	s := spec.withDefaults()
	for _, req := range []struct{ name, v string }{
		{"Package", s.Package},
		{"Import", s.Import},
		{"GoPackage", s.GoPackage},
		{"Root", s.Root},
	} {
		if req.v == "" {
			return "", fmt.Errorf("servicegen: Spec.%s is required", req.name)
		}
	}

	var b strings.Builder
	p := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	p("// Code generated by gluon servicegen (run via genproto). DO NOT EDIT.")
	p("")
	p("syntax = %q;", "proto3")
	p("")
	p("package %s;", s.Package)
	p("")
	p("import %q;", s.Import)
	p("import %q;", "google/protobuf/any.proto")
	p("")
	p("option go_package = %q;", s.GoPackage)
	p("")
	p("// %s renders typed %s messages to %s text and parses %s text", s.Service, s.Root, s.Lang, s.Lang)
	p("// back. %s is the grammar's start symbol — every %s.* message is", s.Root, s.Package)
	p("// reachable from it — so both directions are rooted there. Both directions are")
	p("// pure reflection over the grammar-derived schema in %s plus the generated", s.Import)
	p("// tables; the gluon codec does all parsing and rendering, so the implementing")
	p("// server carries no per-rule logic.")
	p("service %s {", s.Service)
	p("  // Render serializes the request's %s into %s text.", s.Root, s.Lang)
	p("  rpc Render(RenderRequest) returns (RenderResponse);")
	p("")
	p("  // RenderStream serializes the request's %s and streams the %s text", s.Root, s.Lang)
	p("  // in chunks. The concatenation of all chunks equals Render's `%s`.", s.TextField)
	p("  rpc RenderStream(RenderRequest) returns (stream RenderChunk);")
	p("")
	p("  // Parse parses %s text into a typed %s.", s.Lang, s.Root)
	p("  rpc Parse(ParseRequest) returns (ParseResponse);")
	p("}")
	p("")
	p("message RenderRequest {")
	p("  // The %s to render. Any %s.* subtree is reachable from here.", s.Root, s.Package)
	p("  %s %s = 1;", s.Root, s.RootField)
	p("")
	p("  // Alternative root: an arbitrary grammar subtree packed as Any (as")
	p("  // returned in ParseResponse.node). Takes precedence over `%s`.", s.RootField)
	p("  google.protobuf.Any node = 2;")
	p("}")
	p("")
	p("message RenderResponse {")
	p("  // The rendered %s text.", s.Lang)
	p("  string %s = 1;", s.TextField)
	p("}")
	p("")
	p("message RenderChunk {")
	p("  // A slice of the rendered %s text. Concatenate chunks in arrival order.", s.Lang)
	p("  string %s = 1;", s.TextField)
	p("}")
	p("")
	p("message ParseRequest {")
	p("  // The %s text to parse.", s.Lang)
	p("  string %s = 1;", s.TextField)
	p("")
	p("  // Optional fully-qualified message type to parse as (e.g. a single")
	p("  // element or value production) instead of the %s root. The result", s.Root)
	p("  // comes back Any-packed in ParseResponse.node.")
	p("  string type = 2;")
	p("}")
	p("")
	p("message ParseResponse {")
	p("  // The parsed %s (set when ParseRequest.type was empty).", s.Root)
	p("  %s %s = 1;", s.Root, s.RootField)
	p("")
	p("  // The parsed subtree, Any-packed (set when ParseRequest.type named a")
	p("  // non-root message).")
	p("  google.protobuf.Any node = 2;")
	p("}")

	return b.String(), nil
}
