// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: v2/ast.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ASTDescriptor is a language-agnostic tree produced by parsing a source
// document against a GrammarDescriptor. At this stage it carries the full
// concrete syntax — every token the parser matched — so it is really a
// CST. A separate compiler may later lower it into a more abstract form
// (dropping punctuation, collapsing single-child chains, etc.) without
// changing the message shape.
type ASTDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the language the tree was parsed from (e.g. "sqlite", "go").
	Language string `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	// Optional version label for the language spec (e.g. "3.45", "1.26").
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Root node.
	Root          *ASTNode `protobuf:"bytes,3,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ASTDescriptor) Reset() {
	*x = ASTDescriptor{}
	mi := &file_v2_ast_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ASTDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ASTDescriptor) ProtoMessage() {}

func (x *ASTDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_v2_ast_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ASTDescriptor.ProtoReflect.Descriptor instead.
func (*ASTDescriptor) Descriptor() ([]byte, []int) {
	return file_v2_ast_proto_rawDescGZIP(), []int{0}
}

func (x *ASTDescriptor) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ASTDescriptor) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ASTDescriptor) GetRoot() *ASTNode {
	if x != nil {
		return x.Root
	}
	return nil
}

// ASTNode is a single node. Leaf nodes carry a `value` (the matched text);
// interior nodes carry `children`. The `kind` string names the rule or
// terminal role that produced the node.
type ASTNode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Rule name (e.g. "SelectStmt") for interior nodes, or a terminal tag
	// (e.g. "TERMINAL", "NONTERMINAL") for leaves.
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Matched text, for leaves. Interior nodes should leave this empty.
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// Child nodes, in source order.
	Children []*ASTNode `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty"`
	// Where this node was parsed from. Points into the source document
	// via SourceLocation.uri.
	Location      *SourceLocation `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ASTNode) Reset() {
	*x = ASTNode{}
	mi := &file_v2_ast_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ASTNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ASTNode) ProtoMessage() {}

func (x *ASTNode) ProtoReflect() protoreflect.Message {
	mi := &file_v2_ast_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ASTNode.ProtoReflect.Descriptor instead.
func (*ASTNode) Descriptor() ([]byte, []int) {
	return file_v2_ast_proto_rawDescGZIP(), []int{1}
}

func (x *ASTNode) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ASTNode) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ASTNode) GetChildren() []*ASTNode {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *ASTNode) GetLocation() *SourceLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

var File_v2_ast_proto protoreflect.FileDescriptor

const file_v2_ast_proto_rawDesc = "" +
	"\n" +
	"\fv2/ast.proto\x12\bgluon.v2\x1a\x18v2/source_location.proto\"l\n" +
	"\rASTDescriptor\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12%\n" +
	"\x04root\x18\x03 \x01(\v2\x11.gluon.v2.ASTNodeR\x04root\"\x98\x01\n" +
	"\aASTNode\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12-\n" +
	"\bchildren\x18\x03 \x03(\v2\x11.gluon.v2.ASTNodeR\bchildren\x124\n" +
	"\blocation\x18\x04 \x01(\v2\x18.gluon.v2.SourceLocationR\blocationB$Z\"github.com/accretional/gluon/v2/pbb\x06proto3"

var (
	file_v2_ast_proto_rawDescOnce sync.Once
	file_v2_ast_proto_rawDescData []byte
)

func file_v2_ast_proto_rawDescGZIP() []byte {
	file_v2_ast_proto_rawDescOnce.Do(func() {
		file_v2_ast_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v2_ast_proto_rawDesc), len(file_v2_ast_proto_rawDesc)))
	})
	return file_v2_ast_proto_rawDescData
}

var file_v2_ast_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v2_ast_proto_goTypes = []any{
	(*ASTDescriptor)(nil),  // 0: gluon.v2.ASTDescriptor
	(*ASTNode)(nil),        // 1: gluon.v2.ASTNode
	(*SourceLocation)(nil), // 2: gluon.v2.SourceLocation
}
var file_v2_ast_proto_depIdxs = []int32{
	1, // 0: gluon.v2.ASTDescriptor.root:type_name -> gluon.v2.ASTNode
	1, // 1: gluon.v2.ASTNode.children:type_name -> gluon.v2.ASTNode
	2, // 2: gluon.v2.ASTNode.location:type_name -> gluon.v2.SourceLocation
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v2_ast_proto_init() }
func file_v2_ast_proto_init() {
	if File_v2_ast_proto != nil {
		return
	}
	file_v2_source_location_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v2_ast_proto_rawDesc), len(file_v2_ast_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v2_ast_proto_goTypes,
		DependencyIndexes: file_v2_ast_proto_depIdxs,
		MessageInfos:      file_v2_ast_proto_msgTypes,
	}.Build()
	File_v2_ast_proto = out.File
	file_v2_ast_proto_goTypes = nil
	file_v2_ast_proto_depIdxs = nil
}
