// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: v2/astkit.proto

// The Transformer service exposes universal tree operations over v2
// ASTNode trees. It is the RPC surface that proto-expr scripts drive
// via Dispatch — see v2/metaparser.proto's Transform flow.
//
// The Go implementation lives in v2/astkit (pure-Go helpers) and
// v2/astkit/server (Transformer impl). This proto was seeded from
// gluon/codegen.OnboardDir("astkit", "v2/astkit") and then edited to
// (a) use the gluon.v2 package namespace, (b) add the v2/ast.proto
// import, and (c) reference ASTNode unqualified (same package).

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Transformer_Find_FullMethodName         = "/gluon.v2.Transformer/Find"
	Transformer_FindAll_FullMethodName      = "/gluon.v2.Transformer/FindAll"
	Transformer_Count_FullMethodName        = "/gluon.v2.Transformer/Count"
	Transformer_ReplaceKind_FullMethodName  = "/gluon.v2.Transformer/ReplaceKind"
	Transformer_ReplaceValue_FullMethodName = "/gluon.v2.Transformer/ReplaceValue"
	Transformer_Filter_FullMethodName       = "/gluon.v2.Transformer/Filter"
)

// TransformerClient is the client API for Transformer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Transformer is the gRPC surface for language-agnostic tree
// operations. Each RPC takes an ASTNode tree and returns either a
// query result or a rewritten tree; inputs are never mutated.
type TransformerClient interface {
	Find(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error)
	FindAll(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindAllResponse, error)
	Count(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*CountResponse, error)
	ReplaceKind(ctx context.Context, in *ReplaceRequest, opts ...grpc.CallOption) (*ReplaceResponse, error)
	ReplaceValue(ctx context.Context, in *ReplaceRequest, opts ...grpc.CallOption) (*ReplaceResponse, error)
	Filter(ctx context.Context, in *FilterRequest, opts ...grpc.CallOption) (*FilterResponse, error)
}

type transformerClient struct {
	cc grpc.ClientConnInterface
}

func NewTransformerClient(cc grpc.ClientConnInterface) TransformerClient {
	return &transformerClient{cc}
}

func (c *transformerClient) Find(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindResponse)
	err := c.cc.Invoke(ctx, Transformer_Find_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transformerClient) FindAll(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindAllResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindAllResponse)
	err := c.cc.Invoke(ctx, Transformer_FindAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transformerClient) Count(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*CountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountResponse)
	err := c.cc.Invoke(ctx, Transformer_Count_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transformerClient) ReplaceKind(ctx context.Context, in *ReplaceRequest, opts ...grpc.CallOption) (*ReplaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplaceResponse)
	err := c.cc.Invoke(ctx, Transformer_ReplaceKind_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transformerClient) ReplaceValue(ctx context.Context, in *ReplaceRequest, opts ...grpc.CallOption) (*ReplaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplaceResponse)
	err := c.cc.Invoke(ctx, Transformer_ReplaceValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transformerClient) Filter(ctx context.Context, in *FilterRequest, opts ...grpc.CallOption) (*FilterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FilterResponse)
	err := c.cc.Invoke(ctx, Transformer_Filter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransformerServer is the server API for Transformer service.
// All implementations must embed UnimplementedTransformerServer
// for forward compatibility.
//
// Transformer is the gRPC surface for language-agnostic tree
// operations. Each RPC takes an ASTNode tree and returns either a
// query result or a rewritten tree; inputs are never mutated.
type TransformerServer interface {
	Find(context.Context, *FindRequest) (*FindResponse, error)
	FindAll(context.Context, *FindRequest) (*FindAllResponse, error)
	Count(context.Context, *FindRequest) (*CountResponse, error)
	ReplaceKind(context.Context, *ReplaceRequest) (*ReplaceResponse, error)
	ReplaceValue(context.Context, *ReplaceRequest) (*ReplaceResponse, error)
	Filter(context.Context, *FilterRequest) (*FilterResponse, error)
	mustEmbedUnimplementedTransformerServer()
}

// UnimplementedTransformerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransformerServer struct{}

func (UnimplementedTransformerServer) Find(context.Context, *FindRequest) (*FindResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Find not implemented")
}
func (UnimplementedTransformerServer) FindAll(context.Context, *FindRequest) (*FindAllResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindAll not implemented")
}
func (UnimplementedTransformerServer) Count(context.Context, *FindRequest) (*CountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Count not implemented")
}
func (UnimplementedTransformerServer) ReplaceKind(context.Context, *ReplaceRequest) (*ReplaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplaceKind not implemented")
}
func (UnimplementedTransformerServer) ReplaceValue(context.Context, *ReplaceRequest) (*ReplaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplaceValue not implemented")
}
func (UnimplementedTransformerServer) Filter(context.Context, *FilterRequest) (*FilterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Filter not implemented")
}
func (UnimplementedTransformerServer) mustEmbedUnimplementedTransformerServer() {}
func (UnimplementedTransformerServer) testEmbeddedByValue()                     {}

// UnsafeTransformerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransformerServer will
// result in compilation errors.
type UnsafeTransformerServer interface {
	mustEmbedUnimplementedTransformerServer()
}

func RegisterTransformerServer(s grpc.ServiceRegistrar, srv TransformerServer) {
	// If the following call panics, it indicates UnimplementedTransformerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Transformer_ServiceDesc, srv)
}

func _Transformer_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransformerServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Transformer_Find_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransformerServer).Find(ctx, req.(*FindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transformer_FindAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransformerServer).FindAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Transformer_FindAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransformerServer).FindAll(ctx, req.(*FindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transformer_Count_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransformerServer).Count(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Transformer_Count_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransformerServer).Count(ctx, req.(*FindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transformer_ReplaceKind_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransformerServer).ReplaceKind(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Transformer_ReplaceKind_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransformerServer).ReplaceKind(ctx, req.(*ReplaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transformer_ReplaceValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransformerServer).ReplaceValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Transformer_ReplaceValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransformerServer).ReplaceValue(ctx, req.(*ReplaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transformer_Filter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransformerServer).Filter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Transformer_Filter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransformerServer).Filter(ctx, req.(*FilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Transformer_ServiceDesc is the grpc.ServiceDesc for Transformer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Transformer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gluon.v2.Transformer",
	HandlerType: (*TransformerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Find",
			Handler:    _Transformer_Find_Handler,
		},
		{
			MethodName: "FindAll",
			Handler:    _Transformer_FindAll_Handler,
		},
		{
			MethodName: "Count",
			Handler:    _Transformer_Count_Handler,
		},
		{
			MethodName: "ReplaceKind",
			Handler:    _Transformer_ReplaceKind_Handler,
		},
		{
			MethodName: "ReplaceValue",
			Handler:    _Transformer_ReplaceValue_Handler,
		},
		{
			MethodName: "Filter",
			Handler:    _Transformer_Filter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v2/astkit.proto",
}
