// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: v2/astkit.proto

// The Transformer service exposes universal tree operations over v2
// ASTNode trees. It is the RPC surface that proto-expr scripts drive
// via Dispatch — see v2/metaparser.proto's Transform flow.
//
// The Go implementation lives in v2/astkit (pure-Go helpers) and
// v2/astkit/server (Transformer impl). This proto was seeded from
// gluon/codegen.OnboardDir("astkit", "v2/astkit") and then edited to
// (a) use the gluon.v2 package namespace, (b) add the v2/ast.proto
// import, and (c) reference ASTNode unqualified (same package).

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Root  *ASTNode               `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	// Kind and Value are ANDed. An empty field is ignored; at least one
	// must be set — empty-predicate requests return InvalidArgument.
	Kind          string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Value         string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindRequest) Reset() {
	*x = FindRequest{}
	mi := &file_v2_astkit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRequest) ProtoMessage() {}

func (x *FindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_astkit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRequest.ProtoReflect.Descriptor instead.
func (*FindRequest) Descriptor() ([]byte, []int) {
	return file_v2_astkit_proto_rawDescGZIP(), []int{0}
}

func (x *FindRequest) GetRoot() *ASTNode {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *FindRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *FindRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type FindResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// First matching descendant (inclusive of root), or unset if none.
	Node          *ASTNode `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindResponse) Reset() {
	*x = FindResponse{}
	mi := &file_v2_astkit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindResponse) ProtoMessage() {}

func (x *FindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v2_astkit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindResponse.ProtoReflect.Descriptor instead.
func (*FindResponse) Descriptor() ([]byte, []int) {
	return file_v2_astkit_proto_rawDescGZIP(), []int{1}
}

func (x *FindResponse) GetNode() *ASTNode {
	if x != nil {
		return x.Node
	}
	return nil
}

type FindAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*ASTNode             `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllResponse) Reset() {
	*x = FindAllResponse{}
	mi := &file_v2_astkit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllResponse) ProtoMessage() {}

func (x *FindAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v2_astkit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllResponse.ProtoReflect.Descriptor instead.
func (*FindAllResponse) Descriptor() ([]byte, []int) {
	return file_v2_astkit_proto_rawDescGZIP(), []int{2}
}

func (x *FindAllResponse) GetNodes() []*ASTNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type CountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountResponse) Reset() {
	*x = CountResponse{}
	mi := &file_v2_astkit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountResponse) ProtoMessage() {}

func (x *CountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v2_astkit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountResponse.ProtoReflect.Descriptor instead.
func (*CountResponse) Descriptor() ([]byte, []int) {
	return file_v2_astkit_proto_rawDescGZIP(), []int{3}
}

func (x *CountResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ReplaceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Root  *ASTNode               `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	// ReplaceKind: nodes whose Kind == from get Kind = to.
	// ReplaceValue: leaves whose Value == from get Value = to.
	From          string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplaceRequest) Reset() {
	*x = ReplaceRequest{}
	mi := &file_v2_astkit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceRequest) ProtoMessage() {}

func (x *ReplaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_astkit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceRequest.ProtoReflect.Descriptor instead.
func (*ReplaceRequest) Descriptor() ([]byte, []int) {
	return file_v2_astkit_proto_rawDescGZIP(), []int{4}
}

func (x *ReplaceRequest) GetRoot() *ASTNode {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *ReplaceRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ReplaceRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type ReplaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Root          *ASTNode               `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplaceResponse) Reset() {
	*x = ReplaceResponse{}
	mi := &file_v2_astkit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceResponse) ProtoMessage() {}

func (x *ReplaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v2_astkit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceResponse.ProtoReflect.Descriptor instead.
func (*ReplaceResponse) Descriptor() ([]byte, []int) {
	return file_v2_astkit_proto_rawDescGZIP(), []int{5}
}

func (x *ReplaceResponse) GetRoot() *ASTNode {
	if x != nil {
		return x.Root
	}
	return nil
}

type FilterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Root  *ASTNode               `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	// Kind and Value match as in FindRequest. Matching interior nodes
	// are dropped and their children are lifted into the parent;
	// matching leaves are dropped outright.
	Kind          string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Value         string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterRequest) Reset() {
	*x = FilterRequest{}
	mi := &file_v2_astkit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterRequest) ProtoMessage() {}

func (x *FilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_astkit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterRequest.ProtoReflect.Descriptor instead.
func (*FilterRequest) Descriptor() ([]byte, []int) {
	return file_v2_astkit_proto_rawDescGZIP(), []int{6}
}

func (x *FilterRequest) GetRoot() *ASTNode {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *FilterRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *FilterRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type FilterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Root          *ASTNode               `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterResponse) Reset() {
	*x = FilterResponse{}
	mi := &file_v2_astkit_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterResponse) ProtoMessage() {}

func (x *FilterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v2_astkit_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterResponse.ProtoReflect.Descriptor instead.
func (*FilterResponse) Descriptor() ([]byte, []int) {
	return file_v2_astkit_proto_rawDescGZIP(), []int{7}
}

func (x *FilterResponse) GetRoot() *ASTNode {
	if x != nil {
		return x.Root
	}
	return nil
}

var File_v2_astkit_proto protoreflect.FileDescriptor

const file_v2_astkit_proto_rawDesc = "" +
	"\n" +
	"\x0fv2/astkit.proto\x12\bgluon.v2\x1a\fv2/ast.proto\"^\n" +
	"\vFindRequest\x12%\n" +
	"\x04root\x18\x01 \x01(\v2\x11.gluon.v2.ASTNodeR\x04root\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"5\n" +
	"\fFindResponse\x12%\n" +
	"\x04node\x18\x01 \x01(\v2\x11.gluon.v2.ASTNodeR\x04node\":\n" +
	"\x0fFindAllResponse\x12'\n" +
	"\x05nodes\x18\x01 \x03(\v2\x11.gluon.v2.ASTNodeR\x05nodes\"%\n" +
	"\rCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"[\n" +
	"\x0eReplaceRequest\x12%\n" +
	"\x04root\x18\x01 \x01(\v2\x11.gluon.v2.ASTNodeR\x04root\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\"8\n" +
	"\x0fReplaceResponse\x12%\n" +
	"\x04root\x18\x01 \x01(\v2\x11.gluon.v2.ASTNodeR\x04root\"`\n" +
	"\rFilterRequest\x12%\n" +
	"\x04root\x18\x01 \x01(\v2\x11.gluon.v2.ASTNodeR\x04root\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"7\n" +
	"\x0eFilterResponse\x12%\n" +
	"\x04root\x18\x01 \x01(\v2\x11.gluon.v2.ASTNodeR\x04root2\x80\x03\n" +
	"\vTransformer\x125\n" +
	"\x04Find\x12\x15.gluon.v2.FindRequest\x1a\x16.gluon.v2.FindResponse\x12;\n" +
	"\aFindAll\x12\x15.gluon.v2.FindRequest\x1a\x19.gluon.v2.FindAllResponse\x127\n" +
	"\x05Count\x12\x15.gluon.v2.FindRequest\x1a\x17.gluon.v2.CountResponse\x12B\n" +
	"\vReplaceKind\x12\x18.gluon.v2.ReplaceRequest\x1a\x19.gluon.v2.ReplaceResponse\x12C\n" +
	"\fReplaceValue\x12\x18.gluon.v2.ReplaceRequest\x1a\x19.gluon.v2.ReplaceResponse\x12;\n" +
	"\x06Filter\x12\x17.gluon.v2.FilterRequest\x1a\x18.gluon.v2.FilterResponseB$Z\"github.com/accretional/gluon/v2/pbb\x06proto3"

var (
	file_v2_astkit_proto_rawDescOnce sync.Once
	file_v2_astkit_proto_rawDescData []byte
)

func file_v2_astkit_proto_rawDescGZIP() []byte {
	file_v2_astkit_proto_rawDescOnce.Do(func() {
		file_v2_astkit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v2_astkit_proto_rawDesc), len(file_v2_astkit_proto_rawDesc)))
	})
	return file_v2_astkit_proto_rawDescData
}

var file_v2_astkit_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_v2_astkit_proto_goTypes = []any{
	(*FindRequest)(nil),     // 0: gluon.v2.FindRequest
	(*FindResponse)(nil),    // 1: gluon.v2.FindResponse
	(*FindAllResponse)(nil), // 2: gluon.v2.FindAllResponse
	(*CountResponse)(nil),   // 3: gluon.v2.CountResponse
	(*ReplaceRequest)(nil),  // 4: gluon.v2.ReplaceRequest
	(*ReplaceResponse)(nil), // 5: gluon.v2.ReplaceResponse
	(*FilterRequest)(nil),   // 6: gluon.v2.FilterRequest
	(*FilterResponse)(nil),  // 7: gluon.v2.FilterResponse
	(*ASTNode)(nil),         // 8: gluon.v2.ASTNode
}
var file_v2_astkit_proto_depIdxs = []int32{
	8,  // 0: gluon.v2.FindRequest.root:type_name -> gluon.v2.ASTNode
	8,  // 1: gluon.v2.FindResponse.node:type_name -> gluon.v2.ASTNode
	8,  // 2: gluon.v2.FindAllResponse.nodes:type_name -> gluon.v2.ASTNode
	8,  // 3: gluon.v2.ReplaceRequest.root:type_name -> gluon.v2.ASTNode
	8,  // 4: gluon.v2.ReplaceResponse.root:type_name -> gluon.v2.ASTNode
	8,  // 5: gluon.v2.FilterRequest.root:type_name -> gluon.v2.ASTNode
	8,  // 6: gluon.v2.FilterResponse.root:type_name -> gluon.v2.ASTNode
	0,  // 7: gluon.v2.Transformer.Find:input_type -> gluon.v2.FindRequest
	0,  // 8: gluon.v2.Transformer.FindAll:input_type -> gluon.v2.FindRequest
	0,  // 9: gluon.v2.Transformer.Count:input_type -> gluon.v2.FindRequest
	4,  // 10: gluon.v2.Transformer.ReplaceKind:input_type -> gluon.v2.ReplaceRequest
	4,  // 11: gluon.v2.Transformer.ReplaceValue:input_type -> gluon.v2.ReplaceRequest
	6,  // 12: gluon.v2.Transformer.Filter:input_type -> gluon.v2.FilterRequest
	1,  // 13: gluon.v2.Transformer.Find:output_type -> gluon.v2.FindResponse
	2,  // 14: gluon.v2.Transformer.FindAll:output_type -> gluon.v2.FindAllResponse
	3,  // 15: gluon.v2.Transformer.Count:output_type -> gluon.v2.CountResponse
	5,  // 16: gluon.v2.Transformer.ReplaceKind:output_type -> gluon.v2.ReplaceResponse
	5,  // 17: gluon.v2.Transformer.ReplaceValue:output_type -> gluon.v2.ReplaceResponse
	7,  // 18: gluon.v2.Transformer.Filter:output_type -> gluon.v2.FilterResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_v2_astkit_proto_init() }
func file_v2_astkit_proto_init() {
	if File_v2_astkit_proto != nil {
		return
	}
	file_v2_ast_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v2_astkit_proto_rawDesc), len(file_v2_astkit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v2_astkit_proto_goTypes,
		DependencyIndexes: file_v2_astkit_proto_depIdxs,
		MessageInfos:      file_v2_astkit_proto_msgTypes,
	}.Build()
	File_v2_astkit_proto = out.File
	file_v2_astkit_proto_goTypes = nil
	file_v2_astkit_proto_depIdxs = nil
}
