// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: v2/document.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DocumentDescriptor is a named, addressable bundle of text — conceptually
// "one source file", but without assuming the filesystem.
//
// The `text` field is `repeated` so a document can be assembled from
// heterogeneously-encoded chunks (an ASCII run, a unicode burst, a
// by-reference pointer) without forcing a single encoding on the whole
// payload. Readers should treat the chunks as logically concatenated.
type DocumentDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable name (e.g. "sqlite.ebnf"). Not required to be unique.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Identifier for the document's origin — typically a file:// or https://
	// URI, but any stable identifier works (e.g. "stdin", "embedded://foo").
	Uri string `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	// Text content, split into chunks. See TextDescriptor for why chunks.
	Text          []*TextDescriptor `protobuf:"bytes,3,rep,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentDescriptor) Reset() {
	*x = DocumentDescriptor{}
	mi := &file_v2_document_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentDescriptor) ProtoMessage() {}

func (x *DocumentDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_v2_document_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentDescriptor.ProtoReflect.Descriptor instead.
func (*DocumentDescriptor) Descriptor() ([]byte, []int) {
	return file_v2_document_proto_rawDescGZIP(), []int{0}
}

func (x *DocumentDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DocumentDescriptor) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *DocumentDescriptor) GetText() []*TextDescriptor {
	if x != nil {
		return x.Text
	}
	return nil
}

var File_v2_document_proto protoreflect.FileDescriptor

const file_v2_document_proto_rawDesc = "" +
	"\n" +
	"\x11v2/document.proto\x12\bgluon.v2\x1a\rv2/text.proto\"h\n" +
	"\x12DocumentDescriptor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\x12,\n" +
	"\x04text\x18\x03 \x03(\v2\x18.gluon.v2.TextDescriptorR\x04textB$Z\"github.com/accretional/gluon/v2/pbb\x06proto3"

var (
	file_v2_document_proto_rawDescOnce sync.Once
	file_v2_document_proto_rawDescData []byte
)

func file_v2_document_proto_rawDescGZIP() []byte {
	file_v2_document_proto_rawDescOnce.Do(func() {
		file_v2_document_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v2_document_proto_rawDesc), len(file_v2_document_proto_rawDesc)))
	})
	return file_v2_document_proto_rawDescData
}

var file_v2_document_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v2_document_proto_goTypes = []any{
	(*DocumentDescriptor)(nil), // 0: gluon.v2.DocumentDescriptor
	(*TextDescriptor)(nil),     // 1: gluon.v2.TextDescriptor
}
var file_v2_document_proto_depIdxs = []int32{
	1, // 0: gluon.v2.DocumentDescriptor.text:type_name -> gluon.v2.TextDescriptor
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v2_document_proto_init() }
func file_v2_document_proto_init() {
	if File_v2_document_proto != nil {
		return
	}
	file_v2_text_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v2_document_proto_rawDesc), len(file_v2_document_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v2_document_proto_goTypes,
		DependencyIndexes: file_v2_document_proto_depIdxs,
		MessageInfos:      file_v2_document_proto_msgTypes,
	}.Build()
	File_v2_document_proto = out.File
	file_v2_document_proto_goTypes = nil
	file_v2_document_proto_depIdxs = nil
}
