// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: v2/grammar.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Production is a single node in the right-hand side of a rule.
//
// Structure is encoded positionally rather than as a tree:
//
//   - A rule's `expressions` is a flat list of Productions.
//   - Delimiters (ALTERNATION, CONCATENATION, …) sit *between* siblings
//     and indicate how their neighbors relate.
//   - Scopers open a nested sub-list in their own `body`.
//
// This keeps the serialized form close to the source — no artificial
// Sequence/Alternation wrapper messages — and means each variant stays
// small (an enum, a repeated-Production, or a plain string).
type Production struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Production_Delimiter
	//	*Production_Scoper
	//	*Production_Terminal
	//	*Production_Nonterminal
	//	*Production_Range
	Kind          isProduction_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Production) Reset() {
	*x = Production{}
	mi := &file_v2_grammar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Production) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Production) ProtoMessage() {}

func (x *Production) ProtoReflect() protoreflect.Message {
	mi := &file_v2_grammar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Production.ProtoReflect.Descriptor instead.
func (*Production) Descriptor() ([]byte, []int) {
	return file_v2_grammar_proto_rawDescGZIP(), []int{0}
}

func (x *Production) GetKind() isProduction_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Production) GetDelimiter() Delimiter {
	if x != nil {
		if x, ok := x.Kind.(*Production_Delimiter); ok {
			return x.Delimiter
		}
	}
	return Delimiter_DELIMITER_UNSPECIFIED
}

func (x *Production) GetScoper() *ScopedProduction {
	if x != nil {
		if x, ok := x.Kind.(*Production_Scoper); ok {
			return x.Scoper
		}
	}
	return nil
}

func (x *Production) GetTerminal() string {
	if x != nil {
		if x, ok := x.Kind.(*Production_Terminal); ok {
			return x.Terminal
		}
	}
	return ""
}

func (x *Production) GetNonterminal() string {
	if x != nil {
		if x, ok := x.Kind.(*Production_Nonterminal); ok {
			return x.Nonterminal
		}
	}
	return ""
}

func (x *Production) GetRange() *StringRange {
	if x != nil {
		if x, ok := x.Kind.(*Production_Range); ok {
			return x.Range
		}
	}
	return nil
}

type isProduction_Kind interface {
	isProduction_Kind()
}

type Production_Delimiter struct {
	// A positional separator. Its role (ALTERNATION, CONCATENATION, …)
	// tells readers how the surrounding siblings combine. The character(s)
	// that produced it are resolved via the rule's LexDescriptor.
	Delimiter Delimiter `protobuf:"varint,1,opt,name=delimiter,proto3,enum=gluon.v2.Delimiter,oneof"`
}

type Production_Scoper struct {
	// A bracketed sub-expression. `kind` says what kind of bracket
	// (OPTIONAL, REPETITION, GROUP, TERMINAL, COMMENT) and `body` holds
	// its inner productions as a flat list.
	Scoper *ScopedProduction `protobuf:"bytes,2,opt,name=scoper,proto3,oneof"`
}

type Production_Terminal struct {
	// A literal terminal string (unquoted). Empty string is valid
	// (matches nothing); consumers should treat absence of kind as an
	// uninitialized node.
	Terminal string `protobuf:"bytes,3,opt,name=terminal,proto3,oneof"`
}

type Production_Nonterminal struct {
	// A reference to another rule by name.
	Nonterminal string `protobuf:"bytes,4,opt,name=nonterminal,proto3,oneof"`
}

type Production_Range struct {
	// An inclusive character range, e.g. "a" … "z".
	Range *StringRange `protobuf:"bytes,5,opt,name=range,proto3,oneof"`
}

func (*Production_Delimiter) isProduction_Kind() {}

func (*Production_Scoper) isProduction_Kind() {}

func (*Production_Terminal) isProduction_Kind() {}

func (*Production_Nonterminal) isProduction_Kind() {}

func (*Production_Range) isProduction_Kind() {}

// ScopedProduction is the body of a scoper (optional, repetition, group,
// terminal, or comment) together with a tag identifying which scoper role
// produced it.
type ScopedProduction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  Scoper                 `protobuf:"varint,1,opt,name=kind,proto3,enum=gluon.v2.Scoper" json:"kind,omitempty"`
	// Inner expressions, interpreted the same way as a rule's top-level
	// expressions (delimiters between siblings, scopers nesting further).
	Body          []*Production `protobuf:"bytes,2,rep,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScopedProduction) Reset() {
	*x = ScopedProduction{}
	mi := &file_v2_grammar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScopedProduction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScopedProduction) ProtoMessage() {}

func (x *ScopedProduction) ProtoReflect() protoreflect.Message {
	mi := &file_v2_grammar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScopedProduction.ProtoReflect.Descriptor instead.
func (*ScopedProduction) Descriptor() ([]byte, []int) {
	return file_v2_grammar_proto_rawDescGZIP(), []int{1}
}

func (x *ScopedProduction) GetKind() Scoper {
	if x != nil {
		return x.Kind
	}
	return Scoper_SCOPER_UNSPECIFIED
}

func (x *ScopedProduction) GetBody() []*Production {
	if x != nil {
		return x.Body
	}
	return nil
}

// StringRange represents an inclusive character range like "a" … "z".
// Both bounds are strings (not single runes) so multi-byte characters
// and multi-character bounds can be expressed without a separate rune
// type.
type StringRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lower         string                 `protobuf:"bytes,1,opt,name=lower,proto3" json:"lower,omitempty"`
	Upper         string                 `protobuf:"bytes,2,opt,name=upper,proto3" json:"upper,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringRange) Reset() {
	*x = StringRange{}
	mi := &file_v2_grammar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringRange) ProtoMessage() {}

func (x *StringRange) ProtoReflect() protoreflect.Message {
	mi := &file_v2_grammar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringRange.ProtoReflect.Descriptor instead.
func (*StringRange) Descriptor() ([]byte, []int) {
	return file_v2_grammar_proto_rawDescGZIP(), []int{2}
}

func (x *StringRange) GetLower() string {
	if x != nil {
		return x.Lower
	}
	return ""
}

func (x *StringRange) GetUpper() string {
	if x != nil {
		return x.Upper
	}
	return ""
}

// RuleDescriptor is a single production rule.
//
// Example: `letter = "A" | "B" | "C" ;`  becomes
//
//	name = "letter"
//	expressions = [
//	  Production{terminal: "A"},
//	  Production{delimiter: ALTERNATION},
//	  Production{terminal: "B"},
//	  Production{delimiter: ALTERNATION},
//	  Production{terminal: "C"},
//	]
type RuleDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Left-hand-side name (e.g. "letter").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Flat list of productions making up the RHS. Structure is encoded by
	// the positions and kinds of delimiters/scopers — see Production.
	Expressions   []*Production `protobuf:"bytes,2,rep,name=expressions,proto3" json:"expressions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleDescriptor) Reset() {
	*x = RuleDescriptor{}
	mi := &file_v2_grammar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleDescriptor) ProtoMessage() {}

func (x *RuleDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_v2_grammar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleDescriptor.ProtoReflect.Descriptor instead.
func (*RuleDescriptor) Descriptor() ([]byte, []int) {
	return file_v2_grammar_proto_rawDescGZIP(), []int{3}
}

func (x *RuleDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RuleDescriptor) GetExpressions() []*Production {
	if x != nil {
		return x.Expressions
	}
	return nil
}

// GrammarDescriptor pairs a lex configuration with a set of rules.
// The lex descriptor is what was used to read the rules out of their
// source notation; downstream consumers rely on it to interpret each
// Delimiter's role.
type GrammarDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional name (e.g. "sqlite", "go").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Lexical conventions for the notation the rules were written in.
	Lex *LexDescriptor `protobuf:"bytes,2,opt,name=lex,proto3" json:"lex,omitempty"`
	// Rules defining the grammar.
	Rules         []*RuleDescriptor `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrammarDescriptor) Reset() {
	*x = GrammarDescriptor{}
	mi := &file_v2_grammar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrammarDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrammarDescriptor) ProtoMessage() {}

func (x *GrammarDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_v2_grammar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrammarDescriptor.ProtoReflect.Descriptor instead.
func (*GrammarDescriptor) Descriptor() ([]byte, []int) {
	return file_v2_grammar_proto_rawDescGZIP(), []int{4}
}

func (x *GrammarDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GrammarDescriptor) GetLex() *LexDescriptor {
	if x != nil {
		return x.Lex
	}
	return nil
}

func (x *GrammarDescriptor) GetRules() []*RuleDescriptor {
	if x != nil {
		return x.Rules
	}
	return nil
}

var File_v2_grammar_proto protoreflect.FileDescriptor

const file_v2_grammar_proto_rawDesc = "" +
	"\n" +
	"\x10v2/grammar.proto\x12\bgluon.v2\x1a\fv2/lex.proto\"\xf0\x01\n" +
	"\n" +
	"Production\x123\n" +
	"\tdelimiter\x18\x01 \x01(\x0e2\x13.gluon.v2.DelimiterH\x00R\tdelimiter\x124\n" +
	"\x06scoper\x18\x02 \x01(\v2\x1a.gluon.v2.ScopedProductionH\x00R\x06scoper\x12\x1c\n" +
	"\bterminal\x18\x03 \x01(\tH\x00R\bterminal\x12\"\n" +
	"\vnonterminal\x18\x04 \x01(\tH\x00R\vnonterminal\x12-\n" +
	"\x05range\x18\x05 \x01(\v2\x15.gluon.v2.StringRangeH\x00R\x05rangeB\x06\n" +
	"\x04kind\"b\n" +
	"\x10ScopedProduction\x12$\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x10.gluon.v2.ScoperR\x04kind\x12(\n" +
	"\x04body\x18\x02 \x03(\v2\x14.gluon.v2.ProductionR\x04body\"9\n" +
	"\vStringRange\x12\x14\n" +
	"\x05lower\x18\x01 \x01(\tR\x05lower\x12\x14\n" +
	"\x05upper\x18\x02 \x01(\tR\x05upper\"\\\n" +
	"\x0eRuleDescriptor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x126\n" +
	"\vexpressions\x18\x02 \x03(\v2\x14.gluon.v2.ProductionR\vexpressions\"\x82\x01\n" +
	"\x11GrammarDescriptor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12)\n" +
	"\x03lex\x18\x02 \x01(\v2\x17.gluon.v2.LexDescriptorR\x03lex\x12.\n" +
	"\x05rules\x18\x03 \x03(\v2\x18.gluon.v2.RuleDescriptorR\x05rulesB$Z\"github.com/accretional/gluon/v2/pbb\x06proto3"

var (
	file_v2_grammar_proto_rawDescOnce sync.Once
	file_v2_grammar_proto_rawDescData []byte
)

func file_v2_grammar_proto_rawDescGZIP() []byte {
	file_v2_grammar_proto_rawDescOnce.Do(func() {
		file_v2_grammar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v2_grammar_proto_rawDesc), len(file_v2_grammar_proto_rawDesc)))
	})
	return file_v2_grammar_proto_rawDescData
}

var file_v2_grammar_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_v2_grammar_proto_goTypes = []any{
	(*Production)(nil),        // 0: gluon.v2.Production
	(*ScopedProduction)(nil),  // 1: gluon.v2.ScopedProduction
	(*StringRange)(nil),       // 2: gluon.v2.StringRange
	(*RuleDescriptor)(nil),    // 3: gluon.v2.RuleDescriptor
	(*GrammarDescriptor)(nil), // 4: gluon.v2.GrammarDescriptor
	(Delimiter)(0),            // 5: gluon.v2.Delimiter
	(Scoper)(0),               // 6: gluon.v2.Scoper
	(*LexDescriptor)(nil),     // 7: gluon.v2.LexDescriptor
}
var file_v2_grammar_proto_depIdxs = []int32{
	5, // 0: gluon.v2.Production.delimiter:type_name -> gluon.v2.Delimiter
	1, // 1: gluon.v2.Production.scoper:type_name -> gluon.v2.ScopedProduction
	2, // 2: gluon.v2.Production.range:type_name -> gluon.v2.StringRange
	6, // 3: gluon.v2.ScopedProduction.kind:type_name -> gluon.v2.Scoper
	0, // 4: gluon.v2.ScopedProduction.body:type_name -> gluon.v2.Production
	0, // 5: gluon.v2.RuleDescriptor.expressions:type_name -> gluon.v2.Production
	7, // 6: gluon.v2.GrammarDescriptor.lex:type_name -> gluon.v2.LexDescriptor
	3, // 7: gluon.v2.GrammarDescriptor.rules:type_name -> gluon.v2.RuleDescriptor
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_v2_grammar_proto_init() }
func file_v2_grammar_proto_init() {
	if File_v2_grammar_proto != nil {
		return
	}
	file_v2_lex_proto_init()
	file_v2_grammar_proto_msgTypes[0].OneofWrappers = []any{
		(*Production_Delimiter)(nil),
		(*Production_Scoper)(nil),
		(*Production_Terminal)(nil),
		(*Production_Nonterminal)(nil),
		(*Production_Range)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v2_grammar_proto_rawDesc), len(file_v2_grammar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v2_grammar_proto_goTypes,
		DependencyIndexes: file_v2_grammar_proto_depIdxs,
		MessageInfos:      file_v2_grammar_proto_msgTypes,
	}.Build()
	File_v2_grammar_proto = out.File
	file_v2_grammar_proto_goTypes = nil
	file_v2_grammar_proto_depIdxs = nil
}
