// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: v2/lex.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Delimiter enumerates the roles played by single-character separators
// in an EBNF-style notation. Each value names *what the character does*,
// not what character is used — the mapping from character to role lives
// in LexDescriptor via SymbolDescriptor.
//
// This enum is deliberately small: downstream artifacts (rules, CSTs)
// persist the role as an enum value rather than re-encoding the raw
// character, which keeps those artifacts compact and notation-agnostic.
type Delimiter int32

const (
	// ==========================================================================
	// LOAD-BEARING: DELIMITER_UNSPECIFIED has a special meaning inside Token.
	//
	// When a Token's `kind` oneof is unset — which, because proto3 treats the
	// zero-valued enum as indistinguishable from an unset oneof field, also
	// includes a Token whose delimiter is DELIMITER_UNSPECIFIED — that Token
	// is interpreted as a LITERAL run starting at Token.offset, not as a
	// "missing delimiter." See Token in v2/tokens.proto.
	//
	// Do NOT reorder these enum values. Do NOT use DELIMITER_UNSPECIFIED as
	// a real delimiter role; it is the canonical tag for "this token is text."
	// ==========================================================================
	Delimiter_DELIMITER_UNSPECIFIED Delimiter = 0
	// Separates tokens without contributing to structure (space, tab, CR, LF).
	Delimiter_WHITESPACE Delimiter = 1
	// Separates a rule's name from its body. Standard EBNF: '='.
	Delimiter_DEFINITION Delimiter = 2
	// Joins sequential terms. Standard EBNF: ',' (may be implicit in other
	// notations, in which case no SymbolDescriptor carries this role).
	Delimiter_CONCATENATION Delimiter = 3
	// Marks the end of a rule. Standard EBNF: ';'. Go EBNF: '.'.
	Delimiter_TERMINATION Delimiter = 4
	// Separates alternative choices. Universally: '|'.
	Delimiter_ALTERNATION Delimiter = 5
)

// Enum value maps for Delimiter.
var (
	Delimiter_name = map[int32]string{
		0: "DELIMITER_UNSPECIFIED",
		1: "WHITESPACE",
		2: "DEFINITION",
		3: "CONCATENATION",
		4: "TERMINATION",
		5: "ALTERNATION",
	}
	Delimiter_value = map[string]int32{
		"DELIMITER_UNSPECIFIED": 0,
		"WHITESPACE":            1,
		"DEFINITION":            2,
		"CONCATENATION":         3,
		"TERMINATION":           4,
		"ALTERNATION":           5,
	}
)

func (x Delimiter) Enum() *Delimiter {
	p := new(Delimiter)
	*p = x
	return p
}

func (x Delimiter) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Delimiter) Descriptor() protoreflect.EnumDescriptor {
	return file_v2_lex_proto_enumTypes[0].Descriptor()
}

func (Delimiter) Type() protoreflect.EnumType {
	return &file_v2_lex_proto_enumTypes[0]
}

func (x Delimiter) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Delimiter.Descriptor instead.
func (Delimiter) EnumDescriptor() ([]byte, []int) {
	return file_v2_lex_proto_rawDescGZIP(), []int{0}
}

// Scoper enumerates the roles played by paired begin/end delimiters.
// Every scoper opens a nested context and must be closed by its matching
// partner; the body between them is treated as a sub-expression.
type Scoper int32

const (
	// ==========================================================================
	// LOAD-BEARING: SCOPER_UNSPECIFIED, like DELIMITER_UNSPECIFIED, participates
	// in the "this token is text" convention used by Token in v2/tokens.proto.
	// A Token whose `kind` is a ScoperToken carrying SCOPER_UNSPECIFIED on
	// either lhs or rhs is equivalent to an unset oneof — i.e. a literal run.
	//
	// Do NOT reorder. Do NOT use SCOPER_UNSPECIFIED as a real scoper role.
	// ==========================================================================
	Scoper_SCOPER_UNSPECIFIED Scoper = 0
	// Encloses an optional sub-expression (0 or 1 occurrence). Std EBNF: [ ].
	Scoper_OPTIONAL Scoper = 1
	// Encloses a repeated sub-expression (0..n occurrences). Std EBNF: { }.
	Scoper_REPETITION Scoper = 2
	// Encloses a grouped sub-expression (structural only). Std EBNF: ( ).
	Scoper_GROUP Scoper = 3
	// Encloses a terminal literal. Std EBNF: " " or ' '. Go also uses ` `.
	Scoper_TERMINAL Scoper = 4
	// Encloses a comment. Std EBNF: (* *). Go/C EBNF: /* */.
	Scoper_COMMENT Scoper = 5
)

// Enum value maps for Scoper.
var (
	Scoper_name = map[int32]string{
		0: "SCOPER_UNSPECIFIED",
		1: "OPTIONAL",
		2: "REPETITION",
		3: "GROUP",
		4: "TERMINAL",
		5: "COMMENT",
	}
	Scoper_value = map[string]int32{
		"SCOPER_UNSPECIFIED": 0,
		"OPTIONAL":           1,
		"REPETITION":         2,
		"GROUP":              3,
		"TERMINAL":           4,
		"COMMENT":            5,
	}
)

func (x Scoper) Enum() *Scoper {
	p := new(Scoper)
	*p = x
	return p
}

func (x Scoper) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Scoper) Descriptor() protoreflect.EnumDescriptor {
	return file_v2_lex_proto_enumTypes[1].Descriptor()
}

func (Scoper) Type() protoreflect.EnumType {
	return &file_v2_lex_proto_enumTypes[1]
}

func (x Scoper) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Scoper.Descriptor instead.
func (Scoper) EnumDescriptor() ([]byte, []int) {
	return file_v2_lex_proto_rawDescGZIP(), []int{1}
}

// LexicalDelimiter binds a Delimiter role to the actual character(s) that
// trigger it in a given notation.
type LexicalDelimiter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  Delimiter              `protobuf:"varint,1,opt,name=kind,proto3,enum=gluon.v2.Delimiter" json:"kind,omitempty"`
	// Character(s) that play this role. Typically a single rune, but kept
	// as a string so multi-character operators like "::=" can be expressed.
	Symbol        string `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LexicalDelimiter) Reset() {
	*x = LexicalDelimiter{}
	mi := &file_v2_lex_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LexicalDelimiter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LexicalDelimiter) ProtoMessage() {}

func (x *LexicalDelimiter) ProtoReflect() protoreflect.Message {
	mi := &file_v2_lex_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LexicalDelimiter.ProtoReflect.Descriptor instead.
func (*LexicalDelimiter) Descriptor() ([]byte, []int) {
	return file_v2_lex_proto_rawDescGZIP(), []int{0}
}

func (x *LexicalDelimiter) GetKind() Delimiter {
	if x != nil {
		return x.Kind
	}
	return Delimiter_DELIMITER_UNSPECIFIED
}

func (x *LexicalDelimiter) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// LexicalScoper binds a Scoper role to its begin/end character(s).
type LexicalScoper struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  Scoper                 `protobuf:"varint,1,opt,name=kind,proto3,enum=gluon.v2.Scoper" json:"kind,omitempty"`
	// Opening character(s). E.g. "[" for OPTIONAL, "(*" for COMMENT.
	Begin string `protobuf:"bytes,2,opt,name=begin,proto3" json:"begin,omitempty"`
	// Closing character(s). E.g. "]" for OPTIONAL, "*)" for COMMENT.
	End           string `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LexicalScoper) Reset() {
	*x = LexicalScoper{}
	mi := &file_v2_lex_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LexicalScoper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LexicalScoper) ProtoMessage() {}

func (x *LexicalScoper) ProtoReflect() protoreflect.Message {
	mi := &file_v2_lex_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LexicalScoper.ProtoReflect.Descriptor instead.
func (*LexicalScoper) Descriptor() ([]byte, []int) {
	return file_v2_lex_proto_rawDescGZIP(), []int{1}
}

func (x *LexicalScoper) GetKind() Scoper {
	if x != nil {
		return x.Kind
	}
	return Scoper_SCOPER_UNSPECIFIED
}

func (x *LexicalScoper) GetBegin() string {
	if x != nil {
		return x.Begin
	}
	return ""
}

func (x *LexicalScoper) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

// SymbolDescriptor wraps either a delimiter or a scoper. A LexDescriptor
// is a flat list of these; during lexing they are consulted to classify
// each incoming character run into the role it plays.
type SymbolDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*SymbolDescriptor_Delimiter
	//	*SymbolDescriptor_Scoper
	Kind          isSymbolDescriptor_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SymbolDescriptor) Reset() {
	*x = SymbolDescriptor{}
	mi := &file_v2_lex_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymbolDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymbolDescriptor) ProtoMessage() {}

func (x *SymbolDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_v2_lex_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymbolDescriptor.ProtoReflect.Descriptor instead.
func (*SymbolDescriptor) Descriptor() ([]byte, []int) {
	return file_v2_lex_proto_rawDescGZIP(), []int{2}
}

func (x *SymbolDescriptor) GetKind() isSymbolDescriptor_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *SymbolDescriptor) GetDelimiter() *LexicalDelimiter {
	if x != nil {
		if x, ok := x.Kind.(*SymbolDescriptor_Delimiter); ok {
			return x.Delimiter
		}
	}
	return nil
}

func (x *SymbolDescriptor) GetScoper() *LexicalScoper {
	if x != nil {
		if x, ok := x.Kind.(*SymbolDescriptor_Scoper); ok {
			return x.Scoper
		}
	}
	return nil
}

type isSymbolDescriptor_Kind interface {
	isSymbolDescriptor_Kind()
}

type SymbolDescriptor_Delimiter struct {
	Delimiter *LexicalDelimiter `protobuf:"bytes,1,opt,name=delimiter,proto3,oneof"`
}

type SymbolDescriptor_Scoper struct {
	Scoper *LexicalScoper `protobuf:"bytes,2,opt,name=scoper,proto3,oneof"`
}

func (*SymbolDescriptor_Delimiter) isSymbolDescriptor_Kind() {}

func (*SymbolDescriptor_Scoper) isSymbolDescriptor_Kind() {}

// LexDescriptor describes the lexical conventions of an EBNF-style
// notation. It's just a named bag of SymbolDescriptors — the shape
// of the notation is entirely determined by which roles are present
// and which characters are bound to them.
//
// Swapping LexDescriptors lets the same lexer/parser implementation
// handle ISO 14977, Go's spec notation, proto's notation, etc.
type LexDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable identifier for the notation (e.g. "iso-14977", "go").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The symbols that make up the notation.
	Symbols       []*SymbolDescriptor `protobuf:"bytes,2,rep,name=symbols,proto3" json:"symbols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LexDescriptor) Reset() {
	*x = LexDescriptor{}
	mi := &file_v2_lex_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LexDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LexDescriptor) ProtoMessage() {}

func (x *LexDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_v2_lex_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LexDescriptor.ProtoReflect.Descriptor instead.
func (*LexDescriptor) Descriptor() ([]byte, []int) {
	return file_v2_lex_proto_rawDescGZIP(), []int{3}
}

func (x *LexDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LexDescriptor) GetSymbols() []*SymbolDescriptor {
	if x != nil {
		return x.Symbols
	}
	return nil
}

var File_v2_lex_proto protoreflect.FileDescriptor

const file_v2_lex_proto_rawDesc = "" +
	"\n" +
	"\fv2/lex.proto\x12\bgluon.v2\"S\n" +
	"\x10LexicalDelimiter\x12'\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x13.gluon.v2.DelimiterR\x04kind\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\"]\n" +
	"\rLexicalScoper\x12$\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x10.gluon.v2.ScoperR\x04kind\x12\x14\n" +
	"\x05begin\x18\x02 \x01(\tR\x05begin\x12\x10\n" +
	"\x03end\x18\x03 \x01(\tR\x03end\"\x89\x01\n" +
	"\x10SymbolDescriptor\x12:\n" +
	"\tdelimiter\x18\x01 \x01(\v2\x1a.gluon.v2.LexicalDelimiterH\x00R\tdelimiter\x121\n" +
	"\x06scoper\x18\x02 \x01(\v2\x17.gluon.v2.LexicalScoperH\x00R\x06scoperB\x06\n" +
	"\x04kind\"Y\n" +
	"\rLexDescriptor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x124\n" +
	"\asymbols\x18\x02 \x03(\v2\x1a.gluon.v2.SymbolDescriptorR\asymbols*{\n" +
	"\tDelimiter\x12\x19\n" +
	"\x15DELIMITER_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"WHITESPACE\x10\x01\x12\x0e\n" +
	"\n" +
	"DEFINITION\x10\x02\x12\x11\n" +
	"\rCONCATENATION\x10\x03\x12\x0f\n" +
	"\vTERMINATION\x10\x04\x12\x0f\n" +
	"\vALTERNATION\x10\x05*d\n" +
	"\x06Scoper\x12\x16\n" +
	"\x12SCOPER_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bOPTIONAL\x10\x01\x12\x0e\n" +
	"\n" +
	"REPETITION\x10\x02\x12\t\n" +
	"\x05GROUP\x10\x03\x12\f\n" +
	"\bTERMINAL\x10\x04\x12\v\n" +
	"\aCOMMENT\x10\x05B$Z\"github.com/accretional/gluon/v2/pbb\x06proto3"

var (
	file_v2_lex_proto_rawDescOnce sync.Once
	file_v2_lex_proto_rawDescData []byte
)

func file_v2_lex_proto_rawDescGZIP() []byte {
	file_v2_lex_proto_rawDescOnce.Do(func() {
		file_v2_lex_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v2_lex_proto_rawDesc), len(file_v2_lex_proto_rawDesc)))
	})
	return file_v2_lex_proto_rawDescData
}

var file_v2_lex_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_v2_lex_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v2_lex_proto_goTypes = []any{
	(Delimiter)(0),           // 0: gluon.v2.Delimiter
	(Scoper)(0),              // 1: gluon.v2.Scoper
	(*LexicalDelimiter)(nil), // 2: gluon.v2.LexicalDelimiter
	(*LexicalScoper)(nil),    // 3: gluon.v2.LexicalScoper
	(*SymbolDescriptor)(nil), // 4: gluon.v2.SymbolDescriptor
	(*LexDescriptor)(nil),    // 5: gluon.v2.LexDescriptor
}
var file_v2_lex_proto_depIdxs = []int32{
	0, // 0: gluon.v2.LexicalDelimiter.kind:type_name -> gluon.v2.Delimiter
	1, // 1: gluon.v2.LexicalScoper.kind:type_name -> gluon.v2.Scoper
	2, // 2: gluon.v2.SymbolDescriptor.delimiter:type_name -> gluon.v2.LexicalDelimiter
	3, // 3: gluon.v2.SymbolDescriptor.scoper:type_name -> gluon.v2.LexicalScoper
	4, // 4: gluon.v2.LexDescriptor.symbols:type_name -> gluon.v2.SymbolDescriptor
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_v2_lex_proto_init() }
func file_v2_lex_proto_init() {
	if File_v2_lex_proto != nil {
		return
	}
	file_v2_lex_proto_msgTypes[2].OneofWrappers = []any{
		(*SymbolDescriptor_Delimiter)(nil),
		(*SymbolDescriptor_Scoper)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v2_lex_proto_rawDesc), len(file_v2_lex_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v2_lex_proto_goTypes,
		DependencyIndexes: file_v2_lex_proto_depIdxs,
		EnumInfos:         file_v2_lex_proto_enumTypes,
		MessageInfos:      file_v2_lex_proto_msgTypes,
	}.Build()
	File_v2_lex_proto = out.File
	file_v2_lex_proto_goTypes = nil
	file_v2_lex_proto_depIdxs = nil
}
