// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: v2/metaparser.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Metaparser_ReadBytes_FullMethodName  = "/gluon.v2.Metaparser/ReadBytes"
	Metaparser_ReadString_FullMethodName = "/gluon.v2.Metaparser/ReadString"
	Metaparser_EBNF_FullMethodName       = "/gluon.v2.Metaparser/EBNF"
	Metaparser_CST_FullMethodName        = "/gluon.v2.Metaparser/CST"
)

// MetaparserClient is the client API for Metaparser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Metaparser is the bottom-up parsing pipeline.
//
// Typical flow (file on disk → CST):
//
//	bytes                                      ← io.ReadFile
//	  → ReadBytes   → TextDescriptor           ← raw bytes
//	string                                     ← a name for the document
//	  → ReadString  → DocumentDescriptor
//	DocumentDescriptor                         ← EBNF source
//	  → EBNF        → GrammarDescriptor        ← rules + lex conventions
//	TokenSequence + GrammarDescriptor
//	  → CST         → ASTDescriptor            ← concrete syntax tree
//
// A separate compiler (not part of Metaparser) lowers an ASTDescriptor
// into a FileDescriptorProto or any other target shape.
type MetaparserClient interface {
	// ReadBytes classifies a raw byte buffer into a TextDescriptor,
	// choosing an encoding (ASCII / unicode_val / unicode_string) based
	// on the input.
	ReadBytes(ctx context.Context, in *wrapperspb.BytesValue, opts ...grpc.CallOption) (*TextDescriptor, error)
	// ReadString lifts a single string into a DocumentDescriptor with a
	// single TextDescriptor chunk. Cheap entry point when the source is
	// already in memory as a Go string.
	ReadString(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*DocumentDescriptor, error)
	// EBNF parses a DocumentDescriptor containing EBNF source into a
	// GrammarDescriptor. Internally lexes according to a LexDescriptor
	// configured for the input's EBNF dialect.
	EBNF(ctx context.Context, in *DocumentDescriptor, opts ...grpc.CallOption) (*GrammarDescriptor, error)
	// CST parses an already-lexed TokenSequence against a grammar,
	// producing an ASTDescriptor that carries the full concrete syntax
	// tree (every matched token).
	CST(ctx context.Context, in *CstRequest, opts ...grpc.CallOption) (*ASTDescriptor, error)
}

type metaparserClient struct {
	cc grpc.ClientConnInterface
}

func NewMetaparserClient(cc grpc.ClientConnInterface) MetaparserClient {
	return &metaparserClient{cc}
}

func (c *metaparserClient) ReadBytes(ctx context.Context, in *wrapperspb.BytesValue, opts ...grpc.CallOption) (*TextDescriptor, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TextDescriptor)
	err := c.cc.Invoke(ctx, Metaparser_ReadBytes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaparserClient) ReadString(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*DocumentDescriptor, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentDescriptor)
	err := c.cc.Invoke(ctx, Metaparser_ReadString_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaparserClient) EBNF(ctx context.Context, in *DocumentDescriptor, opts ...grpc.CallOption) (*GrammarDescriptor, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrammarDescriptor)
	err := c.cc.Invoke(ctx, Metaparser_EBNF_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaparserClient) CST(ctx context.Context, in *CstRequest, opts ...grpc.CallOption) (*ASTDescriptor, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ASTDescriptor)
	err := c.cc.Invoke(ctx, Metaparser_CST_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetaparserServer is the server API for Metaparser service.
// All implementations must embed UnimplementedMetaparserServer
// for forward compatibility.
//
// Metaparser is the bottom-up parsing pipeline.
//
// Typical flow (file on disk → CST):
//
//	bytes                                      ← io.ReadFile
//	  → ReadBytes   → TextDescriptor           ← raw bytes
//	string                                     ← a name for the document
//	  → ReadString  → DocumentDescriptor
//	DocumentDescriptor                         ← EBNF source
//	  → EBNF        → GrammarDescriptor        ← rules + lex conventions
//	TokenSequence + GrammarDescriptor
//	  → CST         → ASTDescriptor            ← concrete syntax tree
//
// A separate compiler (not part of Metaparser) lowers an ASTDescriptor
// into a FileDescriptorProto or any other target shape.
type MetaparserServer interface {
	// ReadBytes classifies a raw byte buffer into a TextDescriptor,
	// choosing an encoding (ASCII / unicode_val / unicode_string) based
	// on the input.
	ReadBytes(context.Context, *wrapperspb.BytesValue) (*TextDescriptor, error)
	// ReadString lifts a single string into a DocumentDescriptor with a
	// single TextDescriptor chunk. Cheap entry point when the source is
	// already in memory as a Go string.
	ReadString(context.Context, *wrapperspb.StringValue) (*DocumentDescriptor, error)
	// EBNF parses a DocumentDescriptor containing EBNF source into a
	// GrammarDescriptor. Internally lexes according to a LexDescriptor
	// configured for the input's EBNF dialect.
	EBNF(context.Context, *DocumentDescriptor) (*GrammarDescriptor, error)
	// CST parses an already-lexed TokenSequence against a grammar,
	// producing an ASTDescriptor that carries the full concrete syntax
	// tree (every matched token).
	CST(context.Context, *CstRequest) (*ASTDescriptor, error)
	mustEmbedUnimplementedMetaparserServer()
}

// UnimplementedMetaparserServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetaparserServer struct{}

func (UnimplementedMetaparserServer) ReadBytes(context.Context, *wrapperspb.BytesValue) (*TextDescriptor, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadBytes not implemented")
}
func (UnimplementedMetaparserServer) ReadString(context.Context, *wrapperspb.StringValue) (*DocumentDescriptor, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadString not implemented")
}
func (UnimplementedMetaparserServer) EBNF(context.Context, *DocumentDescriptor) (*GrammarDescriptor, error) {
	return nil, status.Error(codes.Unimplemented, "method EBNF not implemented")
}
func (UnimplementedMetaparserServer) CST(context.Context, *CstRequest) (*ASTDescriptor, error) {
	return nil, status.Error(codes.Unimplemented, "method CST not implemented")
}
func (UnimplementedMetaparserServer) mustEmbedUnimplementedMetaparserServer() {}
func (UnimplementedMetaparserServer) testEmbeddedByValue()                    {}

// UnsafeMetaparserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetaparserServer will
// result in compilation errors.
type UnsafeMetaparserServer interface {
	mustEmbedUnimplementedMetaparserServer()
}

func RegisterMetaparserServer(s grpc.ServiceRegistrar, srv MetaparserServer) {
	// If the following call panics, it indicates UnimplementedMetaparserServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Metaparser_ServiceDesc, srv)
}

func _Metaparser_ReadBytes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.BytesValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaparserServer).ReadBytes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metaparser_ReadBytes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaparserServer).ReadBytes(ctx, req.(*wrapperspb.BytesValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metaparser_ReadString_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaparserServer).ReadString(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metaparser_ReadString_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaparserServer).ReadString(ctx, req.(*wrapperspb.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metaparser_EBNF_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocumentDescriptor)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaparserServer).EBNF(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metaparser_EBNF_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaparserServer).EBNF(ctx, req.(*DocumentDescriptor))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metaparser_CST_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CstRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaparserServer).CST(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metaparser_CST_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaparserServer).CST(ctx, req.(*CstRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Metaparser_ServiceDesc is the grpc.ServiceDesc for Metaparser service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Metaparser_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gluon.v2.Metaparser",
	HandlerType: (*MetaparserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadBytes",
			Handler:    _Metaparser_ReadBytes_Handler,
		},
		{
			MethodName: "ReadString",
			Handler:    _Metaparser_ReadString_Handler,
		},
		{
			MethodName: "EBNF",
			Handler:    _Metaparser_EBNF_Handler,
		},
		{
			MethodName: "CST",
			Handler:    _Metaparser_CST_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v2/metaparser.proto",
}
