// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: v2/source_location.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SourceLocation is a byte-range pointer into a source document.
// It lets downstream messages refer to a region of source text without
// copying the bytes themselves — useful for CST nodes, diagnostics, and
// chunked TextDescriptors that share a backing buffer.
//
// The field is deliberately a URI, not inline text, so consumers are
// forced to resolve it against a document they already hold. That
// prevents SourceLocation from drifting into a second home for text.
type SourceLocation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// URI of the document this location refers to (matches
	// DocumentDescriptor.uri). Empty means "the enclosing/ambient document".
	Uri string `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	// Byte offset from the start of the referenced document.
	Offset int32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// Byte length of the region. Zero length = a point (e.g. a cursor).
	Length int32 `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	// Optional 1-based line/column for human-readable diagnostics.
	// Producers may leave these as 0 when not computed.
	Line          int32 `protobuf:"varint,4,opt,name=line,proto3" json:"line,omitempty"`
	Column        int32 `protobuf:"varint,5,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceLocation) Reset() {
	*x = SourceLocation{}
	mi := &file_v2_source_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceLocation) ProtoMessage() {}

func (x *SourceLocation) ProtoReflect() protoreflect.Message {
	mi := &file_v2_source_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceLocation.ProtoReflect.Descriptor instead.
func (*SourceLocation) Descriptor() ([]byte, []int) {
	return file_v2_source_location_proto_rawDescGZIP(), []int{0}
}

func (x *SourceLocation) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *SourceLocation) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SourceLocation) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *SourceLocation) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *SourceLocation) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

var File_v2_source_location_proto protoreflect.FileDescriptor

const file_v2_source_location_proto_rawDesc = "" +
	"\n" +
	"\x18v2/source_location.proto\x12\bgluon.v2\"~\n" +
	"\x0eSourceLocation\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x05R\x06length\x12\x12\n" +
	"\x04line\x18\x04 \x01(\x05R\x04line\x12\x16\n" +
	"\x06column\x18\x05 \x01(\x05R\x06columnB$Z\"github.com/accretional/gluon/v2/pbb\x06proto3"

var (
	file_v2_source_location_proto_rawDescOnce sync.Once
	file_v2_source_location_proto_rawDescData []byte
)

func file_v2_source_location_proto_rawDescGZIP() []byte {
	file_v2_source_location_proto_rawDescOnce.Do(func() {
		file_v2_source_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v2_source_location_proto_rawDesc), len(file_v2_source_location_proto_rawDesc)))
	})
	return file_v2_source_location_proto_rawDescData
}

var file_v2_source_location_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v2_source_location_proto_goTypes = []any{
	(*SourceLocation)(nil), // 0: gluon.v2.SourceLocation
}
var file_v2_source_location_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v2_source_location_proto_init() }
func file_v2_source_location_proto_init() {
	if File_v2_source_location_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v2_source_location_proto_rawDesc), len(file_v2_source_location_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v2_source_location_proto_goTypes,
		DependencyIndexes: file_v2_source_location_proto_depIdxs,
		MessageInfos:      file_v2_source_location_proto_msgTypes,
	}.Build()
	File_v2_source_location_proto = out.File
	file_v2_source_location_proto_goTypes = nil
	file_v2_source_location_proto_depIdxs = nil
}
