// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: v2/text.proto

package pb

import (
	pb "github.com/accretional/gluon/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TextDescriptor holds a chunk of source text in one of several encodings.
//
// The encodings exist so that the common case — ASCII-only source — costs
// roughly one byte per character, while non-ASCII content can still be
// represented without lossy conversion and large buffers can be shared by
// reference.
//
// The oneof is chunk-scoped, not document-scoped: a DocumentDescriptor
// typically carries a `repeated TextDescriptor text`, so different regions
// of the same document can use different encodings (a run of ASCII, then a
// unicode burst, then back to ASCII).
type TextDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional name — useful when the text is addressed by reference
	// (e.g. from SourceLocation.text).
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Content:
	//
	//	*TextDescriptor_Ascii
	//	*TextDescriptor_UnicodeVal
	//	*TextDescriptor_UnicodeString
	//	*TextDescriptor_SourceLocation
	Content       isTextDescriptor_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextDescriptor) Reset() {
	*x = TextDescriptor{}
	mi := &file_v2_text_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextDescriptor) ProtoMessage() {}

func (x *TextDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_v2_text_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextDescriptor.ProtoReflect.Descriptor instead.
func (*TextDescriptor) Descriptor() ([]byte, []int) {
	return file_v2_text_proto_rawDescGZIP(), []int{0}
}

func (x *TextDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TextDescriptor) GetContent() isTextDescriptor_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *TextDescriptor) GetAscii() *AsciiChunk {
	if x != nil {
		if x, ok := x.Content.(*TextDescriptor_Ascii); ok {
			return x.Ascii
		}
	}
	return nil
}

func (x *TextDescriptor) GetUnicodeVal() *UnicodeChunk {
	if x != nil {
		if x, ok := x.Content.(*TextDescriptor_UnicodeVal); ok {
			return x.UnicodeVal
		}
	}
	return nil
}

func (x *TextDescriptor) GetUnicodeString() string {
	if x != nil {
		if x, ok := x.Content.(*TextDescriptor_UnicodeString); ok {
			return x.UnicodeString
		}
	}
	return ""
}

func (x *TextDescriptor) GetSourceLocation() *SourceLocation {
	if x != nil {
		if x, ok := x.Content.(*TextDescriptor_SourceLocation); ok {
			return x.SourceLocation
		}
	}
	return nil
}

type isTextDescriptor_Content interface {
	isTextDescriptor_Content()
}

type TextDescriptor_Ascii struct {
	// ASCII-only run. Preferred when every character fits in 7 bits —
	// each rune is one int value with a readable ASCII enum name.
	Ascii *AsciiChunk `protobuf:"bytes,2,opt,name=ascii,proto3,oneof"`
}

type TextDescriptor_UnicodeVal struct {
	// Arbitrary Unicode code points. Use when the text contains non-ASCII
	// runes but you still want per-rune addressability.
	UnicodeVal *UnicodeChunk `protobuf:"bytes,3,opt,name=unicode_val,json=unicodeVal,proto3,oneof"`
}

type TextDescriptor_UnicodeString struct {
	// Raw UTF-8 string. Use for prose or when per-rune addressability
	// doesn't matter — cheapest to construct from an existing string.
	UnicodeString string `protobuf:"bytes,4,opt,name=unicode_string,json=unicodeString,proto3,oneof"`
}

type TextDescriptor_SourceLocation struct {
	// By-reference pointer into a source document (resolved via
	// SourceLocation.uri against a DocumentDescriptor). Use when
	// multiple descriptors need to refer to the same backing buffer
	// without copying.
	SourceLocation *SourceLocation `protobuf:"bytes,5,opt,name=source_location,json=sourceLocation,proto3,oneof"`
}

func (*TextDescriptor_Ascii) isTextDescriptor_Content() {}

func (*TextDescriptor_UnicodeVal) isTextDescriptor_Content() {}

func (*TextDescriptor_UnicodeString) isTextDescriptor_Content() {}

func (*TextDescriptor_SourceLocation) isTextDescriptor_Content() {}

// AsciiChunk is a run of ASCII-only characters. Wrapped in a message
// because proto3 doesn't permit `repeated` directly inside a oneof.
type AsciiChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chars         []pb.ASCII             `protobuf:"varint,1,rep,packed,name=chars,proto3,enum=unicode.ASCII" json:"chars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsciiChunk) Reset() {
	*x = AsciiChunk{}
	mi := &file_v2_text_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsciiChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsciiChunk) ProtoMessage() {}

func (x *AsciiChunk) ProtoReflect() protoreflect.Message {
	mi := &file_v2_text_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsciiChunk.ProtoReflect.Descriptor instead.
func (*AsciiChunk) Descriptor() ([]byte, []int) {
	return file_v2_text_proto_rawDescGZIP(), []int{1}
}

func (x *AsciiChunk) GetChars() []pb.ASCII {
	if x != nil {
		return x.Chars
	}
	return nil
}

// UnicodeChunk is a run of arbitrary Unicode code points. int32 is used
// (rather than uint32) to stay consistent with Go's `rune` type.
type UnicodeChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chars         []int32                `protobuf:"varint,1,rep,packed,name=chars,proto3" json:"chars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnicodeChunk) Reset() {
	*x = UnicodeChunk{}
	mi := &file_v2_text_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnicodeChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnicodeChunk) ProtoMessage() {}

func (x *UnicodeChunk) ProtoReflect() protoreflect.Message {
	mi := &file_v2_text_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnicodeChunk.ProtoReflect.Descriptor instead.
func (*UnicodeChunk) Descriptor() ([]byte, []int) {
	return file_v2_text_proto_rawDescGZIP(), []int{2}
}

func (x *UnicodeChunk) GetChars() []int32 {
	if x != nil {
		return x.Chars
	}
	return nil
}

var File_v2_text_proto protoreflect.FileDescriptor

const file_v2_text_proto_rawDesc = "" +
	"\n" +
	"\rv2/text.proto\x12\bgluon.v2\x1a\x13unicode/ascii.proto\x1a\x18v2/source_location.proto\"\x86\x02\n" +
	"\x0eTextDescriptor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12,\n" +
	"\x05ascii\x18\x02 \x01(\v2\x14.gluon.v2.AsciiChunkH\x00R\x05ascii\x129\n" +
	"\vunicode_val\x18\x03 \x01(\v2\x16.gluon.v2.UnicodeChunkH\x00R\n" +
	"unicodeVal\x12'\n" +
	"\x0eunicode_string\x18\x04 \x01(\tH\x00R\runicodeString\x12C\n" +
	"\x0fsource_location\x18\x05 \x01(\v2\x18.gluon.v2.SourceLocationH\x00R\x0esourceLocationB\t\n" +
	"\acontent\"2\n" +
	"\n" +
	"AsciiChunk\x12$\n" +
	"\x05chars\x18\x01 \x03(\x0e2\x0e.unicode.ASCIIR\x05chars\"$\n" +
	"\fUnicodeChunk\x12\x14\n" +
	"\x05chars\x18\x01 \x03(\x05R\x05charsB$Z\"github.com/accretional/gluon/v2/pbb\x06proto3"

var (
	file_v2_text_proto_rawDescOnce sync.Once
	file_v2_text_proto_rawDescData []byte
)

func file_v2_text_proto_rawDescGZIP() []byte {
	file_v2_text_proto_rawDescOnce.Do(func() {
		file_v2_text_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v2_text_proto_rawDesc), len(file_v2_text_proto_rawDesc)))
	})
	return file_v2_text_proto_rawDescData
}

var file_v2_text_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_v2_text_proto_goTypes = []any{
	(*TextDescriptor)(nil), // 0: gluon.v2.TextDescriptor
	(*AsciiChunk)(nil),     // 1: gluon.v2.AsciiChunk
	(*UnicodeChunk)(nil),   // 2: gluon.v2.UnicodeChunk
	(*SourceLocation)(nil), // 3: gluon.v2.SourceLocation
	(pb.ASCII)(0),          // 4: unicode.ASCII
}
var file_v2_text_proto_depIdxs = []int32{
	1, // 0: gluon.v2.TextDescriptor.ascii:type_name -> gluon.v2.AsciiChunk
	2, // 1: gluon.v2.TextDescriptor.unicode_val:type_name -> gluon.v2.UnicodeChunk
	3, // 2: gluon.v2.TextDescriptor.source_location:type_name -> gluon.v2.SourceLocation
	4, // 3: gluon.v2.AsciiChunk.chars:type_name -> unicode.ASCII
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_v2_text_proto_init() }
func file_v2_text_proto_init() {
	if File_v2_text_proto != nil {
		return
	}
	file_v2_source_location_proto_init()
	file_v2_text_proto_msgTypes[0].OneofWrappers = []any{
		(*TextDescriptor_Ascii)(nil),
		(*TextDescriptor_UnicodeVal)(nil),
		(*TextDescriptor_UnicodeString)(nil),
		(*TextDescriptor_SourceLocation)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v2_text_proto_rawDesc), len(file_v2_text_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v2_text_proto_goTypes,
		DependencyIndexes: file_v2_text_proto_depIdxs,
		MessageInfos:      file_v2_text_proto_msgTypes,
	}.Build()
	File_v2_text_proto = out.File
	file_v2_text_proto_goTypes = nil
	file_v2_text_proto_depIdxs = nil
}
