// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: v2/tokens.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TokenSequence is a linear stream of classified tokens — the output of
// lexing a DocumentDescriptor against a LexDescriptor, and the input to
// CST parsing against a GrammarDescriptor.
//
// Tokens carry their role (delimiter / scoper-boundary / literal) rather
// than raw characters: the parser never needs to re-consult the lex
// tables, and the serialized form stays compact.
type TokenSequence struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional name — typically the source document's name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// URI of the source document the tokens were lexed from. Each token's
	// `offset` points into this document.
	Uri           string   `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	Tokens        []*Token `protobuf:"bytes,3,rep,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenSequence) Reset() {
	*x = TokenSequence{}
	mi := &file_v2_tokens_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenSequence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenSequence) ProtoMessage() {}

func (x *TokenSequence) ProtoReflect() protoreflect.Message {
	mi := &file_v2_tokens_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenSequence.ProtoReflect.Descriptor instead.
func (*TokenSequence) Descriptor() ([]byte, []int) {
	return file_v2_tokens_proto_rawDescGZIP(), []int{0}
}

func (x *TokenSequence) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TokenSequence) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *TokenSequence) GetTokens() []*Token {
	if x != nil {
		return x.Tokens
	}
	return nil
}

// Token is one classified element of a TokenSequence.
//
// Every token carries an `offset` into TokenSequence.uri. The optional
// `kind` oneof says what role (if any) the characters at that offset
// play.
//
// ===========================================================================
// LOAD-BEARING CONVENTION — READ BEFORE TOUCHING THIS MESSAGE
// ===========================================================================
//
// A Token whose `kind` oneof is unset is a LITERAL TEXT run beginning at
// `offset`. This is the canonical representation of a text/identifier
// token; there is no separate "text" variant.
//
// Because proto3 cannot distinguish "oneof unset" from "oneof set to the
// zero value" at the wire level, the following forms are ALL equivalent
// and all mean "literal text":
//
//  1. Token { offset: N }                          ← canonical
//  2. Token { offset: N, delimiter: DELIMITER_UNSPECIFIED }
//  3. Token { offset: N, scoper: { lhs: SCOPER_UNSPECIFIED } }
//  4. Token { offset: N, scoper: { rhs: SCOPER_UNSPECIFIED } }
//  5. Token { offset: N, scoper: {} }              ← empty ScoperToken
//
// Producers SHOULD emit form (1). Consumers MUST accept all five.
//
// Implications:
//   - Never assign DELIMITER_UNSPECIFIED or SCOPER_UNSPECIFIED as a real
//     role — doing so silently reclassifies the token as literal text.
//   - Never reorder Delimiter or Scoper enum values; keeping the zero
//     value reserved for "unspecified" is what makes the convention work.
//   - Literal-run length is implied by the next token's offset, so the
//     lexer MUST emit a token (typically Delimiter.WHITESPACE) for every
//     skipped run — otherwise literal boundaries are lost.
//
// ===========================================================================
type Token struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If unset (or populated with the UNSPECIFIED zero value of either
	// inner enum), this Token is a literal text run starting at `offset`.
	// See the banner above.
	//
	// Types that are valid to be assigned to Kind:
	//
	//	*Token_Delimiter
	//	*Token_Scoper
	Kind isToken_Kind `protobuf_oneof:"kind"`
	// Byte offset into TokenSequence.uri where this token begins.
	Offset        int32 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_v2_tokens_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_v2_tokens_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_v2_tokens_proto_rawDescGZIP(), []int{1}
}

func (x *Token) GetKind() isToken_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Token) GetDelimiter() Delimiter {
	if x != nil {
		if x, ok := x.Kind.(*Token_Delimiter); ok {
			return x.Delimiter
		}
	}
	return Delimiter_DELIMITER_UNSPECIFIED
}

func (x *Token) GetScoper() *ScoperToken {
	if x != nil {
		if x, ok := x.Kind.(*Token_Scoper); ok {
			return x.Scoper
		}
	}
	return nil
}

func (x *Token) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type isToken_Kind interface {
	isToken_Kind()
}

type Token_Delimiter struct {
	Delimiter Delimiter `protobuf:"varint,1,opt,name=delimiter,proto3,enum=gluon.v2.Delimiter,oneof"`
}

type Token_Scoper struct {
	Scoper *ScoperToken `protobuf:"bytes,2,opt,name=scoper,proto3,oneof"`
}

func (*Token_Delimiter) isToken_Kind() {}

func (*Token_Scoper) isToken_Kind() {}

// ScoperToken tags a paired scoper as either its opening or closing
// side. Using a oneof (lhs/rhs) rather than (kind, side) pair saves a
// field on the wire: each ScoperToken serializes as one tag-value
// entry rather than two.
type ScoperToken struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*ScoperToken_Lhs
	//	*ScoperToken_Rhs
	Kind          isScoperToken_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoperToken) Reset() {
	*x = ScoperToken{}
	mi := &file_v2_tokens_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoperToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoperToken) ProtoMessage() {}

func (x *ScoperToken) ProtoReflect() protoreflect.Message {
	mi := &file_v2_tokens_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoperToken.ProtoReflect.Descriptor instead.
func (*ScoperToken) Descriptor() ([]byte, []int) {
	return file_v2_tokens_proto_rawDescGZIP(), []int{2}
}

func (x *ScoperToken) GetKind() isScoperToken_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *ScoperToken) GetLhs() Scoper {
	if x != nil {
		if x, ok := x.Kind.(*ScoperToken_Lhs); ok {
			return x.Lhs
		}
	}
	return Scoper_SCOPER_UNSPECIFIED
}

func (x *ScoperToken) GetRhs() Scoper {
	if x != nil {
		if x, ok := x.Kind.(*ScoperToken_Rhs); ok {
			return x.Rhs
		}
	}
	return Scoper_SCOPER_UNSPECIFIED
}

type isScoperToken_Kind interface {
	isScoperToken_Kind()
}

type ScoperToken_Lhs struct {
	// Opening side of a scoper pair (e.g. "[" for OPTIONAL, "(*" for
	// COMMENT).
	Lhs Scoper `protobuf:"varint,1,opt,name=lhs,proto3,enum=gluon.v2.Scoper,oneof"`
}

type ScoperToken_Rhs struct {
	// Closing side of a scoper pair (e.g. "]" for OPTIONAL, "*)" for
	// COMMENT).
	Rhs Scoper `protobuf:"varint,2,opt,name=rhs,proto3,enum=gluon.v2.Scoper,oneof"`
}

func (*ScoperToken_Lhs) isScoperToken_Kind() {}

func (*ScoperToken_Rhs) isScoperToken_Kind() {}

var File_v2_tokens_proto protoreflect.FileDescriptor

const file_v2_tokens_proto_rawDesc = "" +
	"\n" +
	"\x0fv2/tokens.proto\x12\bgluon.v2\x1a\fv2/lex.proto\"^\n" +
	"\rTokenSequence\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\x12'\n" +
	"\x06tokens\x18\x03 \x03(\v2\x0f.gluon.v2.TokenR\x06tokens\"\x8d\x01\n" +
	"\x05Token\x123\n" +
	"\tdelimiter\x18\x01 \x01(\x0e2\x13.gluon.v2.DelimiterH\x00R\tdelimiter\x12/\n" +
	"\x06scoper\x18\x02 \x01(\v2\x15.gluon.v2.ScoperTokenH\x00R\x06scoper\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offsetB\x06\n" +
	"\x04kind\"a\n" +
	"\vScoperToken\x12$\n" +
	"\x03lhs\x18\x01 \x01(\x0e2\x10.gluon.v2.ScoperH\x00R\x03lhs\x12$\n" +
	"\x03rhs\x18\x02 \x01(\x0e2\x10.gluon.v2.ScoperH\x00R\x03rhsB\x06\n" +
	"\x04kindB$Z\"github.com/accretional/gluon/v2/pbb\x06proto3"

var (
	file_v2_tokens_proto_rawDescOnce sync.Once
	file_v2_tokens_proto_rawDescData []byte
)

func file_v2_tokens_proto_rawDescGZIP() []byte {
	file_v2_tokens_proto_rawDescOnce.Do(func() {
		file_v2_tokens_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v2_tokens_proto_rawDesc), len(file_v2_tokens_proto_rawDesc)))
	})
	return file_v2_tokens_proto_rawDescData
}

var file_v2_tokens_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_v2_tokens_proto_goTypes = []any{
	(*TokenSequence)(nil), // 0: gluon.v2.TokenSequence
	(*Token)(nil),         // 1: gluon.v2.Token
	(*ScoperToken)(nil),   // 2: gluon.v2.ScoperToken
	(Delimiter)(0),        // 3: gluon.v2.Delimiter
	(Scoper)(0),           // 4: gluon.v2.Scoper
}
var file_v2_tokens_proto_depIdxs = []int32{
	1, // 0: gluon.v2.TokenSequence.tokens:type_name -> gluon.v2.Token
	3, // 1: gluon.v2.Token.delimiter:type_name -> gluon.v2.Delimiter
	2, // 2: gluon.v2.Token.scoper:type_name -> gluon.v2.ScoperToken
	4, // 3: gluon.v2.ScoperToken.lhs:type_name -> gluon.v2.Scoper
	4, // 4: gluon.v2.ScoperToken.rhs:type_name -> gluon.v2.Scoper
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_v2_tokens_proto_init() }
func file_v2_tokens_proto_init() {
	if File_v2_tokens_proto != nil {
		return
	}
	file_v2_lex_proto_init()
	file_v2_tokens_proto_msgTypes[1].OneofWrappers = []any{
		(*Token_Delimiter)(nil),
		(*Token_Scoper)(nil),
	}
	file_v2_tokens_proto_msgTypes[2].OneofWrappers = []any{
		(*ScoperToken_Lhs)(nil),
		(*ScoperToken_Rhs)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v2_tokens_proto_rawDesc), len(file_v2_tokens_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v2_tokens_proto_goTypes,
		DependencyIndexes: file_v2_tokens_proto_depIdxs,
		MessageInfos:      file_v2_tokens_proto_msgTypes,
	}.Build()
	File_v2_tokens_proto = out.File
	file_v2_tokens_proto_goTypes = nil
	file_v2_tokens_proto_depIdxs = nil
}
