// Package lexkit provides a configurable EBNF lexer and parser that
// reads grammar definitions according to a LexDescriptor configuration.
// It supports Go's EBNF variant, Protocol Buffers' EBNF, and standard
// ISO 14977 EBNF by swapping the LexDescriptor.
package lexkit

import (
	"fmt"
	"strings"
	"unicode"
	"unicode/utf8"

	pb "github.com/accretional/gluon/pb"
)

// Predefined LexDescriptors for supported EBNF variants.

// GoLex returns the LexDescriptor for Go's EBNF variant.
// Definition: '=', termination: '.', no explicit concatenation,
// terminals in '"' or '`', comments in /* */.
func GoLex() *pb.LexDescriptor {
	return &pb.LexDescriptor{
		Whitespace:    []int32{' ', '\t', '\n', '\r'},
		Definition:    '=',
		Concatenation: 0, // implicit
		Termination:   '.',
		Alternation:   '|',
		OptionalLhs:   '[',
		OptionalRhs:   ']',
		RepetitionLhs: '{',
		RepetitionRhs: '}',
		GroupingLhs:   '(',
		GroupingRhs:   ')',
		Terminal:      '"',
		CommentLhs:    '/',
		CommentRhs:    '/',
	}
}

// ProtoLex returns the LexDescriptor for Protocol Buffers' EBNF variant.
// Same as Go except termination is ';' instead of '.'.
func ProtoLex() *pb.LexDescriptor {
	return &pb.LexDescriptor{
		Whitespace:    []int32{' ', '\t', '\n', '\r'},
		Definition:    '=',
		Concatenation: 0, // implicit
		Termination:   ';',
		Alternation:   '|',
		OptionalLhs:   '[',
		OptionalRhs:   ']',
		RepetitionLhs: '{',
		RepetitionRhs: '}',
		GroupingLhs:   '(',
		GroupingRhs:   ')',
		Terminal:      '"',
		CommentLhs:    '/',
		CommentRhs:    '/',
	}
}

// StandardLex returns the LexDescriptor for ISO 14977 standard EBNF.
// Uses ',' for concatenation, ';' for termination, (* *) for comments.
func StandardLex() *pb.LexDescriptor {
	return &pb.LexDescriptor{
		Whitespace:    []int32{' ', '\t', '\n', '\r'},
		Definition:    '=',
		Concatenation: ',',
		Termination:   ';',
		Alternation:   '|',
		OptionalLhs:   '[',
		OptionalRhs:   ']',
		RepetitionLhs: '{',
		RepetitionRhs: '}',
		GroupingLhs:   '(',
		GroupingRhs:   ')',
		Terminal:      '"',
		CommentLhs:    '(',
		CommentRhs:    ')',
	}
}

// Production represents a single parsed EBNF production rule.
type Production struct {
	Name string // production name (left-hand side)
	Raw  string // raw EBNF text of the expression (right-hand side)
}

// ParseResult holds the output of parsing an EBNF grammar file.
type ParseResult struct {
	Lex         *pb.LexDescriptor
	Productions []Production
}

// Parse reads EBNF source text and extracts production rules according
// to the given LexDescriptor configuration.
func Parse(src string, lex *pb.LexDescriptor) (*ParseResult, error) {
	p := &parser{
		src: src,
		lex: lex,
		pos: 0,
	}
	prods, err := p.parse()
	if err != nil {
		return nil, err
	}
	return &ParseResult{
		Lex:         lex,
		Productions: prods,
	}, nil
}

// ToGrammarDescriptor converts a ParseResult into a protobuf GrammarDescriptor.
// Since ProductionDescriptor is currently empty (TODO), the productions
// are counted but their content is not serialized into proto fields yet.
func (pr *ParseResult) ToGrammarDescriptor() *pb.GrammarDescriptor {
	gd := &pb.GrammarDescriptor{
		Lex:         pr.Lex,
		Productions: make([]*pb.ProductionDescriptor, len(pr.Productions)),
	}
	for i := range pr.Productions {
		gd.Productions[i] = &pb.ProductionDescriptor{}
	}
	return gd
}

// ToTextproto serializes a ParseResult as a human-readable textproto
// representation of a GrammarDescriptor. Since ProductionDescriptor has
// no fields yet, productions are represented as comments.
func (pr *ParseResult) ToTextproto() string {
	var b strings.Builder

	b.WriteString("# GrammarDescriptor\n")
	b.WriteString("# Generated by lexkit\n\n")

	// Lex descriptor
	b.WriteString("lex {\n")
	for _, ws := range pr.Lex.Whitespace {
		fmt.Fprintf(&b, "  whitespace: %d  # %s\n", ws, charName(ws))
	}
	if pr.Lex.Definition != 0 {
		fmt.Fprintf(&b, "  definition: %d  # '%c'\n", pr.Lex.Definition, pr.Lex.Definition)
	}
	if pr.Lex.Concatenation != 0 {
		fmt.Fprintf(&b, "  concatenation: %d  # '%c'\n", pr.Lex.Concatenation, pr.Lex.Concatenation)
	}
	if pr.Lex.Termination != 0 {
		fmt.Fprintf(&b, "  termination: %d  # '%c'\n", pr.Lex.Termination, pr.Lex.Termination)
	}
	if pr.Lex.Alternation != 0 {
		fmt.Fprintf(&b, "  alternation: %d  # '%c'\n", pr.Lex.Alternation, pr.Lex.Alternation)
	}
	if pr.Lex.OptionalLhs != 0 {
		fmt.Fprintf(&b, "  optional_lhs: %d  # '%c'\n", pr.Lex.OptionalLhs, pr.Lex.OptionalLhs)
	}
	if pr.Lex.OptionalRhs != 0 {
		fmt.Fprintf(&b, "  optional_rhs: %d  # '%c'\n", pr.Lex.OptionalRhs, pr.Lex.OptionalRhs)
	}
	if pr.Lex.RepetitionLhs != 0 {
		fmt.Fprintf(&b, "  repetition_lhs: %d  # '%c'\n", pr.Lex.RepetitionLhs, pr.Lex.RepetitionLhs)
	}
	if pr.Lex.RepetitionRhs != 0 {
		fmt.Fprintf(&b, "  repetition_rhs: %d  # '%c'\n", pr.Lex.RepetitionRhs, pr.Lex.RepetitionRhs)
	}
	if pr.Lex.GroupingLhs != 0 {
		fmt.Fprintf(&b, "  grouping_lhs: %d  # '%c'\n", pr.Lex.GroupingLhs, pr.Lex.GroupingLhs)
	}
	if pr.Lex.GroupingRhs != 0 {
		fmt.Fprintf(&b, "  grouping_rhs: %d  # '%c'\n", pr.Lex.GroupingRhs, pr.Lex.GroupingRhs)
	}
	if pr.Lex.Terminal != 0 {
		fmt.Fprintf(&b, "  terminal: %d  # '%c'\n", pr.Lex.Terminal, pr.Lex.Terminal)
	}
	if pr.Lex.CommentLhs != 0 {
		fmt.Fprintf(&b, "  comment_lhs: %d  # '%c'\n", pr.Lex.CommentLhs, pr.Lex.CommentLhs)
	}
	if pr.Lex.CommentRhs != 0 {
		fmt.Fprintf(&b, "  comment_rhs: %d  # '%c'\n", pr.Lex.CommentRhs, pr.Lex.CommentRhs)
	}
	b.WriteString("}\n\n")

	// Productions as comments + empty proto messages
	b.WriteString(fmt.Sprintf("# %d productions parsed\n", len(pr.Productions)))
	b.WriteString("# ProductionDescriptor fields are TODO — listing as comments:\n")
	for i, prod := range pr.Productions {
		fmt.Fprintf(&b, "#   [%d] %s = %s\n", i+1, prod.Name, truncate(prod.Raw, 80))
		b.WriteString("productions {}\n")
	}

	return b.String()
}

func charName(c int32) string {
	switch c {
	case ' ':
		return "space"
	case '\t':
		return "tab"
	case '\n':
		return "newline"
	case '\r':
		return "carriage return"
	default:
		return fmt.Sprintf("'%c'", c)
	}
}

func truncate(s string, n int) string {
	s = strings.Join(strings.Fields(s), " ") // collapse whitespace
	if len(s) <= n {
		return s
	}
	return s[:n-3] + "..."
}

// parser implements a simple EBNF production-rule extractor.
type parser struct {
	src string
	lex *pb.LexDescriptor
	pos int
}

func (p *parser) parse() ([]Production, error) {
	var prods []Production
	for {
		p.skipWhitespaceAndComments()
		if p.pos >= len(p.src) {
			break
		}

		// Look ahead: a new production starts only when we see
		// `identifier <whitespace> = `. If the current position has
		// an identifier followed by something other than '=', it's
		// not a production start (it's a continuation or stray text).
		saved := p.pos
		name, err := p.parseName()
		if err != nil {
			return nil, err
		}
		if name == "" {
			// Not an identifier — skip character
			p.pos++
			continue
		}

		p.skipWhitespaceAndComments()

		// Check for definition operator
		if p.pos >= len(p.src) {
			// EOF after a name with no '=' — not a production
			break
		}
		r, sz := utf8.DecodeRuneInString(p.src[p.pos:])
		if r != rune(p.lex.Definition) {
			// Not a production start — restore position and skip
			// past this identifier (it was part of something else).
			p.pos = saved + len(name)
			continue
		}
		p.pos += sz

		// Read until termination character (not inside quotes/brackets)
		raw, err := p.parseExpression()
		if err != nil {
			return nil, fmt.Errorf("parsing expression for %q: %w", name, err)
		}

		prods = append(prods, Production{
			Name: name,
			Raw:  strings.TrimSpace(raw),
		})
	}
	return prods, nil
}

func (p *parser) parseName() (string, error) {
	p.skipWhitespaceAndComments()
	if p.pos >= len(p.src) {
		return "", nil
	}

	r, _ := utf8.DecodeRuneInString(p.src[p.pos:])
	if !unicode.IsLetter(r) && r != '_' {
		return "", nil
	}

	start := p.pos
	for p.pos < len(p.src) {
		r, sz := utf8.DecodeRuneInString(p.src[p.pos:])
		if unicode.IsLetter(r) || unicode.IsDigit(r) || r == '_' {
			p.pos += sz
		} else {
			break
		}
	}
	return p.src[start:p.pos], nil
}

func (p *parser) parseExpression() (string, error) {
	start := p.pos
	term := rune(p.lex.Termination)
	depth := 0 // track bracket nesting

	for p.pos < len(p.src) {
		r, sz := utf8.DecodeRuneInString(p.src[p.pos:])

		// Handle quoted strings — skip to matching quote
		if r == '"' || r == '\'' || r == '`' {
			p.pos += sz
			p.skipQuoted(r)
			continue
		}

		// Handle comments
		if p.isCommentStart() {
			p.skipComment()
			continue
		}

		// Track bracket depth
		if r == rune(p.lex.GroupingLhs) || r == rune(p.lex.OptionalLhs) || r == rune(p.lex.RepetitionLhs) {
			depth++
		}
		if r == rune(p.lex.GroupingRhs) || r == rune(p.lex.OptionalRhs) || r == rune(p.lex.RepetitionRhs) {
			depth--
		}

		// Termination character at depth 0 ends the production
		if r == term && depth <= 0 {
			raw := p.src[start:p.pos]
			p.pos += sz // consume terminator
			return raw, nil
		}

		p.pos += sz
	}

	// If no termination found, return what we have (some grammars may
	// have the last production without a terminator)
	return p.src[start:p.pos], nil
}

func (p *parser) skipQuoted(quote rune) {
	// EBNF terminal strings are always literal — no escape sequences.
	// The content between quotes represents exact characters in the
	// described language. A backslash inside "\" is a literal backslash,
	// not an escape for the closing quote.
	for p.pos < len(p.src) {
		r, sz := utf8.DecodeRuneInString(p.src[p.pos:])
		p.pos += sz
		if r == quote {
			return
		}
	}
}

func (p *parser) skipWhitespaceAndComments() {
	for p.pos < len(p.src) {
		r, sz := utf8.DecodeRuneInString(p.src[p.pos:])

		// Check whitespace
		isWS := false
		for _, ws := range p.lex.Whitespace {
			if r == rune(ws) {
				isWS = true
				break
			}
		}
		if isWS {
			p.pos += sz
			continue
		}

		// Check for comment start
		if p.isCommentStart() {
			p.skipComment()
			continue
		}

		break
	}
}

func (p *parser) isCommentStart() bool {
	if p.pos >= len(p.src) {
		return false
	}
	clhs := rune(p.lex.CommentLhs)
	if clhs == 0 {
		return false
	}

	r, _ := utf8.DecodeRuneInString(p.src[p.pos:])
	if r != clhs {
		return false
	}

	// Check for // or /* style (when comment_lhs == '/')
	if clhs == '/' && p.pos+1 < len(p.src) {
		next := p.src[p.pos+1]
		return next == '/' || next == '*'
	}

	// Check for (* style (when comment_lhs == '(')
	if clhs == '(' && p.pos+1 < len(p.src) {
		return p.src[p.pos+1] == '*'
	}

	return false
}

func (p *parser) skipComment() {
	clhs := rune(p.lex.CommentLhs)

	if clhs == '/' && p.pos+1 < len(p.src) {
		if p.src[p.pos+1] == '/' {
			// Line comment — skip to end of line
			p.pos += 2
			for p.pos < len(p.src) && p.src[p.pos] != '\n' {
				p.pos++
			}
			return
		}
		if p.src[p.pos+1] == '*' {
			// Block comment — skip to */
			p.pos += 2
			for p.pos+1 < len(p.src) {
				if p.src[p.pos] == '*' && p.src[p.pos+1] == '/' {
					p.pos += 2
					return
				}
				p.pos++
			}
			p.pos = len(p.src)
			return
		}
	}

	if clhs == '(' && p.pos+1 < len(p.src) && p.src[p.pos+1] == '*' {
		// (* ... *) comment
		p.pos += 2
		for p.pos+1 < len(p.src) {
			if p.src[p.pos] == '*' && p.src[p.pos+1] == ')' {
				p.pos += 2
				return
			}
			p.pos++
		}
		p.pos = len(p.src)
		return
	}

	// Fallback: skip one character
	p.pos++
}
