//go:build linux

// To regenerate trace_bpfel.go after editing bpf/trace.c, run on Linux:
//
//	go generate ./tracer/
//
//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -target amd64 trace ./bpf/trace.c -- -I/usr/include/bpf

package tracer

import (
	"encoding/binary"
	"fmt"
	"log"
	"os/exec"

	"github.com/accretional/gluon/pb"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// BPFTraceServer implements pb.BPFTraceServer using Linux eBPF uprobes.
// It attaches a uprobe to every non-runtime function entry in the target binary
// and streams a TraceEvent for each observed call. Requires kernel >= 5.15
// (bpf_get_attach_cookie for uprobes) and CAP_BPF or root.
type BPFTraceServer struct {
	pb.UnimplementedBPFTraceServer
}

// NewBPFTraceServer creates a new BPFTraceServer.
func NewBPFTraceServer() *BPFTraceServer { return &BPFTraceServer{} }

// bpfEvent mirrors the C struct event in bpf/trace.c.
type bpfEvent struct {
	CallerAddr  uint64
	CalleeAddr  uint64
	GoroutineID uint64
	TimestampNs uint64
}

// Run loads the eBPF program, attaches uprobes to every function in the binary,
// starts the target process, then streams TraceEvents until the binary exits or
// the client cancels.
func (s *BPFTraceServer) Run(req *pb.TraceRequest, stream grpc.ServerStreamingServer[pb.TraceEvent]) error {
	ctx := stream.Context()

	bin := req.GetBinary()
	if bin == "" {
		return status.Error(codes.InvalidArgument, "binary path is required")
	}

	syms, err := LoadSymbols(bin)
	if err != nil {
		return status.Errorf(codes.Internal, "load symbols: %v", err)
	}
	if len(syms) == 0 {
		return status.Error(codes.InvalidArgument, "no traceable symbols found in binary")
	}

	nameByAddr := addrToName(syms)

	goidOff, err := GoroutineIDOffset(bin)
	if err != nil {
		log.Printf("bpftrace: goroutine ID disabled: %v", err)
		goidOff = 0
	}

	// Load compiled eBPF objects (generated by bpf2go from bpf/trace.c).
	objs := traceObjects{}
	if err := loadTraceObjects(&objs, nil); err != nil {
		return status.Errorf(codes.Internal, "load eBPF objects: %v", err)
	}
	defer objs.Close()

	// Write the goroutine ID offset into the config map (key 0).
	if goidOff > 0 {
		var key uint32 = 0
		if err := objs.Config.Put(key, goidOff); err != nil {
			log.Printf("bpftrace: set goid_offset: %v", err)
		}
	}

	// Open the target executable for uprobe attachment.
	ex, err := link.OpenExecutable(bin)
	if err != nil {
		return status.Errorf(codes.Internal, "open executable for uprobes: %v", err)
	}

	// Attach a uprobe at each function entry, passing the function address as
	// the cookie so the eBPF program can report callee_addr without a map lookup.
	links := make([]link.Link, 0, len(syms))
	for _, sym := range syms {
		l, err := ex.Uprobe("", objs.TraceEntry, &link.UprobeOptions{
			Address: sym.Addr,
			Cookie:  sym.Addr,
		})
		if err != nil {
			// Some symbols may not be attachable (e.g. inlined); skip silently.
			continue
		}
		links = append(links, l)
	}
	if len(links) == 0 {
		return status.Error(codes.Internal, "no uprobes could be attached")
	}
	defer func() {
		for _, l := range links {
			l.Close()
		}
	}()

	// Open the ring buffer reader.
	rd, err := ringbuf.NewReader(objs.Events)
	if err != nil {
		return status.Errorf(codes.Internal, "open ring buffer: %v", err)
	}
	defer rd.Close()

	// Launch the target binary. It runs at full speed — eBPF has no
	// stop-the-world overhead unlike ptrace.
	cmd := exec.Command(bin, req.GetArgs()...)
	if err := cmd.Start(); err != nil {
		return status.Errorf(codes.Internal, "start process: %v", err)
	}

	procDone := make(chan error, 1)
	go func() { procDone <- cmd.Wait() }()

	// Close the ring buffer reader when the process exits or the client cancels,
	// which causes rd.Read() to unblock and return.
	go func() {
		select {
		case <-ctx.Done():
		case <-procDone:
		}
		rd.Close()
	}()

	// Read events from the ring buffer and stream them to the gRPC client.
	for {
		record, err := rd.Read()
		if err != nil {
			if err == ringbuf.ErrClosed {
				// Reader was closed (process exited or context cancelled).
				return nil
			}
			return status.Errorf(codes.Internal, "ring buffer read: %v", err)
		}

		if len(record.RawSample) < 32 {
			continue // truncated record, skip
		}

		ev := bpfEvent{
			CallerAddr:  binary.LittleEndian.Uint64(record.RawSample[0:]),
			CalleeAddr:  binary.LittleEndian.Uint64(record.RawSample[8:]),
			GoroutineID: binary.LittleEndian.Uint64(record.RawSample[16:]),
			TimestampNs: binary.LittleEndian.Uint64(record.RawSample[24:]),
		}

		callee, ok := nameByAddr[ev.CalleeAddr]
		if !ok {
			callee = fmt.Sprintf("0x%x", ev.CalleeAddr)
		}
		caller := findContainingFunction(syms, ev.CallerAddr)
		if caller == "" {
			caller = fmt.Sprintf("0x%x", ev.CallerAddr)
		}

		if err := stream.Send(&pb.TraceEvent{
			Caller:      caller,
			Callee:      callee,
			GoroutineId: int64(ev.GoroutineID),
			TimestampNs: int64(ev.TimestampNs),
		}); err != nil {
			return err
		}

		select {
		case <-ctx.Done():
			return ctx.Err()
		default:
		}
	}
}
