// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: ast.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ASTDescriptor is a language-agnostic container for a serialized abstract
// syntax tree. It pairs the source language identity with the tree itself,
// enabling cross-language AST manipulation and transpilation via protobuf
// as the common interchange format.
type ASTDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Language this AST was parsed from (e.g. "go", "proto", "ebnf").
	Language string `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	// Language spec version used during parsing (e.g. "1.26", "3").
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Root node of the abstract syntax tree.
	// TODO: Design and implement once GrammarDescriptor/ProductionDescriptor
	// are fleshed out. The node structure will mirror the production rules
	// of the source language's grammar, making it possible to mechanically
	// derive AST node types from EBNF definitions.
	Root          *ASTNodeDescriptor `protobuf:"bytes,3,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ASTDescriptor) Reset() {
	*x = ASTDescriptor{}
	mi := &file_ast_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ASTDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ASTDescriptor) ProtoMessage() {}

func (x *ASTDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_ast_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ASTDescriptor.ProtoReflect.Descriptor instead.
func (*ASTDescriptor) Descriptor() ([]byte, []int) {
	return file_ast_proto_rawDescGZIP(), []int{0}
}

func (x *ASTDescriptor) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ASTDescriptor) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ASTDescriptor) GetRoot() *ASTNodeDescriptor {
	if x != nil {
		return x.Root
	}
	return nil
}

// ASTNodeDescriptor represents a single node in a language-agnostic AST.
// TODO: Define fields. Expected structure:
//
//	string kind = 1;                    // node type (maps to a production name)
//	string value = 2;                   // terminal value, if leaf node
//	repeated ASTNodeDescriptor children = 3; // child nodes
//	SourceLocation location = 4;        // source position
type ASTNodeDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ASTNodeDescriptor) Reset() {
	*x = ASTNodeDescriptor{}
	mi := &file_ast_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ASTNodeDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ASTNodeDescriptor) ProtoMessage() {}

func (x *ASTNodeDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_ast_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ASTNodeDescriptor.ProtoReflect.Descriptor instead.
func (*ASTNodeDescriptor) Descriptor() ([]byte, []int) {
	return file_ast_proto_rawDescGZIP(), []int{1}
}

var File_ast_proto protoreflect.FileDescriptor

const file_ast_proto_rawDesc = "" +
	"\n" +
	"\tast.proto\x12\x05gluon\"s\n" +
	"\rASTDescriptor\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12,\n" +
	"\x04root\x18\x03 \x01(\v2\x18.gluon.ASTNodeDescriptorR\x04root\"\x13\n" +
	"\x11ASTNodeDescriptorB!Z\x1fgithub.com/accretional/gluon/pbb\x06proto3"

var (
	file_ast_proto_rawDescOnce sync.Once
	file_ast_proto_rawDescData []byte
)

func file_ast_proto_rawDescGZIP() []byte {
	file_ast_proto_rawDescOnce.Do(func() {
		file_ast_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ast_proto_rawDesc), len(file_ast_proto_rawDesc)))
	})
	return file_ast_proto_rawDescData
}

var file_ast_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ast_proto_goTypes = []any{
	(*ASTDescriptor)(nil),     // 0: gluon.ASTDescriptor
	(*ASTNodeDescriptor)(nil), // 1: gluon.ASTNodeDescriptor
}
var file_ast_proto_depIdxs = []int32{
	1, // 0: gluon.ASTDescriptor.root:type_name -> gluon.ASTNodeDescriptor
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ast_proto_init() }
func file_ast_proto_init() {
	if File_ast_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ast_proto_rawDesc), len(file_ast_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ast_proto_goTypes,
		DependencyIndexes: file_ast_proto_depIdxs,
		MessageInfos:      file_ast_proto_msgTypes,
	}.Build()
	File_ast_proto = out.File
	file_ast_proto_goTypes = nil
	file_ast_proto_depIdxs = nil
}
