// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: callgraph.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallGraphRequest_Algorithm int32

const (
	CallGraphRequest_ALGORITHM_UNKNOWN CallGraphRequest_Algorithm = 0 // Default: vta
	CallGraphRequest_static            CallGraphRequest_Algorithm = 1 // static calls only (fastest, unsound for dynamic dispatch)
	CallGraphRequest_cha               CallGraphRequest_Algorithm = 2 // class hierarchy analysis
	CallGraphRequest_rta               CallGraphRequest_Algorithm = 3 // rapid type analysis
	CallGraphRequest_vta               CallGraphRequest_Algorithm = 4 // variable type analysis (most precise)
)

// Enum value maps for CallGraphRequest_Algorithm.
var (
	CallGraphRequest_Algorithm_name = map[int32]string{
		0: "ALGORITHM_UNKNOWN",
		1: "static",
		2: "cha",
		3: "rta",
		4: "vta",
	}
	CallGraphRequest_Algorithm_value = map[string]int32{
		"ALGORITHM_UNKNOWN": 0,
		"static":            1,
		"cha":               2,
		"rta":               3,
		"vta":               4,
	}
)

func (x CallGraphRequest_Algorithm) Enum() *CallGraphRequest_Algorithm {
	p := new(CallGraphRequest_Algorithm)
	*p = x
	return p
}

func (x CallGraphRequest_Algorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallGraphRequest_Algorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_callgraph_proto_enumTypes[0].Descriptor()
}

func (CallGraphRequest_Algorithm) Type() protoreflect.EnumType {
	return &file_callgraph_proto_enumTypes[0]
}

func (x CallGraphRequest_Algorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CallGraphRequest_Algorithm.Descriptor instead.
func (CallGraphRequest_Algorithm) EnumDescriptor() ([]byte, []int) {
	return file_callgraph_proto_rawDescGZIP(), []int{0, 0}
}

type CallGraphRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Packages []string               `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"`
	// -algo: call graph construction algorithm (default: vta)
	Algo CallGraphRequest_Algorithm `protobuf:"varint,2,opt,name=algo,proto3,enum=gluon.CallGraphRequest_Algorithm" json:"algo,omitempty"`
	// -test: include the package's test source files in the analysis
	Test          bool `protobuf:"varint,3,opt,name=test,proto3" json:"test,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallGraphRequest) Reset() {
	*x = CallGraphRequest{}
	mi := &file_callgraph_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallGraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallGraphRequest) ProtoMessage() {}

func (x *CallGraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_callgraph_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallGraphRequest.ProtoReflect.Descriptor instead.
func (*CallGraphRequest) Descriptor() ([]byte, []int) {
	return file_callgraph_proto_rawDescGZIP(), []int{0}
}

func (x *CallGraphRequest) GetPackages() []string {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *CallGraphRequest) GetAlgo() CallGraphRequest_Algorithm {
	if x != nil {
		return x.Algo
	}
	return CallGraphRequest_ALGORITHM_UNKNOWN
}

func (x *CallGraphRequest) GetTest() bool {
	if x != nil {
		return x.Test
	}
	return false
}

type CallGraphFoldedRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CallgraphRequest *CallGraphRequest      `protobuf:"bytes,1,opt,name=callgraph_request,json=callgraphRequest,proto3" json:"callgraph_request,omitempty"`
	RootFolder       string                 `protobuf:"bytes,2,opt,name=root_folder,json=rootFolder,proto3" json:"root_folder,omitempty"`
	ExcludeStdlib    bool                   `protobuf:"varint,3,opt,name=exclude_stdlib,json=excludeStdlib,proto3" json:"exclude_stdlib,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CallGraphFoldedRequest) Reset() {
	*x = CallGraphFoldedRequest{}
	mi := &file_callgraph_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallGraphFoldedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallGraphFoldedRequest) ProtoMessage() {}

func (x *CallGraphFoldedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_callgraph_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallGraphFoldedRequest.ProtoReflect.Descriptor instead.
func (*CallGraphFoldedRequest) Descriptor() ([]byte, []int) {
	return file_callgraph_proto_rawDescGZIP(), []int{1}
}

func (x *CallGraphFoldedRequest) GetCallgraphRequest() *CallGraphRequest {
	if x != nil {
		return x.CallgraphRequest
	}
	return nil
}

func (x *CallGraphFoldedRequest) GetRootFolder() string {
	if x != nil {
		return x.RootFolder
	}
	return ""
}

func (x *CallGraphFoldedRequest) GetExcludeStdlib() bool {
	if x != nil {
		return x.ExcludeStdlib
	}
	return false
}

// A single directed edge in the call graph: caller -> callee.
type CallGraphEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Caller        string                 `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`
	Callee        string                 `protobuf:"bytes,2,opt,name=callee,proto3" json:"callee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallGraphEdge) Reset() {
	*x = CallGraphEdge{}
	mi := &file_callgraph_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallGraphEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallGraphEdge) ProtoMessage() {}

func (x *CallGraphEdge) ProtoReflect() protoreflect.Message {
	mi := &file_callgraph_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallGraphEdge.ProtoReflect.Descriptor instead.
func (*CallGraphEdge) Descriptor() ([]byte, []int) {
	return file_callgraph_proto_rawDescGZIP(), []int{2}
}

func (x *CallGraphEdge) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

func (x *CallGraphEdge) GetCallee() string {
	if x != nil {
		return x.Callee
	}
	return ""
}

var File_callgraph_proto protoreflect.FileDescriptor

const file_callgraph_proto_rawDesc = "" +
	"\n" +
	"\x0fcallgraph.proto\x12\x05gluon\x1a\bgo.proto\"\xc4\x01\n" +
	"\x10CallGraphRequest\x12\x1a\n" +
	"\bpackages\x18\x01 \x03(\tR\bpackages\x125\n" +
	"\x04algo\x18\x02 \x01(\x0e2!.gluon.CallGraphRequest.AlgorithmR\x04algo\x12\x12\n" +
	"\x04test\x18\x03 \x01(\bR\x04test\"I\n" +
	"\tAlgorithm\x12\x15\n" +
	"\x11ALGORITHM_UNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06static\x10\x01\x12\a\n" +
	"\x03cha\x10\x02\x12\a\n" +
	"\x03rta\x10\x03\x12\a\n" +
	"\x03vta\x10\x04\"\xa6\x01\n" +
	"\x16CallGraphFoldedRequest\x12D\n" +
	"\x11callgraph_request\x18\x01 \x01(\v2\x17.gluon.CallGraphRequestR\x10callgraphRequest\x12\x1f\n" +
	"\vroot_folder\x18\x02 \x01(\tR\n" +
	"rootFolder\x12%\n" +
	"\x0eexclude_stdlib\x18\x03 \x01(\bR\rexcludeStdlib\"?\n" +
	"\rCallGraphEdge\x12\x16\n" +
	"\x06caller\x18\x01 \x01(\tR\x06caller\x12\x16\n" +
	"\x06callee\x18\x02 \x01(\tR\x06callee2~\n" +
	"\tCallGraph\x126\n" +
	"\x03Run\x12\x17.gluon.CallGraphRequest\x1a\x14.gluon.CallGraphEdge0\x01\x129\n" +
	"\tRunFolded\x12\x1d.gluon.CallGraphFoldedRequest\x1a\v.gluon.Text0\x01B!Z\x1fgithub.com/accretional/gluon/pbb\x06proto3"

var (
	file_callgraph_proto_rawDescOnce sync.Once
	file_callgraph_proto_rawDescData []byte
)

func file_callgraph_proto_rawDescGZIP() []byte {
	file_callgraph_proto_rawDescOnce.Do(func() {
		file_callgraph_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_callgraph_proto_rawDesc), len(file_callgraph_proto_rawDesc)))
	})
	return file_callgraph_proto_rawDescData
}

var file_callgraph_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_callgraph_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_callgraph_proto_goTypes = []any{
	(CallGraphRequest_Algorithm)(0), // 0: gluon.CallGraphRequest.Algorithm
	(*CallGraphRequest)(nil),        // 1: gluon.CallGraphRequest
	(*CallGraphFoldedRequest)(nil),  // 2: gluon.CallGraphFoldedRequest
	(*CallGraphEdge)(nil),           // 3: gluon.CallGraphEdge
	(*Text)(nil),                    // 4: gluon.Text
}
var file_callgraph_proto_depIdxs = []int32{
	0, // 0: gluon.CallGraphRequest.algo:type_name -> gluon.CallGraphRequest.Algorithm
	1, // 1: gluon.CallGraphFoldedRequest.callgraph_request:type_name -> gluon.CallGraphRequest
	1, // 2: gluon.CallGraph.Run:input_type -> gluon.CallGraphRequest
	2, // 3: gluon.CallGraph.RunFolded:input_type -> gluon.CallGraphFoldedRequest
	3, // 4: gluon.CallGraph.Run:output_type -> gluon.CallGraphEdge
	4, // 5: gluon.CallGraph.RunFolded:output_type -> gluon.Text
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_callgraph_proto_init() }
func file_callgraph_proto_init() {
	if File_callgraph_proto != nil {
		return
	}
	file_go_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_callgraph_proto_rawDesc), len(file_callgraph_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_callgraph_proto_goTypes,
		DependencyIndexes: file_callgraph_proto_depIdxs,
		EnumInfos:         file_callgraph_proto_enumTypes,
		MessageInfos:      file_callgraph_proto_msgTypes,
	}.Build()
	File_callgraph_proto = out.File
	file_callgraph_proto_goTypes = nil
	file_callgraph_proto_depIdxs = nil
}
