// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: callgraph.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CallGraph_Run_FullMethodName       = "/gluon.CallGraph/Run"
	CallGraph_RunFolded_FullMethodName = "/gluon.CallGraph/RunFolded"
)

// CallGraphClient is the client API for CallGraph service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CallGraph builds a full callgraph for the requested packages and all
// transitive dependencies using SSA-based analysis.
type CallGraphClient interface {
	Run(ctx context.Context, in *CallGraphRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CallGraphEdge], error)
	RunFolded(ctx context.Context, in *CallGraphFoldedRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Text], error)
}

type callGraphClient struct {
	cc grpc.ClientConnInterface
}

func NewCallGraphClient(cc grpc.ClientConnInterface) CallGraphClient {
	return &callGraphClient{cc}
}

func (c *callGraphClient) Run(ctx context.Context, in *CallGraphRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CallGraphEdge], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CallGraph_ServiceDesc.Streams[0], CallGraph_Run_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CallGraphRequest, CallGraphEdge]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CallGraph_RunClient = grpc.ServerStreamingClient[CallGraphEdge]

func (c *callGraphClient) RunFolded(ctx context.Context, in *CallGraphFoldedRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Text], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CallGraph_ServiceDesc.Streams[1], CallGraph_RunFolded_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CallGraphFoldedRequest, Text]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CallGraph_RunFoldedClient = grpc.ServerStreamingClient[Text]

// CallGraphServer is the server API for CallGraph service.
// All implementations must embed UnimplementedCallGraphServer
// for forward compatibility.
//
// CallGraph builds a full callgraph for the requested packages and all
// transitive dependencies using SSA-based analysis.
type CallGraphServer interface {
	Run(*CallGraphRequest, grpc.ServerStreamingServer[CallGraphEdge]) error
	RunFolded(*CallGraphFoldedRequest, grpc.ServerStreamingServer[Text]) error
	mustEmbedUnimplementedCallGraphServer()
}

// UnimplementedCallGraphServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCallGraphServer struct{}

func (UnimplementedCallGraphServer) Run(*CallGraphRequest, grpc.ServerStreamingServer[CallGraphEdge]) error {
	return status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedCallGraphServer) RunFolded(*CallGraphFoldedRequest, grpc.ServerStreamingServer[Text]) error {
	return status.Error(codes.Unimplemented, "method RunFolded not implemented")
}
func (UnimplementedCallGraphServer) mustEmbedUnimplementedCallGraphServer() {}
func (UnimplementedCallGraphServer) testEmbeddedByValue()                   {}

// UnsafeCallGraphServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CallGraphServer will
// result in compilation errors.
type UnsafeCallGraphServer interface {
	mustEmbedUnimplementedCallGraphServer()
}

func RegisterCallGraphServer(s grpc.ServiceRegistrar, srv CallGraphServer) {
	// If the following call panics, it indicates UnimplementedCallGraphServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CallGraph_ServiceDesc, srv)
}

func _CallGraph_Run_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CallGraphRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CallGraphServer).Run(m, &grpc.GenericServerStream[CallGraphRequest, CallGraphEdge]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CallGraph_RunServer = grpc.ServerStreamingServer[CallGraphEdge]

func _CallGraph_RunFolded_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CallGraphFoldedRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CallGraphServer).RunFolded(m, &grpc.GenericServerStream[CallGraphFoldedRequest, Text]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CallGraph_RunFoldedServer = grpc.ServerStreamingServer[Text]

// CallGraph_ServiceDesc is the grpc.ServiceDesc for CallGraph service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CallGraph_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gluon.CallGraph",
	HandlerType: (*CallGraphServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Run",
			Handler:       _CallGraph_Run_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RunFolded",
			Handler:       _CallGraph_RunFolded_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "callgraph.proto",
}
