// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: callgraph.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CallGraph_Command_FullMethodName = "/gluon.CallGraph/Command"
	CallGraph_Run_FullMethodName     = "/gluon.CallGraph/Run"
)

// CallGraphClient is the client API for CallGraph service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Wrapper for https://pkg.go.dev/golang.org/x/tools/cmd/callgraph
type CallGraphClient interface {
	// General escape hatch that runs callgraph with arbitrary arguments
	Command(ctx context.Context, in *Text, opts ...grpc.CallOption) (*Text, error)
	// Run call graph analysis on the given packages, streaming one edge per message
	Run(ctx context.Context, in *CallGraphRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CallGraphEdge], error)
}

type callGraphClient struct {
	cc grpc.ClientConnInterface
}

func NewCallGraphClient(cc grpc.ClientConnInterface) CallGraphClient {
	return &callGraphClient{cc}
}

func (c *callGraphClient) Command(ctx context.Context, in *Text, opts ...grpc.CallOption) (*Text, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Text)
	err := c.cc.Invoke(ctx, CallGraph_Command_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callGraphClient) Run(ctx context.Context, in *CallGraphRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CallGraphEdge], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CallGraph_ServiceDesc.Streams[0], CallGraph_Run_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CallGraphRequest, CallGraphEdge]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CallGraph_RunClient = grpc.ServerStreamingClient[CallGraphEdge]

// CallGraphServer is the server API for CallGraph service.
// All implementations must embed UnimplementedCallGraphServer
// for forward compatibility.
//
// Wrapper for https://pkg.go.dev/golang.org/x/tools/cmd/callgraph
type CallGraphServer interface {
	// General escape hatch that runs callgraph with arbitrary arguments
	Command(context.Context, *Text) (*Text, error)
	// Run call graph analysis on the given packages, streaming one edge per message
	Run(*CallGraphRequest, grpc.ServerStreamingServer[CallGraphEdge]) error
	mustEmbedUnimplementedCallGraphServer()
}

// UnimplementedCallGraphServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCallGraphServer struct{}

func (UnimplementedCallGraphServer) Command(context.Context, *Text) (*Text, error) {
	return nil, status.Error(codes.Unimplemented, "method Command not implemented")
}
func (UnimplementedCallGraphServer) Run(*CallGraphRequest, grpc.ServerStreamingServer[CallGraphEdge]) error {
	return status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedCallGraphServer) mustEmbedUnimplementedCallGraphServer() {}
func (UnimplementedCallGraphServer) testEmbeddedByValue()                   {}

// UnsafeCallGraphServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CallGraphServer will
// result in compilation errors.
type UnsafeCallGraphServer interface {
	mustEmbedUnimplementedCallGraphServer()
}

func RegisterCallGraphServer(s grpc.ServiceRegistrar, srv CallGraphServer) {
	// If the following call panics, it indicates UnimplementedCallGraphServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CallGraph_ServiceDesc, srv)
}

func _CallGraph_Command_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Text)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallGraphServer).Command(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallGraph_Command_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallGraphServer).Command(ctx, req.(*Text))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallGraph_Run_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CallGraphRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CallGraphServer).Run(m, &grpc.GenericServerStream[CallGraphRequest, CallGraphEdge]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CallGraph_RunServer = grpc.ServerStreamingServer[CallGraphEdge]

// CallGraph_ServiceDesc is the grpc.ServiceDesc for CallGraph service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CallGraph_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gluon.CallGraph",
	HandlerType: (*CallGraphServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Command",
			Handler:    _CallGraph_Command_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Run",
			Handler:       _CallGraph_Run_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "callgraph.proto",
}
