// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: git.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FetchRequest specifies a repository to fetch and where to put it.
type FetchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Repo  *Repo                  `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	// Local filesystem path to clone/fetch into.
	// If empty, the server uses its configured default path.
	Dest string `protobuf:"bytes,2,opt,name=dest,proto3" json:"dest,omitempty"`
	// If true, do a shallow clone (--depth 1).
	Shallow       bool `protobuf:"varint,3,opt,name=shallow,proto3" json:"shallow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_git_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_git_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_git_proto_rawDescGZIP(), []int{0}
}

func (x *FetchRequest) GetRepo() *Repo {
	if x != nil {
		return x.Repo
	}
	return nil
}

func (x *FetchRequest) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

func (x *FetchRequest) GetShallow() bool {
	if x != nil {
		return x.Shallow
	}
	return false
}

// FetchResult describes the outcome of a fetch operation.
type FetchResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Local path where the repo was cloned/fetched.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// HEAD commit hash after fetch.
	HeadCommit string `protobuf:"bytes,2,opt,name=head_commit,json=headCommit,proto3" json:"head_commit,omitempty"`
	// Whether this was a fresh clone or an update of an existing repo.
	AlreadyExisted bool `protobuf:"varint,3,opt,name=already_existed,json=alreadyExisted,proto3" json:"already_existed,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FetchResult) Reset() {
	*x = FetchResult{}
	mi := &file_git_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResult) ProtoMessage() {}

func (x *FetchResult) ProtoReflect() protoreflect.Message {
	mi := &file_git_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResult.ProtoReflect.Descriptor instead.
func (*FetchResult) Descriptor() ([]byte, []int) {
	return file_git_proto_rawDescGZIP(), []int{1}
}

func (x *FetchResult) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FetchResult) GetHeadCommit() string {
	if x != nil {
		return x.HeadCommit
	}
	return ""
}

func (x *FetchResult) GetAlreadyExisted() bool {
	if x != nil {
		return x.AlreadyExisted
	}
	return false
}

// FileEntry describes a single file discovered in a repository.
type FileEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path relative to the repo root.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Size in bytes.
	Size          int64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEntry) Reset() {
	*x = FileEntry{}
	mi := &file_git_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntry) ProtoMessage() {}

func (x *FileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_git_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEntry.ProtoReflect.Descriptor instead.
func (*FileEntry) Descriptor() ([]byte, []int) {
	return file_git_proto_rawDescGZIP(), []int{2}
}

func (x *FileEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// ListFilesRequest asks for files matching a pattern in a fetched repo.
type ListFilesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Repo  *Repo                  `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	// Glob pattern to match (e.g. "**/*.proto").
	Pattern       string `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_git_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_git_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_git_proto_rawDescGZIP(), []int{3}
}

func (x *ListFilesRequest) GetRepo() *Repo {
	if x != nil {
		return x.Repo
	}
	return nil
}

func (x *ListFilesRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

// ListFilesResult returns the matching files.
type ListFilesResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileEntry           `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResult) Reset() {
	*x = ListFilesResult{}
	mi := &file_git_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResult) ProtoMessage() {}

func (x *ListFilesResult) ProtoReflect() protoreflect.Message {
	mi := &file_git_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResult.ProtoReflect.Descriptor instead.
func (*ListFilesResult) Descriptor() ([]byte, []int) {
	return file_git_proto_rawDescGZIP(), []int{4}
}

func (x *ListFilesResult) GetFiles() []*FileEntry {
	if x != nil {
		return x.Files
	}
	return nil
}

var File_git_proto protoreflect.FileDescriptor

const file_git_proto_rawDesc = "" +
	"\n" +
	"\tgit.proto\x12\x05gluon\x1a\vrepos.proto\"]\n" +
	"\fFetchRequest\x12\x1f\n" +
	"\x04repo\x18\x01 \x01(\v2\v.gluon.RepoR\x04repo\x12\x12\n" +
	"\x04dest\x18\x02 \x01(\tR\x04dest\x12\x18\n" +
	"\ashallow\x18\x03 \x01(\bR\ashallow\"k\n" +
	"\vFetchResult\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1f\n" +
	"\vhead_commit\x18\x02 \x01(\tR\n" +
	"headCommit\x12'\n" +
	"\x0falready_existed\x18\x03 \x01(\bR\x0ealreadyExisted\"3\n" +
	"\tFileEntry\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"M\n" +
	"\x10ListFilesRequest\x12\x1f\n" +
	"\x04repo\x18\x01 \x01(\v2\v.gluon.RepoR\x04repo\x12\x18\n" +
	"\apattern\x18\x02 \x01(\tR\apattern\"9\n" +
	"\x0fListFilesResult\x12&\n" +
	"\x05files\x18\x01 \x03(\v2\x10.gluon.FileEntryR\x05files2u\n" +
	"\x03Git\x120\n" +
	"\x05Fetch\x12\x13.gluon.FetchRequest\x1a\x12.gluon.FetchResult\x12<\n" +
	"\tListFiles\x12\x17.gluon.ListFilesRequest\x1a\x16.gluon.ListFilesResultB!Z\x1fgithub.com/accretional/gluon/pbb\x06proto3"

var (
	file_git_proto_rawDescOnce sync.Once
	file_git_proto_rawDescData []byte
)

func file_git_proto_rawDescGZIP() []byte {
	file_git_proto_rawDescOnce.Do(func() {
		file_git_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_git_proto_rawDesc), len(file_git_proto_rawDesc)))
	})
	return file_git_proto_rawDescData
}

var file_git_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_git_proto_goTypes = []any{
	(*FetchRequest)(nil),     // 0: gluon.FetchRequest
	(*FetchResult)(nil),      // 1: gluon.FetchResult
	(*FileEntry)(nil),        // 2: gluon.FileEntry
	(*ListFilesRequest)(nil), // 3: gluon.ListFilesRequest
	(*ListFilesResult)(nil),  // 4: gluon.ListFilesResult
	(*Repo)(nil),             // 5: gluon.Repo
}
var file_git_proto_depIdxs = []int32{
	5, // 0: gluon.FetchRequest.repo:type_name -> gluon.Repo
	5, // 1: gluon.ListFilesRequest.repo:type_name -> gluon.Repo
	2, // 2: gluon.ListFilesResult.files:type_name -> gluon.FileEntry
	0, // 3: gluon.Git.Fetch:input_type -> gluon.FetchRequest
	3, // 4: gluon.Git.ListFiles:input_type -> gluon.ListFilesRequest
	1, // 5: gluon.Git.Fetch:output_type -> gluon.FetchResult
	4, // 6: gluon.Git.ListFiles:output_type -> gluon.ListFilesResult
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_git_proto_init() }
func file_git_proto_init() {
	if File_git_proto != nil {
		return
	}
	file_repos_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_git_proto_rawDesc), len(file_git_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_git_proto_goTypes,
		DependencyIndexes: file_git_proto_depIdxs,
		MessageInfos:      file_git_proto_msgTypes,
	}.Build()
	File_git_proto = out.File
	file_git_proto_goTypes = nil
	file_git_proto_depIdxs = nil
}
