// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: git.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Git_Fetch_FullMethodName     = "/gluon.Git/Fetch"
	Git_ListFiles_FullMethodName = "/gluon.Git/ListFiles"
)

// GitClient is the client API for Git service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Git provides operations on git repositories.
type GitClient interface {
	// Fetch clones or updates a repository to the local filesystem.
	Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResult, error)
	// ListFiles returns files matching a glob pattern in a fetched repo.
	ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResult, error)
}

type gitClient struct {
	cc grpc.ClientConnInterface
}

func NewGitClient(cc grpc.ClientConnInterface) GitClient {
	return &gitClient{cc}
}

func (c *gitClient) Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchResult)
	err := c.cc.Invoke(ctx, Git_Fetch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitClient) ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFilesResult)
	err := c.cc.Invoke(ctx, Git_ListFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GitServer is the server API for Git service.
// All implementations must embed UnimplementedGitServer
// for forward compatibility.
//
// Git provides operations on git repositories.
type GitServer interface {
	// Fetch clones or updates a repository to the local filesystem.
	Fetch(context.Context, *FetchRequest) (*FetchResult, error)
	// ListFiles returns files matching a glob pattern in a fetched repo.
	ListFiles(context.Context, *ListFilesRequest) (*ListFilesResult, error)
	mustEmbedUnimplementedGitServer()
}

// UnimplementedGitServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGitServer struct{}

func (UnimplementedGitServer) Fetch(context.Context, *FetchRequest) (*FetchResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Fetch not implemented")
}
func (UnimplementedGitServer) ListFiles(context.Context, *ListFilesRequest) (*ListFilesResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedGitServer) mustEmbedUnimplementedGitServer() {}
func (UnimplementedGitServer) testEmbeddedByValue()             {}

// UnsafeGitServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GitServer will
// result in compilation errors.
type UnsafeGitServer interface {
	mustEmbedUnimplementedGitServer()
}

func RegisterGitServer(s grpc.ServiceRegistrar, srv GitServer) {
	// If the following call panics, it indicates UnimplementedGitServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Git_ServiceDesc, srv)
}

func _Git_Fetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServer).Fetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Git_Fetch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServer).Fetch(ctx, req.(*FetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Git_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Git_ListFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServer).ListFiles(ctx, req.(*ListFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Git_ServiceDesc is the grpc.ServiceDesc for Git service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Git_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gluon.Git",
	HandlerType: (*GitServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Fetch",
			Handler:    _Git_Fetch_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _Git_ListFiles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "git.proto",
}
