// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: go.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GoCompilerTarget_GOOS int32

const (
	GoCompilerTarget_GOOS_UNKNOWN GoCompilerTarget_GOOS = 0
	GoCompilerTarget_linux        GoCompilerTarget_GOOS = 1
	GoCompilerTarget_darwin       GoCompilerTarget_GOOS = 2
	GoCompilerTarget_windows      GoCompilerTarget_GOOS = 3
)

// Enum value maps for GoCompilerTarget_GOOS.
var (
	GoCompilerTarget_GOOS_name = map[int32]string{
		0: "GOOS_UNKNOWN",
		1: "linux",
		2: "darwin",
		3: "windows",
	}
	GoCompilerTarget_GOOS_value = map[string]int32{
		"GOOS_UNKNOWN": 0,
		"linux":        1,
		"darwin":       2,
		"windows":      3,
	}
)

func (x GoCompilerTarget_GOOS) Enum() *GoCompilerTarget_GOOS {
	p := new(GoCompilerTarget_GOOS)
	*p = x
	return p
}

func (x GoCompilerTarget_GOOS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GoCompilerTarget_GOOS) Descriptor() protoreflect.EnumDescriptor {
	return file_go_proto_enumTypes[0].Descriptor()
}

func (GoCompilerTarget_GOOS) Type() protoreflect.EnumType {
	return &file_go_proto_enumTypes[0]
}

func (x GoCompilerTarget_GOOS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GoCompilerTarget_GOOS.Descriptor instead.
func (GoCompilerTarget_GOOS) EnumDescriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{0, 0}
}

type GoCompilerTarget_GOARCH int32

const (
	GoCompilerTarget_GOARCH_UNKNOWN GoCompilerTarget_GOARCH = 0
	GoCompilerTarget_amd64          GoCompilerTarget_GOARCH = 1
	GoCompilerTarget__386           GoCompilerTarget_GOARCH = 2
	GoCompilerTarget_arm            GoCompilerTarget_GOARCH = 3
	GoCompilerTarget_arm64          GoCompilerTarget_GOARCH = 4
)

// Enum value maps for GoCompilerTarget_GOARCH.
var (
	GoCompilerTarget_GOARCH_name = map[int32]string{
		0: "GOARCH_UNKNOWN",
		1: "amd64",
		2: "_386",
		3: "arm",
		4: "arm64",
	}
	GoCompilerTarget_GOARCH_value = map[string]int32{
		"GOARCH_UNKNOWN": 0,
		"amd64":          1,
		"_386":           2,
		"arm":            3,
		"arm64":          4,
	}
)

func (x GoCompilerTarget_GOARCH) Enum() *GoCompilerTarget_GOARCH {
	p := new(GoCompilerTarget_GOARCH)
	*p = x
	return p
}

func (x GoCompilerTarget_GOARCH) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GoCompilerTarget_GOARCH) Descriptor() protoreflect.EnumDescriptor {
	return file_go_proto_enumTypes[1].Descriptor()
}

func (GoCompilerTarget_GOARCH) Type() protoreflect.EnumType {
	return &file_go_proto_enumTypes[1]
}

func (x GoCompilerTarget_GOARCH) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GoCompilerTarget_GOARCH.Descriptor instead.
func (GoCompilerTarget_GOARCH) EnumDescriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{0, 1}
}

type GoDocQuery_GoDocQueryFlags int32

const (
	GoDocQuery_GODOC_UNKNOWN      GoDocQuery_GoDocQueryFlags = 0
	GoDocQuery_all                GoDocQuery_GoDocQueryFlags = 1 // show all in package
	GoDocQuery_case_sensitive     GoDocQuery_GoDocQueryFlags = 2
	GoDocQuery_include_main_cmd   GoDocQuery_GoDocQueryFlags = 3 // by default, main is excluded
	GoDocQuery_http               GoDocQuery_GoDocQueryFlags = 4 // return html docs over http. Note: will cause the following to be downloaded. golang.org/x/pkgsite, golang.org/x/mod, github.com/google/safehtml, golang.org/x/tools, github.com/google/licensecheck, rsc.io/markdown
	GoDocQuery_short              GoDocQuery_GoDocQueryFlags = 5 // one-line representation for each symbol
	GoDocQuery_full_source        GoDocQuery_GoDocQueryFlags = 6 // full source per symbol, declaration, definition and impl, type declaration/enclosing costs
	GoDocQuery_include_unexported GoDocQuery_GoDocQueryFlags = 7 // also show docs over unexpected symbols, methods, and fields
)

// Enum value maps for GoDocQuery_GoDocQueryFlags.
var (
	GoDocQuery_GoDocQueryFlags_name = map[int32]string{
		0: "GODOC_UNKNOWN",
		1: "all",
		2: "case_sensitive",
		3: "include_main_cmd",
		4: "http",
		5: "short",
		6: "full_source",
		7: "include_unexported",
	}
	GoDocQuery_GoDocQueryFlags_value = map[string]int32{
		"GODOC_UNKNOWN":      0,
		"all":                1,
		"case_sensitive":     2,
		"include_main_cmd":   3,
		"http":               4,
		"short":              5,
		"full_source":        6,
		"include_unexported": 7,
	}
)

func (x GoDocQuery_GoDocQueryFlags) Enum() *GoDocQuery_GoDocQueryFlags {
	p := new(GoDocQuery_GoDocQueryFlags)
	*p = x
	return p
}

func (x GoDocQuery_GoDocQueryFlags) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GoDocQuery_GoDocQueryFlags) Descriptor() protoreflect.EnumDescriptor {
	return file_go_proto_enumTypes[2].Descriptor()
}

func (GoDocQuery_GoDocQueryFlags) Type() protoreflect.EnumType {
	return &file_go_proto_enumTypes[2]
}

func (x GoDocQuery_GoDocQueryFlags) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GoDocQuery_GoDocQueryFlags.Descriptor instead.
func (GoDocQuery_GoDocQueryFlags) EnumDescriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{1, 0}
}

type GoFormatRequest_PrintOptions int32

const (
	GoFormatRequest_PRINT_UNKNOWN GoFormatRequest_PrintOptions = 0
	GoFormatRequest_Replace       GoFormatRequest_PrintOptions = 1
	GoFormatRequest_Diffs         GoFormatRequest_PrintOptions = 2
	GoFormatRequest_Filenames     GoFormatRequest_PrintOptions = 3
)

// Enum value maps for GoFormatRequest_PrintOptions.
var (
	GoFormatRequest_PrintOptions_name = map[int32]string{
		0: "PRINT_UNKNOWN",
		1: "Replace",
		2: "Diffs",
		3: "Filenames",
	}
	GoFormatRequest_PrintOptions_value = map[string]int32{
		"PRINT_UNKNOWN": 0,
		"Replace":       1,
		"Diffs":         2,
		"Filenames":     3,
	}
)

func (x GoFormatRequest_PrintOptions) Enum() *GoFormatRequest_PrintOptions {
	p := new(GoFormatRequest_PrintOptions)
	*p = x
	return p
}

func (x GoFormatRequest_PrintOptions) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GoFormatRequest_PrintOptions) Descriptor() protoreflect.EnumDescriptor {
	return file_go_proto_enumTypes[3].Descriptor()
}

func (GoFormatRequest_PrintOptions) Type() protoreflect.EnumType {
	return &file_go_proto_enumTypes[3]
}

func (x GoFormatRequest_PrintOptions) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GoFormatRequest_PrintOptions.Descriptor instead.
func (GoFormatRequest_PrintOptions) EnumDescriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{3, 0}
}

// First class architectures: darwin/amd64, darwin/arm64, linux/386, linux/amd64, linux/arm, linux/arm64, windows/386, windows/amd64
// Full list of supported os/architecture pairs can be found at https://go.dev/doc/install/source
// Each default to being unset, which in golang triggers a general build
type GoCompilerTarget struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Os            GoCompilerTarget_GOOS   `protobuf:"varint,1,opt,name=os,proto3,enum=gluon.GoCompilerTarget_GOOS" json:"os,omitempty"`
	Arch          GoCompilerTarget_GOARCH `protobuf:"varint,2,opt,name=arch,proto3,enum=gluon.GoCompilerTarget_GOARCH" json:"arch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoCompilerTarget) Reset() {
	*x = GoCompilerTarget{}
	mi := &file_go_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoCompilerTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoCompilerTarget) ProtoMessage() {}

func (x *GoCompilerTarget) ProtoReflect() protoreflect.Message {
	mi := &file_go_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoCompilerTarget.ProtoReflect.Descriptor instead.
func (*GoCompilerTarget) Descriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{0}
}

func (x *GoCompilerTarget) GetOs() GoCompilerTarget_GOOS {
	if x != nil {
		return x.Os
	}
	return GoCompilerTarget_GOOS_UNKNOWN
}

func (x *GoCompilerTarget) GetArch() GoCompilerTarget_GOARCH {
	if x != nil {
		return x.Arch
	}
	return GoCompilerTarget_GOARCH_UNKNOWN
}

type GoDocQuery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If not provided, look in current package.
	Pkg string `protobuf:"bytes,1,opt,name=pkg,proto3" json:"pkg,omitempty"`
	// exported package-level symbol
	Symbol        string                       `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	MethodOrField []string                     `protobuf:"bytes,3,rep,name=method_or_field,json=methodOrField,proto3" json:"method_or_field,omitempty"`
	Flags         []GoDocQuery_GoDocQueryFlags `protobuf:"varint,4,rep,packed,name=flags,proto3,enum=gluon.GoDocQuery_GoDocQueryFlags" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoDocQuery) Reset() {
	*x = GoDocQuery{}
	mi := &file_go_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoDocQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoDocQuery) ProtoMessage() {}

func (x *GoDocQuery) ProtoReflect() protoreflect.Message {
	mi := &file_go_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoDocQuery.ProtoReflect.Descriptor instead.
func (*GoDocQuery) Descriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{1}
}

func (x *GoDocQuery) GetPkg() string {
	if x != nil {
		return x.Pkg
	}
	return ""
}

func (x *GoDocQuery) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GoDocQuery) GetMethodOrField() []string {
	if x != nil {
		return x.MethodOrField
	}
	return nil
}

func (x *GoDocQuery) GetFlags() []GoDocQuery_GoDocQueryFlags {
	if x != nil {
		return x.Flags
	}
	return nil
}

type GoFixQuery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Pkg   string                 `protobuf:"bytes,1,opt,name=pkg,proto3" json:"pkg,omitempty"`
	Path  string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Diff  bool                   `protobuf:"varint,3,opt,name=diff,proto3" json:"diff,omitempty"`
	// If left empty, run all fixers
	Analyzers     []string          `protobuf:"bytes,4,rep,name=analyzers,proto3" json:"analyzers,omitempty"`
	Target        *GoCompilerTarget `protobuf:"bytes,5,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoFixQuery) Reset() {
	*x = GoFixQuery{}
	mi := &file_go_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoFixQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoFixQuery) ProtoMessage() {}

func (x *GoFixQuery) ProtoReflect() protoreflect.Message {
	mi := &file_go_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoFixQuery.ProtoReflect.Descriptor instead.
func (*GoFixQuery) Descriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{2}
}

func (x *GoFixQuery) GetPkg() string {
	if x != nil {
		return x.Pkg
	}
	return ""
}

func (x *GoFixQuery) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GoFixQuery) GetDiff() bool {
	if x != nil {
		return x.Diff
	}
	return false
}

func (x *GoFixQuery) GetAnalyzers() []string {
	if x != nil {
		return x.Analyzers
	}
	return nil
}

func (x *GoFixQuery) GetTarget() *GoCompilerTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

type GoFormatRequest struct {
	state          protoimpl.MessageState       `protogen:"open.v1"`
	Packages       []string                     `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"`
	GoExpression   string                       `protobuf:"bytes,2,opt,name=go_expression,json=goExpression,proto3" json:"go_expression,omitempty"`
	PrintAllErrors bool                         `protobuf:"varint,3,opt,name=print_all_errors,json=printAllErrors,proto3" json:"print_all_errors,omitempty"`
	PrintOptions   GoFormatRequest_PrintOptions `protobuf:"varint,4,opt,name=print_options,json=printOptions,proto3,enum=gluon.GoFormatRequest_PrintOptions" json:"print_options,omitempty"`
	RewriteRule    *GoFormatRequest_RewriteRule `protobuf:"bytes,5,opt,name=rewrite_rule,json=rewriteRule,proto3" json:"rewrite_rule,omitempty"`
	Simplify       bool                         `protobuf:"varint,6,opt,name=simplify,proto3" json:"simplify,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GoFormatRequest) Reset() {
	*x = GoFormatRequest{}
	mi := &file_go_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoFormatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoFormatRequest) ProtoMessage() {}

func (x *GoFormatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoFormatRequest.ProtoReflect.Descriptor instead.
func (*GoFormatRequest) Descriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{3}
}

func (x *GoFormatRequest) GetPackages() []string {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *GoFormatRequest) GetGoExpression() string {
	if x != nil {
		return x.GoExpression
	}
	return ""
}

func (x *GoFormatRequest) GetPrintAllErrors() bool {
	if x != nil {
		return x.PrintAllErrors
	}
	return false
}

func (x *GoFormatRequest) GetPrintOptions() GoFormatRequest_PrintOptions {
	if x != nil {
		return x.PrintOptions
	}
	return GoFormatRequest_PRINT_UNKNOWN
}

func (x *GoFormatRequest) GetRewriteRule() *GoFormatRequest_RewriteRule {
	if x != nil {
		return x.RewriteRule
	}
	return nil
}

func (x *GoFormatRequest) GetSimplify() bool {
	if x != nil {
		return x.Simplify
	}
	return false
}

type GoGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packages      []string               `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"`
	Upgrade       bool                   `protobuf:"varint,2,opt,name=upgrade,proto3" json:"upgrade,omitempty"`
	IncludeTests  bool                   `protobuf:"varint,3,opt,name=include_tests,json=includeTests,proto3" json:"include_tests,omitempty"` // Never implement -d as it's deprecated since Go 1.17
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoGetRequest) Reset() {
	*x = GoGetRequest{}
	mi := &file_go_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoGetRequest) ProtoMessage() {}

func (x *GoGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoGetRequest.ProtoReflect.Descriptor instead.
func (*GoGetRequest) Descriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{4}
}

func (x *GoGetRequest) GetPackages() []string {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *GoGetRequest) GetUpgrade() bool {
	if x != nil {
		return x.Upgrade
	}
	return false
}

func (x *GoGetRequest) GetIncludeTests() bool {
	if x != nil {
		return x.IncludeTests
	}
	return false
}

type GoInstallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packages      []string               `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoInstallRequest) Reset() {
	*x = GoInstallRequest{}
	mi := &file_go_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoInstallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoInstallRequest) ProtoMessage() {}

func (x *GoInstallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoInstallRequest.ProtoReflect.Descriptor instead.
func (*GoInstallRequest) Descriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{5}
}

func (x *GoInstallRequest) GetPackages() []string {
	if x != nil {
		return x.Packages
	}
	return nil
}

type GoListRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Modules     bool                   `protobuf:"varint,1,opt,name=modules,proto3" json:"modules,omitempty"`
	UpgradeInfo bool                   `protobuf:"varint,2,opt,name=upgrade_info,json=upgradeInfo,proto3" json:"upgrade_info,omitempty"`
	Retracted   bool                   `protobuf:"varint,3,opt,name=retracted,proto3" json:"retracted,omitempty"`
	Versions    bool                   `protobuf:"varint,4,opt,name=versions,proto3" json:"versions,omitempty"`
	// TODO: eventually add other special handling for this into a proper protocol
	Json          bool     `protobuf:"varint,5,opt,name=json,proto3" json:"json,omitempty"`
	Packages      []string `protobuf:"bytes,6,rep,name=packages,proto3" json:"packages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoListRequest) Reset() {
	*x = GoListRequest{}
	mi := &file_go_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoListRequest) ProtoMessage() {}

func (x *GoListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoListRequest.ProtoReflect.Descriptor instead.
func (*GoListRequest) Descriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{6}
}

func (x *GoListRequest) GetModules() bool {
	if x != nil {
		return x.Modules
	}
	return false
}

func (x *GoListRequest) GetUpgradeInfo() bool {
	if x != nil {
		return x.UpgradeInfo
	}
	return false
}

func (x *GoListRequest) GetRetracted() bool {
	if x != nil {
		return x.Retracted
	}
	return false
}

func (x *GoListRequest) GetVersions() bool {
	if x != nil {
		return x.Versions
	}
	return false
}

func (x *GoListRequest) GetJson() bool {
	if x != nil {
		return x.Json
	}
	return false
}

func (x *GoListRequest) GetPackages() []string {
	if x != nil {
		return x.Packages
	}
	return nil
}

type GoEnvironmentVariable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoEnvironmentVariable) Reset() {
	*x = GoEnvironmentVariable{}
	mi := &file_go_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoEnvironmentVariable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoEnvironmentVariable) ProtoMessage() {}

func (x *GoEnvironmentVariable) ProtoReflect() protoreflect.Message {
	mi := &file_go_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoEnvironmentVariable.ProtoReflect.Descriptor instead.
func (*GoEnvironmentVariable) Descriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{7}
}

func (x *GoEnvironmentVariable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GoEnvironmentVariable) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GoEnvRequest struct {
	state   protoimpl.MessageState   `protogen:"open.v1"`
	Json    bool                     `protobuf:"varint,1,opt,name=json,proto3" json:"json,omitempty"`
	Unset   []string                 `protobuf:"bytes,2,rep,name=unset,proto3" json:"unset,omitempty"`
	Set     []*GoEnvironmentVariable `protobuf:"bytes,3,rep,name=set,proto3" json:"set,omitempty"`
	Changed bool                     `protobuf:"varint,4,opt,name=changed,proto3" json:"changed,omitempty"`
	// Variable names to query (positional args to `go env`)
	Vars          []string `protobuf:"bytes,5,rep,name=vars,proto3" json:"vars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoEnvRequest) Reset() {
	*x = GoEnvRequest{}
	mi := &file_go_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoEnvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoEnvRequest) ProtoMessage() {}

func (x *GoEnvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoEnvRequest.ProtoReflect.Descriptor instead.
func (*GoEnvRequest) Descriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{8}
}

func (x *GoEnvRequest) GetJson() bool {
	if x != nil {
		return x.Json
	}
	return false
}

func (x *GoEnvRequest) GetUnset() []string {
	if x != nil {
		return x.Unset
	}
	return nil
}

func (x *GoEnvRequest) GetSet() []*GoEnvironmentVariable {
	if x != nil {
		return x.Set
	}
	return nil
}

func (x *GoEnvRequest) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

func (x *GoEnvRequest) GetVars() []string {
	if x != nil {
		return x.Vars
	}
	return nil
}

// go build [-o output] [-v] [-race] [-ldflags] [-tags] [-trimpath] [-gcflags] [-asmflags] [packages]
type GoBuildRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Packages []string               `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"`
	// -o: output file or directory
	Output string `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	// -v: print package names as compiled
	Verbose bool `protobuf:"varint,3,opt,name=verbose,proto3" json:"verbose,omitempty"`
	// -race: enable race detector
	Race bool `protobuf:"varint,4,opt,name=race,proto3" json:"race,omitempty"`
	// -ldflags: arguments to pass on each go tool link invocation
	Ldflags string `protobuf:"bytes,5,opt,name=ldflags,proto3" json:"ldflags,omitempty"`
	// -tags: build constraint tags
	Tags []string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	// -trimpath: remove all file system paths from the resulting executable
	Trimpath bool `protobuf:"varint,7,opt,name=trimpath,proto3" json:"trimpath,omitempty"`
	// -gcflags: arguments to pass on each go tool compile invocation
	Gcflags string `protobuf:"bytes,8,opt,name=gcflags,proto3" json:"gcflags,omitempty"`
	// -asmflags: arguments to pass on each go tool asm invocation
	Asmflags string `protobuf:"bytes,9,opt,name=asmflags,proto3" json:"asmflags,omitempty"`
	// Cross-compilation target
	Target *GoCompilerTarget `protobuf:"bytes,10,opt,name=target,proto3" json:"target,omitempty"`
	// -work: print the name of the temporary work directory and do not delete it when exiting
	Work          bool `protobuf:"varint,11,opt,name=work,proto3" json:"work,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoBuildRequest) Reset() {
	*x = GoBuildRequest{}
	mi := &file_go_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoBuildRequest) ProtoMessage() {}

func (x *GoBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoBuildRequest.ProtoReflect.Descriptor instead.
func (*GoBuildRequest) Descriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{9}
}

func (x *GoBuildRequest) GetPackages() []string {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *GoBuildRequest) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *GoBuildRequest) GetVerbose() bool {
	if x != nil {
		return x.Verbose
	}
	return false
}

func (x *GoBuildRequest) GetRace() bool {
	if x != nil {
		return x.Race
	}
	return false
}

func (x *GoBuildRequest) GetLdflags() string {
	if x != nil {
		return x.Ldflags
	}
	return ""
}

func (x *GoBuildRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *GoBuildRequest) GetTrimpath() bool {
	if x != nil {
		return x.Trimpath
	}
	return false
}

func (x *GoBuildRequest) GetGcflags() string {
	if x != nil {
		return x.Gcflags
	}
	return ""
}

func (x *GoBuildRequest) GetAsmflags() string {
	if x != nil {
		return x.Asmflags
	}
	return ""
}

func (x *GoBuildRequest) GetTarget() *GoCompilerTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *GoBuildRequest) GetWork() bool {
	if x != nil {
		return x.Work
	}
	return false
}

// go run [-race] [-v] [-tags] [-exec xprog] package [arguments...]
type GoRunRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Package or .go files to run
	Package string `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	// Arguments passed to the built binary
	Args    []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Verbose bool     `protobuf:"varint,3,opt,name=verbose,proto3" json:"verbose,omitempty"`
	Race    bool     `protobuf:"varint,4,opt,name=race,proto3" json:"race,omitempty"`
	Tags    []string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	// -exec: invoke the binary using xprog
	ExecCmd string `protobuf:"bytes,6,opt,name=exec_cmd,json=execCmd,proto3" json:"exec_cmd,omitempty"`
	// -work: print the name of the temporary work directory and do not delete it when exiting
	Work          bool              `protobuf:"varint,7,opt,name=work,proto3" json:"work,omitempty"`
	Target        *GoCompilerTarget `protobuf:"bytes,8,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoRunRequest) Reset() {
	*x = GoRunRequest{}
	mi := &file_go_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoRunRequest) ProtoMessage() {}

func (x *GoRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoRunRequest.ProtoReflect.Descriptor instead.
func (*GoRunRequest) Descriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{10}
}

func (x *GoRunRequest) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *GoRunRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *GoRunRequest) GetVerbose() bool {
	if x != nil {
		return x.Verbose
	}
	return false
}

func (x *GoRunRequest) GetRace() bool {
	if x != nil {
		return x.Race
	}
	return false
}

func (x *GoRunRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *GoRunRequest) GetExecCmd() string {
	if x != nil {
		return x.ExecCmd
	}
	return ""
}

func (x *GoRunRequest) GetWork() bool {
	if x != nil {
		return x.Work
	}
	return false
}

func (x *GoRunRequest) GetTarget() *GoCompilerTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

// go test [-v] [-race] [-run regexp] [-bench regexp] [-count n] [-timeout d]
//
//	[-short] [-cover] [-coverprofile file] [-json] [-tags] [packages] [testflags]
type GoTestRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Packages []string               `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"`
	Verbose  bool                   `protobuf:"varint,2,opt,name=verbose,proto3" json:"verbose,omitempty"`
	Race     bool                   `protobuf:"varint,3,opt,name=race,proto3" json:"race,omitempty"`
	// -run: regexp to select tests/examples to run
	Run string `protobuf:"bytes,4,opt,name=run,proto3" json:"run,omitempty"`
	// -bench: regexp to select benchmarks to run; use "." for all
	Bench string `protobuf:"bytes,5,opt,name=bench,proto3" json:"bench,omitempty"`
	// -count: number of times to run each test
	Count int32 `protobuf:"varint,6,opt,name=count,proto3" json:"count,omitempty"`
	// -timeout: panic if test binary runs longer than duration (e.g. "10m")
	Timeout string `protobuf:"bytes,7,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// -short: tell long-running tests to shorten their run time
	Short bool `protobuf:"varint,8,opt,name=short,proto3" json:"short,omitempty"`
	// -cover: enable coverage analysis
	Cover bool `protobuf:"varint,9,opt,name=cover,proto3" json:"cover,omitempty"`
	// -coverprofile: write coverage profile to file
	Coverprofile string `protobuf:"bytes,10,opt,name=coverprofile,proto3" json:"coverprofile,omitempty"`
	// -json: output in JSON format (for machine consumption)
	Json bool     `protobuf:"varint,11,opt,name=json,proto3" json:"json,omitempty"`
	Tags []string `protobuf:"bytes,12,rep,name=tags,proto3" json:"tags,omitempty"`
	// -failfast: do not start new tests after the first test failure
	Failfast bool `protobuf:"varint,13,opt,name=failfast,proto3" json:"failfast,omitempty"`
	// -benchmem: print memory allocation statistics for benchmarks
	Benchmem bool `protobuf:"varint,14,opt,name=benchmem,proto3" json:"benchmem,omitempty"`
	// -benchtime: run enough iterations of each benchmark to take approximately d (e.g. "5s", "100x")
	Benchtime     string            `protobuf:"bytes,15,opt,name=benchtime,proto3" json:"benchtime,omitempty"`
	Target        *GoCompilerTarget `protobuf:"bytes,16,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoTestRequest) Reset() {
	*x = GoTestRequest{}
	mi := &file_go_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoTestRequest) ProtoMessage() {}

func (x *GoTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoTestRequest.ProtoReflect.Descriptor instead.
func (*GoTestRequest) Descriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{11}
}

func (x *GoTestRequest) GetPackages() []string {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *GoTestRequest) GetVerbose() bool {
	if x != nil {
		return x.Verbose
	}
	return false
}

func (x *GoTestRequest) GetRace() bool {
	if x != nil {
		return x.Race
	}
	return false
}

func (x *GoTestRequest) GetRun() string {
	if x != nil {
		return x.Run
	}
	return ""
}

func (x *GoTestRequest) GetBench() string {
	if x != nil {
		return x.Bench
	}
	return ""
}

func (x *GoTestRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GoTestRequest) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

func (x *GoTestRequest) GetShort() bool {
	if x != nil {
		return x.Short
	}
	return false
}

func (x *GoTestRequest) GetCover() bool {
	if x != nil {
		return x.Cover
	}
	return false
}

func (x *GoTestRequest) GetCoverprofile() string {
	if x != nil {
		return x.Coverprofile
	}
	return ""
}

func (x *GoTestRequest) GetJson() bool {
	if x != nil {
		return x.Json
	}
	return false
}

func (x *GoTestRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *GoTestRequest) GetFailfast() bool {
	if x != nil {
		return x.Failfast
	}
	return false
}

func (x *GoTestRequest) GetBenchmem() bool {
	if x != nil {
		return x.Benchmem
	}
	return false
}

func (x *GoTestRequest) GetBenchtime() string {
	if x != nil {
		return x.Benchtime
	}
	return ""
}

func (x *GoTestRequest) GetTarget() *GoCompilerTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

// go generate [-v] [-n] [-x] [-run regexp] [packages]
type GoGenerateRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Packages []string               `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"`
	Verbose  bool                   `protobuf:"varint,2,opt,name=verbose,proto3" json:"verbose,omitempty"`
	// -n: print commands that would be executed
	DryRun bool `protobuf:"varint,3,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	// -x: print commands as they are executed
	PrintCommands bool `protobuf:"varint,4,opt,name=print_commands,json=printCommands,proto3" json:"print_commands,omitempty"`
	// -run: regexp to restrict generate directives
	Run           string `protobuf:"bytes,5,opt,name=run,proto3" json:"run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoGenerateRequest) Reset() {
	*x = GoGenerateRequest{}
	mi := &file_go_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoGenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoGenerateRequest) ProtoMessage() {}

func (x *GoGenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoGenerateRequest.ProtoReflect.Descriptor instead.
func (*GoGenerateRequest) Descriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{12}
}

func (x *GoGenerateRequest) GetPackages() []string {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *GoGenerateRequest) GetVerbose() bool {
	if x != nil {
		return x.Verbose
	}
	return false
}

func (x *GoGenerateRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

func (x *GoGenerateRequest) GetPrintCommands() bool {
	if x != nil {
		return x.PrintCommands
	}
	return false
}

func (x *GoGenerateRequest) GetRun() string {
	if x != nil {
		return x.Run
	}
	return ""
}

// go vet [-v] [-json] [-tags] [packages]
type GoVetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packages      []string               `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"`
	Verbose       bool                   `protobuf:"varint,2,opt,name=verbose,proto3" json:"verbose,omitempty"`
	Json          bool                   `protobuf:"varint,3,opt,name=json,proto3" json:"json,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoVetRequest) Reset() {
	*x = GoVetRequest{}
	mi := &file_go_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoVetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoVetRequest) ProtoMessage() {}

func (x *GoVetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoVetRequest.ProtoReflect.Descriptor instead.
func (*GoVetRequest) Descriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{13}
}

func (x *GoVetRequest) GetPackages() []string {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *GoVetRequest) GetVerbose() bool {
	if x != nil {
		return x.Verbose
	}
	return false
}

func (x *GoVetRequest) GetJson() bool {
	if x != nil {
		return x.Json
	}
	return false
}

func (x *GoVetRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// go tool [-n] [command] [args...]
type GoToolRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Args  []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	// -n: print command that would be executed
	DryRun        bool `protobuf:"varint,3,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoToolRequest) Reset() {
	*x = GoToolRequest{}
	mi := &file_go_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoToolRequest) ProtoMessage() {}

func (x *GoToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoToolRequest.ProtoReflect.Descriptor instead.
func (*GoToolRequest) Descriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{14}
}

func (x *GoToolRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GoToolRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *GoToolRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

// Simple text message for the Command RPC
type Text struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Text) Reset() {
	*x = Text{}
	mi := &file_go_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Text) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Text) ProtoMessage() {}

func (x *Text) ProtoReflect() protoreflect.Message {
	mi := &file_go_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Text.ProtoReflect.Descriptor instead.
func (*Text) Descriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{15}
}

func (x *Text) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// Empty message for RPCs that take no input
type Nothing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nothing) Reset() {
	*x = Nothing{}
	mi := &file_go_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nothing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nothing) ProtoMessage() {}

func (x *Nothing) ProtoReflect() protoreflect.Message {
	mi := &file_go_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nothing.ProtoReflect.Descriptor instead.
func (*Nothing) Descriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{16}
}

// go mod download [-json] [-x] [modules]
type GoModDownloadRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Modules []string               `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
	Json    bool                   `protobuf:"varint,2,opt,name=json,proto3" json:"json,omitempty"`
	// -x: print commands as they are executed
	PrintCommands bool `protobuf:"varint,3,opt,name=print_commands,json=printCommands,proto3" json:"print_commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoModDownloadRequest) Reset() {
	*x = GoModDownloadRequest{}
	mi := &file_go_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoModDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoModDownloadRequest) ProtoMessage() {}

func (x *GoModDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoModDownloadRequest.ProtoReflect.Descriptor instead.
func (*GoModDownloadRequest) Descriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{17}
}

func (x *GoModDownloadRequest) GetModules() []string {
	if x != nil {
		return x.Modules
	}
	return nil
}

func (x *GoModDownloadRequest) GetJson() bool {
	if x != nil {
		return x.Json
	}
	return false
}

func (x *GoModDownloadRequest) GetPrintCommands() bool {
	if x != nil {
		return x.PrintCommands
	}
	return false
}

// go mod edit — structured edits to go.mod
// Flags are modeled as repeated operations so multiple can be applied in one call.
type GoModEditRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// -module: change the module path
	Module string `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	// -go: set the expected Go language version
	GoVersion string `protobuf:"bytes,2,opt,name=go_version,json=goVersion,proto3" json:"go_version,omitempty"`
	// -require: add a requirement (module@version)
	Require []string `protobuf:"bytes,3,rep,name=require,proto3" json:"require,omitempty"`
	// -droprequire: drop a requirement (module path)
	DropRequire []string `protobuf:"bytes,4,rep,name=drop_require,json=dropRequire,proto3" json:"drop_require,omitempty"`
	// -replace: add a replacement (old[@v]=new[@v])
	Replace []string `protobuf:"bytes,5,rep,name=replace,proto3" json:"replace,omitempty"`
	// -dropreplace: drop a replacement (old[@v])
	DropReplace []string `protobuf:"bytes,6,rep,name=drop_replace,json=dropReplace,proto3" json:"drop_replace,omitempty"`
	// -exclude: add an exclusion (module@version)
	Exclude []string `protobuf:"bytes,7,rep,name=exclude,proto3" json:"exclude,omitempty"`
	// -dropexclude: drop an exclusion (module@version)
	DropExclude []string `protobuf:"bytes,8,rep,name=drop_exclude,json=dropExclude,proto3" json:"drop_exclude,omitempty"`
	// -retract: add a retraction (version or [low,high])
	Retract []string `protobuf:"bytes,9,rep,name=retract,proto3" json:"retract,omitempty"`
	// -dropretract: drop a retraction
	DropRetract []string `protobuf:"bytes,10,rep,name=drop_retract,json=dropRetract,proto3" json:"drop_retract,omitempty"`
	// -json: print the final go.mod in JSON format
	Json bool `protobuf:"varint,11,opt,name=json,proto3" json:"json,omitempty"`
	// -print: print the final go.mod (default behavior when no -json)
	Print bool `protobuf:"varint,12,opt,name=print,proto3" json:"print,omitempty"`
	// -fmt: reformats go.mod without making other changes
	Fmt           bool `protobuf:"varint,13,opt,name=fmt,proto3" json:"fmt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoModEditRequest) Reset() {
	*x = GoModEditRequest{}
	mi := &file_go_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoModEditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoModEditRequest) ProtoMessage() {}

func (x *GoModEditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoModEditRequest.ProtoReflect.Descriptor instead.
func (*GoModEditRequest) Descriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{18}
}

func (x *GoModEditRequest) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *GoModEditRequest) GetGoVersion() string {
	if x != nil {
		return x.GoVersion
	}
	return ""
}

func (x *GoModEditRequest) GetRequire() []string {
	if x != nil {
		return x.Require
	}
	return nil
}

func (x *GoModEditRequest) GetDropRequire() []string {
	if x != nil {
		return x.DropRequire
	}
	return nil
}

func (x *GoModEditRequest) GetReplace() []string {
	if x != nil {
		return x.Replace
	}
	return nil
}

func (x *GoModEditRequest) GetDropReplace() []string {
	if x != nil {
		return x.DropReplace
	}
	return nil
}

func (x *GoModEditRequest) GetExclude() []string {
	if x != nil {
		return x.Exclude
	}
	return nil
}

func (x *GoModEditRequest) GetDropExclude() []string {
	if x != nil {
		return x.DropExclude
	}
	return nil
}

func (x *GoModEditRequest) GetRetract() []string {
	if x != nil {
		return x.Retract
	}
	return nil
}

func (x *GoModEditRequest) GetDropRetract() []string {
	if x != nil {
		return x.DropRetract
	}
	return nil
}

func (x *GoModEditRequest) GetJson() bool {
	if x != nil {
		return x.Json
	}
	return false
}

func (x *GoModEditRequest) GetPrint() bool {
	if x != nil {
		return x.Print
	}
	return false
}

func (x *GoModEditRequest) GetFmt() bool {
	if x != nil {
		return x.Fmt
	}
	return false
}

// go mod graph
type GoModGraphRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// -go: report the graph as seen by the given Go version
	GoVersion     string `protobuf:"bytes,1,opt,name=go_version,json=goVersion,proto3" json:"go_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoModGraphRequest) Reset() {
	*x = GoModGraphRequest{}
	mi := &file_go_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoModGraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoModGraphRequest) ProtoMessage() {}

func (x *GoModGraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoModGraphRequest.ProtoReflect.Descriptor instead.
func (*GoModGraphRequest) Descriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{19}
}

func (x *GoModGraphRequest) GetGoVersion() string {
	if x != nil {
		return x.GoVersion
	}
	return ""
}

// go mod init [module-path]
type GoModInitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModulePath    string                 `protobuf:"bytes,1,opt,name=module_path,json=modulePath,proto3" json:"module_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoModInitRequest) Reset() {
	*x = GoModInitRequest{}
	mi := &file_go_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoModInitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoModInitRequest) ProtoMessage() {}

func (x *GoModInitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoModInitRequest.ProtoReflect.Descriptor instead.
func (*GoModInitRequest) Descriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{20}
}

func (x *GoModInitRequest) GetModulePath() string {
	if x != nil {
		return x.ModulePath
	}
	return ""
}

// go mod tidy [-v] [-go version] [-diff]
type GoModTidyRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Verbose bool                   `protobuf:"varint,1,opt,name=verbose,proto3" json:"verbose,omitempty"`
	// -go: set the expected Go language version
	GoVersion string `protobuf:"bytes,2,opt,name=go_version,json=goVersion,proto3" json:"go_version,omitempty"`
	// -diff: instead of modifying, print the diff and exit with non-zero status if changes needed
	Diff          bool `protobuf:"varint,3,opt,name=diff,proto3" json:"diff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoModTidyRequest) Reset() {
	*x = GoModTidyRequest{}
	mi := &file_go_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoModTidyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoModTidyRequest) ProtoMessage() {}

func (x *GoModTidyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoModTidyRequest.ProtoReflect.Descriptor instead.
func (*GoModTidyRequest) Descriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{21}
}

func (x *GoModTidyRequest) GetVerbose() bool {
	if x != nil {
		return x.Verbose
	}
	return false
}

func (x *GoModTidyRequest) GetGoVersion() string {
	if x != nil {
		return x.GoVersion
	}
	return ""
}

func (x *GoModTidyRequest) GetDiff() bool {
	if x != nil {
		return x.Diff
	}
	return false
}

// go mod vendor [-v] [-o outdir]
type GoModVendorRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Verbose bool                   `protobuf:"varint,1,opt,name=verbose,proto3" json:"verbose,omitempty"`
	// -o: create the vendor directory at the given path instead of "vendor"
	OutputDir     string `protobuf:"bytes,2,opt,name=output_dir,json=outputDir,proto3" json:"output_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoModVendorRequest) Reset() {
	*x = GoModVendorRequest{}
	mi := &file_go_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoModVendorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoModVendorRequest) ProtoMessage() {}

func (x *GoModVendorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoModVendorRequest.ProtoReflect.Descriptor instead.
func (*GoModVendorRequest) Descriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{22}
}

func (x *GoModVendorRequest) GetVerbose() bool {
	if x != nil {
		return x.Verbose
	}
	return false
}

func (x *GoModVendorRequest) GetOutputDir() string {
	if x != nil {
		return x.OutputDir
	}
	return ""
}

// go mod verify
// No flags — just verifies that dependencies in the module cache match go.sum
type GoModVerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoModVerifyRequest) Reset() {
	*x = GoModVerifyRequest{}
	mi := &file_go_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoModVerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoModVerifyRequest) ProtoMessage() {}

func (x *GoModVerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoModVerifyRequest.ProtoReflect.Descriptor instead.
func (*GoModVerifyRequest) Descriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{23}
}

// go mod why [-m] [-vendor] [packages/modules...]
type GoModWhyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// -m: treat arguments as modules, not packages
	Modules bool `protobuf:"varint,1,opt,name=modules,proto3" json:"modules,omitempty"`
	// -vendor: exclude tests of dependencies outside the main module
	Vendor        bool     `protobuf:"varint,2,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Packages      []string `protobuf:"bytes,3,rep,name=packages,proto3" json:"packages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoModWhyRequest) Reset() {
	*x = GoModWhyRequest{}
	mi := &file_go_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoModWhyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoModWhyRequest) ProtoMessage() {}

func (x *GoModWhyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoModWhyRequest.ProtoReflect.Descriptor instead.
func (*GoModWhyRequest) Descriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{24}
}

func (x *GoModWhyRequest) GetModules() bool {
	if x != nil {
		return x.Modules
	}
	return false
}

func (x *GoModWhyRequest) GetVendor() bool {
	if x != nil {
		return x.Vendor
	}
	return false
}

func (x *GoModWhyRequest) GetPackages() []string {
	if x != nil {
		return x.Packages
	}
	return nil
}

type GoFormatRequest_RewriteRule struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SourceExpression string                 `protobuf:"bytes,1,opt,name=source_expression,json=sourceExpression,proto3" json:"source_expression,omitempty"`
	TargetExpression string                 `protobuf:"bytes,2,opt,name=target_expression,json=targetExpression,proto3" json:"target_expression,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GoFormatRequest_RewriteRule) Reset() {
	*x = GoFormatRequest_RewriteRule{}
	mi := &file_go_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoFormatRequest_RewriteRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoFormatRequest_RewriteRule) ProtoMessage() {}

func (x *GoFormatRequest_RewriteRule) ProtoReflect() protoreflect.Message {
	mi := &file_go_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoFormatRequest_RewriteRule.ProtoReflect.Descriptor instead.
func (*GoFormatRequest_RewriteRule) Descriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GoFormatRequest_RewriteRule) GetSourceExpression() string {
	if x != nil {
		return x.SourceExpression
	}
	return ""
}

func (x *GoFormatRequest_RewriteRule) GetTargetExpression() string {
	if x != nil {
		return x.TargetExpression
	}
	return ""
}

var File_go_proto protoreflect.FileDescriptor

const file_go_proto_rawDesc = "" +
	"\n" +
	"\bgo.proto\x12\x05gluon\"\xf9\x01\n" +
	"\x10GoCompilerTarget\x12,\n" +
	"\x02os\x18\x01 \x01(\x0e2\x1c.gluon.GoCompilerTarget.GOOSR\x02os\x122\n" +
	"\x04arch\x18\x02 \x01(\x0e2\x1e.gluon.GoCompilerTarget.GOARCHR\x04arch\"<\n" +
	"\x04GOOS\x12\x10\n" +
	"\fGOOS_UNKNOWN\x10\x00\x12\t\n" +
	"\x05linux\x10\x01\x12\n" +
	"\n" +
	"\x06darwin\x10\x02\x12\v\n" +
	"\awindows\x10\x03\"E\n" +
	"\x06GOARCH\x12\x12\n" +
	"\x0eGOARCH_UNKNOWN\x10\x00\x12\t\n" +
	"\x05amd64\x10\x01\x12\b\n" +
	"\x04_386\x10\x02\x12\a\n" +
	"\x03arm\x10\x03\x12\t\n" +
	"\x05arm64\x10\x04\"\xaf\x02\n" +
	"\n" +
	"GoDocQuery\x12\x10\n" +
	"\x03pkg\x18\x01 \x01(\tR\x03pkg\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12&\n" +
	"\x0fmethod_or_field\x18\x03 \x03(\tR\rmethodOrField\x127\n" +
	"\x05flags\x18\x04 \x03(\x0e2!.gluon.GoDocQuery.GoDocQueryFlagsR\x05flags\"\x95\x01\n" +
	"\x0fGoDocQueryFlags\x12\x11\n" +
	"\rGODOC_UNKNOWN\x10\x00\x12\a\n" +
	"\x03all\x10\x01\x12\x12\n" +
	"\x0ecase_sensitive\x10\x02\x12\x14\n" +
	"\x10include_main_cmd\x10\x03\x12\b\n" +
	"\x04http\x10\x04\x12\t\n" +
	"\x05short\x10\x05\x12\x0f\n" +
	"\vfull_source\x10\x06\x12\x16\n" +
	"\x12include_unexported\x10\a\"\x95\x01\n" +
	"\n" +
	"GoFixQuery\x12\x10\n" +
	"\x03pkg\x18\x01 \x01(\tR\x03pkg\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04diff\x18\x03 \x01(\bR\x04diff\x12\x1c\n" +
	"\tanalyzers\x18\x04 \x03(\tR\tanalyzers\x12/\n" +
	"\x06target\x18\x05 \x01(\v2\x17.gluon.GoCompilerTargetR\x06target\"\xdc\x03\n" +
	"\x0fGoFormatRequest\x12\x1a\n" +
	"\bpackages\x18\x01 \x03(\tR\bpackages\x12#\n" +
	"\rgo_expression\x18\x02 \x01(\tR\fgoExpression\x12(\n" +
	"\x10print_all_errors\x18\x03 \x01(\bR\x0eprintAllErrors\x12H\n" +
	"\rprint_options\x18\x04 \x01(\x0e2#.gluon.GoFormatRequest.PrintOptionsR\fprintOptions\x12E\n" +
	"\frewrite_rule\x18\x05 \x01(\v2\".gluon.GoFormatRequest.RewriteRuleR\vrewriteRule\x12\x1a\n" +
	"\bsimplify\x18\x06 \x01(\bR\bsimplify\x1ag\n" +
	"\vRewriteRule\x12+\n" +
	"\x11source_expression\x18\x01 \x01(\tR\x10sourceExpression\x12+\n" +
	"\x11target_expression\x18\x02 \x01(\tR\x10targetExpression\"H\n" +
	"\fPrintOptions\x12\x11\n" +
	"\rPRINT_UNKNOWN\x10\x00\x12\v\n" +
	"\aReplace\x10\x01\x12\t\n" +
	"\x05Diffs\x10\x02\x12\r\n" +
	"\tFilenames\x10\x03\"i\n" +
	"\fGoGetRequest\x12\x1a\n" +
	"\bpackages\x18\x01 \x03(\tR\bpackages\x12\x18\n" +
	"\aupgrade\x18\x02 \x01(\bR\aupgrade\x12#\n" +
	"\rinclude_tests\x18\x03 \x01(\bR\fincludeTests\".\n" +
	"\x10GoInstallRequest\x12\x1a\n" +
	"\bpackages\x18\x01 \x03(\tR\bpackages\"\xb6\x01\n" +
	"\rGoListRequest\x12\x18\n" +
	"\amodules\x18\x01 \x01(\bR\amodules\x12!\n" +
	"\fupgrade_info\x18\x02 \x01(\bR\vupgradeInfo\x12\x1c\n" +
	"\tretracted\x18\x03 \x01(\bR\tretracted\x12\x1a\n" +
	"\bversions\x18\x04 \x01(\bR\bversions\x12\x12\n" +
	"\x04json\x18\x05 \x01(\bR\x04json\x12\x1a\n" +
	"\bpackages\x18\x06 \x03(\tR\bpackages\"A\n" +
	"\x15GoEnvironmentVariable\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x96\x01\n" +
	"\fGoEnvRequest\x12\x12\n" +
	"\x04json\x18\x01 \x01(\bR\x04json\x12\x14\n" +
	"\x05unset\x18\x02 \x03(\tR\x05unset\x12.\n" +
	"\x03set\x18\x03 \x03(\v2\x1c.gluon.GoEnvironmentVariableR\x03set\x12\x18\n" +
	"\achanged\x18\x04 \x01(\bR\achanged\x12\x12\n" +
	"\x04vars\x18\x05 \x03(\tR\x04vars\"\xb7\x02\n" +
	"\x0eGoBuildRequest\x12\x1a\n" +
	"\bpackages\x18\x01 \x03(\tR\bpackages\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x18\n" +
	"\averbose\x18\x03 \x01(\bR\averbose\x12\x12\n" +
	"\x04race\x18\x04 \x01(\bR\x04race\x12\x18\n" +
	"\aldflags\x18\x05 \x01(\tR\aldflags\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x1a\n" +
	"\btrimpath\x18\a \x01(\bR\btrimpath\x12\x18\n" +
	"\agcflags\x18\b \x01(\tR\agcflags\x12\x1a\n" +
	"\basmflags\x18\t \x01(\tR\basmflags\x12/\n" +
	"\x06target\x18\n" +
	" \x01(\v2\x17.gluon.GoCompilerTargetR\x06target\x12\x12\n" +
	"\x04work\x18\v \x01(\bR\x04work\"\xde\x01\n" +
	"\fGoRunRequest\x12\x18\n" +
	"\apackage\x18\x01 \x01(\tR\apackage\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12\x18\n" +
	"\averbose\x18\x03 \x01(\bR\averbose\x12\x12\n" +
	"\x04race\x18\x04 \x01(\bR\x04race\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x19\n" +
	"\bexec_cmd\x18\x06 \x01(\tR\aexecCmd\x12\x12\n" +
	"\x04work\x18\a \x01(\bR\x04work\x12/\n" +
	"\x06target\x18\b \x01(\v2\x17.gluon.GoCompilerTargetR\x06target\"\xb0\x03\n" +
	"\rGoTestRequest\x12\x1a\n" +
	"\bpackages\x18\x01 \x03(\tR\bpackages\x12\x18\n" +
	"\averbose\x18\x02 \x01(\bR\averbose\x12\x12\n" +
	"\x04race\x18\x03 \x01(\bR\x04race\x12\x10\n" +
	"\x03run\x18\x04 \x01(\tR\x03run\x12\x14\n" +
	"\x05bench\x18\x05 \x01(\tR\x05bench\x12\x14\n" +
	"\x05count\x18\x06 \x01(\x05R\x05count\x12\x18\n" +
	"\atimeout\x18\a \x01(\tR\atimeout\x12\x14\n" +
	"\x05short\x18\b \x01(\bR\x05short\x12\x14\n" +
	"\x05cover\x18\t \x01(\bR\x05cover\x12\"\n" +
	"\fcoverprofile\x18\n" +
	" \x01(\tR\fcoverprofile\x12\x12\n" +
	"\x04json\x18\v \x01(\bR\x04json\x12\x12\n" +
	"\x04tags\x18\f \x03(\tR\x04tags\x12\x1a\n" +
	"\bfailfast\x18\r \x01(\bR\bfailfast\x12\x1a\n" +
	"\bbenchmem\x18\x0e \x01(\bR\bbenchmem\x12\x1c\n" +
	"\tbenchtime\x18\x0f \x01(\tR\tbenchtime\x12/\n" +
	"\x06target\x18\x10 \x01(\v2\x17.gluon.GoCompilerTargetR\x06target\"\x9b\x01\n" +
	"\x11GoGenerateRequest\x12\x1a\n" +
	"\bpackages\x18\x01 \x03(\tR\bpackages\x12\x18\n" +
	"\averbose\x18\x02 \x01(\bR\averbose\x12\x17\n" +
	"\adry_run\x18\x03 \x01(\bR\x06dryRun\x12%\n" +
	"\x0eprint_commands\x18\x04 \x01(\bR\rprintCommands\x12\x10\n" +
	"\x03run\x18\x05 \x01(\tR\x03run\"l\n" +
	"\fGoVetRequest\x12\x1a\n" +
	"\bpackages\x18\x01 \x03(\tR\bpackages\x12\x18\n" +
	"\averbose\x18\x02 \x01(\bR\averbose\x12\x12\n" +
	"\x04json\x18\x03 \x01(\bR\x04json\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\"P\n" +
	"\rGoToolRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12\x17\n" +
	"\adry_run\x18\x03 \x01(\bR\x06dryRun\"\x1a\n" +
	"\x04Text\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\t\n" +
	"\aNothing\"k\n" +
	"\x14GoModDownloadRequest\x12\x18\n" +
	"\amodules\x18\x01 \x03(\tR\amodules\x12\x12\n" +
	"\x04json\x18\x02 \x01(\bR\x04json\x12%\n" +
	"\x0eprint_commands\x18\x03 \x01(\bR\rprintCommands\"\xf9\x02\n" +
	"\x10GoModEditRequest\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12\x1d\n" +
	"\n" +
	"go_version\x18\x02 \x01(\tR\tgoVersion\x12\x18\n" +
	"\arequire\x18\x03 \x03(\tR\arequire\x12!\n" +
	"\fdrop_require\x18\x04 \x03(\tR\vdropRequire\x12\x18\n" +
	"\areplace\x18\x05 \x03(\tR\areplace\x12!\n" +
	"\fdrop_replace\x18\x06 \x03(\tR\vdropReplace\x12\x18\n" +
	"\aexclude\x18\a \x03(\tR\aexclude\x12!\n" +
	"\fdrop_exclude\x18\b \x03(\tR\vdropExclude\x12\x18\n" +
	"\aretract\x18\t \x03(\tR\aretract\x12!\n" +
	"\fdrop_retract\x18\n" +
	" \x03(\tR\vdropRetract\x12\x12\n" +
	"\x04json\x18\v \x01(\bR\x04json\x12\x14\n" +
	"\x05print\x18\f \x01(\bR\x05print\x12\x10\n" +
	"\x03fmt\x18\r \x01(\bR\x03fmt\"2\n" +
	"\x11GoModGraphRequest\x12\x1d\n" +
	"\n" +
	"go_version\x18\x01 \x01(\tR\tgoVersion\"3\n" +
	"\x10GoModInitRequest\x12\x1f\n" +
	"\vmodule_path\x18\x01 \x01(\tR\n" +
	"modulePath\"_\n" +
	"\x10GoModTidyRequest\x12\x18\n" +
	"\averbose\x18\x01 \x01(\bR\averbose\x12\x1d\n" +
	"\n" +
	"go_version\x18\x02 \x01(\tR\tgoVersion\x12\x12\n" +
	"\x04diff\x18\x03 \x01(\bR\x04diff\"M\n" +
	"\x12GoModVendorRequest\x12\x18\n" +
	"\averbose\x18\x01 \x01(\bR\averbose\x12\x1d\n" +
	"\n" +
	"output_dir\x18\x02 \x01(\tR\toutputDir\"\x14\n" +
	"\x12GoModVerifyRequest\"_\n" +
	"\x0fGoModWhyRequest\x12\x18\n" +
	"\amodules\x18\x01 \x01(\bR\amodules\x12\x16\n" +
	"\x06vendor\x18\x02 \x01(\bR\x06vendor\x12\x1a\n" +
	"\bpackages\x18\x03 \x03(\tR\bpackages2\x88\x06\n" +
	"\x02Go\x12#\n" +
	"\aCommand\x12\v.gluon.Text\x1a\v.gluon.Text\x12%\n" +
	"\x03Doc\x12\x11.gluon.GoDocQuery\x1a\v.gluon.Text\x12%\n" +
	"\x03Fix\x12\x11.gluon.GoFixQuery\x1a\v.gluon.Text\x12/\n" +
	"\x10ListFixAnalyzers\x12\x0e.gluon.Nothing\x1a\v.gluon.Text\x12/\n" +
	"\x13DescribeFixAnalyzer\x12\v.gluon.Text\x1a\v.gluon.Text\x12-\n" +
	"\x06Format\x12\x16.gluon.GoFormatRequest\x1a\v.gluon.Text\x12'\n" +
	"\x03Get\x12\x13.gluon.GoGetRequest\x1a\v.gluon.Text\x12/\n" +
	"\aInstall\x12\x17.gluon.GoInstallRequest\x1a\v.gluon.Text\x12)\n" +
	"\x04List\x12\x14.gluon.GoListRequest\x1a\v.gluon.Text\x12'\n" +
	"\x03Env\x12\x13.gluon.GoEnvRequest\x1a\v.gluon.Text\x12+\n" +
	"\x05Build\x12\x15.gluon.GoBuildRequest\x1a\v.gluon.Text\x12'\n" +
	"\x03Run\x12\x13.gluon.GoRunRequest\x1a\v.gluon.Text\x12)\n" +
	"\x04Test\x12\x14.gluon.GoTestRequest\x1a\v.gluon.Text\x121\n" +
	"\bGenerate\x12\x18.gluon.GoGenerateRequest\x1a\v.gluon.Text\x12'\n" +
	"\x03Vet\x12\x13.gluon.GoVetRequest\x1a\v.gluon.Text\x12)\n" +
	"\x04Tool\x12\x14.gluon.GoToolRequest\x1a\v.gluon.Text\x12 \n" +
	"\x04Help\x12\v.gluon.Text\x1a\v.gluon.Text\x12&\n" +
	"\aVersion\x12\x0e.gluon.Nothing\x1a\v.gluon.Text2\x87\x03\n" +
	"\x05GoMod\x124\n" +
	"\bDownload\x12\x1b.gluon.GoModDownloadRequest\x1a\v.gluon.Text\x12,\n" +
	"\x04Edit\x12\x17.gluon.GoModEditRequest\x1a\v.gluon.Text\x12.\n" +
	"\x05Graph\x12\x18.gluon.GoModGraphRequest\x1a\v.gluon.Text\x12,\n" +
	"\x04Init\x12\x17.gluon.GoModInitRequest\x1a\v.gluon.Text\x12,\n" +
	"\x04Tidy\x12\x17.gluon.GoModTidyRequest\x1a\v.gluon.Text\x120\n" +
	"\x06Vendor\x12\x19.gluon.GoModVendorRequest\x1a\v.gluon.Text\x120\n" +
	"\x06Verify\x12\x19.gluon.GoModVerifyRequest\x1a\v.gluon.Text\x12*\n" +
	"\x03Why\x12\x16.gluon.GoModWhyRequest\x1a\v.gluon.TextB!Z\x1fgithub.com/accretional/gluon/pbb\x06proto3"

var (
	file_go_proto_rawDescOnce sync.Once
	file_go_proto_rawDescData []byte
)

func file_go_proto_rawDescGZIP() []byte {
	file_go_proto_rawDescOnce.Do(func() {
		file_go_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_go_proto_rawDesc), len(file_go_proto_rawDesc)))
	})
	return file_go_proto_rawDescData
}

var file_go_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_go_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_go_proto_goTypes = []any{
	(GoCompilerTarget_GOOS)(0),          // 0: gluon.GoCompilerTarget.GOOS
	(GoCompilerTarget_GOARCH)(0),        // 1: gluon.GoCompilerTarget.GOARCH
	(GoDocQuery_GoDocQueryFlags)(0),     // 2: gluon.GoDocQuery.GoDocQueryFlags
	(GoFormatRequest_PrintOptions)(0),   // 3: gluon.GoFormatRequest.PrintOptions
	(*GoCompilerTarget)(nil),            // 4: gluon.GoCompilerTarget
	(*GoDocQuery)(nil),                  // 5: gluon.GoDocQuery
	(*GoFixQuery)(nil),                  // 6: gluon.GoFixQuery
	(*GoFormatRequest)(nil),             // 7: gluon.GoFormatRequest
	(*GoGetRequest)(nil),                // 8: gluon.GoGetRequest
	(*GoInstallRequest)(nil),            // 9: gluon.GoInstallRequest
	(*GoListRequest)(nil),               // 10: gluon.GoListRequest
	(*GoEnvironmentVariable)(nil),       // 11: gluon.GoEnvironmentVariable
	(*GoEnvRequest)(nil),                // 12: gluon.GoEnvRequest
	(*GoBuildRequest)(nil),              // 13: gluon.GoBuildRequest
	(*GoRunRequest)(nil),                // 14: gluon.GoRunRequest
	(*GoTestRequest)(nil),               // 15: gluon.GoTestRequest
	(*GoGenerateRequest)(nil),           // 16: gluon.GoGenerateRequest
	(*GoVetRequest)(nil),                // 17: gluon.GoVetRequest
	(*GoToolRequest)(nil),               // 18: gluon.GoToolRequest
	(*Text)(nil),                        // 19: gluon.Text
	(*Nothing)(nil),                     // 20: gluon.Nothing
	(*GoModDownloadRequest)(nil),        // 21: gluon.GoModDownloadRequest
	(*GoModEditRequest)(nil),            // 22: gluon.GoModEditRequest
	(*GoModGraphRequest)(nil),           // 23: gluon.GoModGraphRequest
	(*GoModInitRequest)(nil),            // 24: gluon.GoModInitRequest
	(*GoModTidyRequest)(nil),            // 25: gluon.GoModTidyRequest
	(*GoModVendorRequest)(nil),          // 26: gluon.GoModVendorRequest
	(*GoModVerifyRequest)(nil),          // 27: gluon.GoModVerifyRequest
	(*GoModWhyRequest)(nil),             // 28: gluon.GoModWhyRequest
	(*GoFormatRequest_RewriteRule)(nil), // 29: gluon.GoFormatRequest.RewriteRule
}
var file_go_proto_depIdxs = []int32{
	0,  // 0: gluon.GoCompilerTarget.os:type_name -> gluon.GoCompilerTarget.GOOS
	1,  // 1: gluon.GoCompilerTarget.arch:type_name -> gluon.GoCompilerTarget.GOARCH
	2,  // 2: gluon.GoDocQuery.flags:type_name -> gluon.GoDocQuery.GoDocQueryFlags
	4,  // 3: gluon.GoFixQuery.target:type_name -> gluon.GoCompilerTarget
	3,  // 4: gluon.GoFormatRequest.print_options:type_name -> gluon.GoFormatRequest.PrintOptions
	29, // 5: gluon.GoFormatRequest.rewrite_rule:type_name -> gluon.GoFormatRequest.RewriteRule
	11, // 6: gluon.GoEnvRequest.set:type_name -> gluon.GoEnvironmentVariable
	4,  // 7: gluon.GoBuildRequest.target:type_name -> gluon.GoCompilerTarget
	4,  // 8: gluon.GoRunRequest.target:type_name -> gluon.GoCompilerTarget
	4,  // 9: gluon.GoTestRequest.target:type_name -> gluon.GoCompilerTarget
	19, // 10: gluon.Go.Command:input_type -> gluon.Text
	5,  // 11: gluon.Go.Doc:input_type -> gluon.GoDocQuery
	6,  // 12: gluon.Go.Fix:input_type -> gluon.GoFixQuery
	20, // 13: gluon.Go.ListFixAnalyzers:input_type -> gluon.Nothing
	19, // 14: gluon.Go.DescribeFixAnalyzer:input_type -> gluon.Text
	7,  // 15: gluon.Go.Format:input_type -> gluon.GoFormatRequest
	8,  // 16: gluon.Go.Get:input_type -> gluon.GoGetRequest
	9,  // 17: gluon.Go.Install:input_type -> gluon.GoInstallRequest
	10, // 18: gluon.Go.List:input_type -> gluon.GoListRequest
	12, // 19: gluon.Go.Env:input_type -> gluon.GoEnvRequest
	13, // 20: gluon.Go.Build:input_type -> gluon.GoBuildRequest
	14, // 21: gluon.Go.Run:input_type -> gluon.GoRunRequest
	15, // 22: gluon.Go.Test:input_type -> gluon.GoTestRequest
	16, // 23: gluon.Go.Generate:input_type -> gluon.GoGenerateRequest
	17, // 24: gluon.Go.Vet:input_type -> gluon.GoVetRequest
	18, // 25: gluon.Go.Tool:input_type -> gluon.GoToolRequest
	19, // 26: gluon.Go.Help:input_type -> gluon.Text
	20, // 27: gluon.Go.Version:input_type -> gluon.Nothing
	21, // 28: gluon.GoMod.Download:input_type -> gluon.GoModDownloadRequest
	22, // 29: gluon.GoMod.Edit:input_type -> gluon.GoModEditRequest
	23, // 30: gluon.GoMod.Graph:input_type -> gluon.GoModGraphRequest
	24, // 31: gluon.GoMod.Init:input_type -> gluon.GoModInitRequest
	25, // 32: gluon.GoMod.Tidy:input_type -> gluon.GoModTidyRequest
	26, // 33: gluon.GoMod.Vendor:input_type -> gluon.GoModVendorRequest
	27, // 34: gluon.GoMod.Verify:input_type -> gluon.GoModVerifyRequest
	28, // 35: gluon.GoMod.Why:input_type -> gluon.GoModWhyRequest
	19, // 36: gluon.Go.Command:output_type -> gluon.Text
	19, // 37: gluon.Go.Doc:output_type -> gluon.Text
	19, // 38: gluon.Go.Fix:output_type -> gluon.Text
	19, // 39: gluon.Go.ListFixAnalyzers:output_type -> gluon.Text
	19, // 40: gluon.Go.DescribeFixAnalyzer:output_type -> gluon.Text
	19, // 41: gluon.Go.Format:output_type -> gluon.Text
	19, // 42: gluon.Go.Get:output_type -> gluon.Text
	19, // 43: gluon.Go.Install:output_type -> gluon.Text
	19, // 44: gluon.Go.List:output_type -> gluon.Text
	19, // 45: gluon.Go.Env:output_type -> gluon.Text
	19, // 46: gluon.Go.Build:output_type -> gluon.Text
	19, // 47: gluon.Go.Run:output_type -> gluon.Text
	19, // 48: gluon.Go.Test:output_type -> gluon.Text
	19, // 49: gluon.Go.Generate:output_type -> gluon.Text
	19, // 50: gluon.Go.Vet:output_type -> gluon.Text
	19, // 51: gluon.Go.Tool:output_type -> gluon.Text
	19, // 52: gluon.Go.Help:output_type -> gluon.Text
	19, // 53: gluon.Go.Version:output_type -> gluon.Text
	19, // 54: gluon.GoMod.Download:output_type -> gluon.Text
	19, // 55: gluon.GoMod.Edit:output_type -> gluon.Text
	19, // 56: gluon.GoMod.Graph:output_type -> gluon.Text
	19, // 57: gluon.GoMod.Init:output_type -> gluon.Text
	19, // 58: gluon.GoMod.Tidy:output_type -> gluon.Text
	19, // 59: gluon.GoMod.Vendor:output_type -> gluon.Text
	19, // 60: gluon.GoMod.Verify:output_type -> gluon.Text
	19, // 61: gluon.GoMod.Why:output_type -> gluon.Text
	36, // [36:62] is the sub-list for method output_type
	10, // [10:36] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_go_proto_init() }
func file_go_proto_init() {
	if File_go_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_go_proto_rawDesc), len(file_go_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_go_proto_goTypes,
		DependencyIndexes: file_go_proto_depIdxs,
		EnumInfos:         file_go_proto_enumTypes,
		MessageInfos:      file_go_proto_msgTypes,
	}.Build()
	File_go_proto = out.File
	file_go_proto_goTypes = nil
	file_go_proto_depIdxs = nil
}
