// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: go.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Go_Command_FullMethodName             = "/gluon.Go/Command"
	Go_Doc_FullMethodName                 = "/gluon.Go/Doc"
	Go_Fix_FullMethodName                 = "/gluon.Go/Fix"
	Go_ListFixAnalyzers_FullMethodName    = "/gluon.Go/ListFixAnalyzers"
	Go_DescribeFixAnalyzer_FullMethodName = "/gluon.Go/DescribeFixAnalyzer"
	Go_Format_FullMethodName              = "/gluon.Go/Format"
	Go_Get_FullMethodName                 = "/gluon.Go/Get"
	Go_Install_FullMethodName             = "/gluon.Go/Install"
	Go_List_FullMethodName                = "/gluon.Go/List"
	Go_Env_FullMethodName                 = "/gluon.Go/Env"
	Go_Build_FullMethodName               = "/gluon.Go/Build"
	Go_Run_FullMethodName                 = "/gluon.Go/Run"
	Go_Test_FullMethodName                = "/gluon.Go/Test"
	Go_Generate_FullMethodName            = "/gluon.Go/Generate"
	Go_Vet_FullMethodName                 = "/gluon.Go/Vet"
	Go_Tool_FullMethodName                = "/gluon.Go/Tool"
	Go_Help_FullMethodName                = "/gluon.Go/Help"
	Go_Version_FullMethodName             = "/gluon.Go/Version"
)

// GoClient is the client API for Go service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Wrapper for https://pkg.go.dev/cmd/go for programmatic, remote, or reflective interaction with the Go compiler and development ecosystem
// Go intentionally doesn't expose this stuff as a package, which makes it harder to automate or use with tool-calling agents or remote development environments
// We can embed the binary in a Go package, provide more structured access via an API, internally translate that into commands, and invoke it via a loader, subprocess, etc :)
type GoClient interface {
	// IMPORTANT - general escape hatch that runs arbitrary go subcommands
	// wrap the Commander from https://github.com/accretional/runrpc
	Command(ctx context.Context, in *Text, opts ...grpc.CallOption) (*Text, error)
	// go doc
	Doc(ctx context.Context, in *GoDocQuery, opts ...grpc.CallOption) (*Text, error)
	// go fix
	Fix(ctx context.Context, in *GoFixQuery, opts ...grpc.CallOption) (*Text, error)
	// go tool fix -list (list available fix analyzers)
	ListFixAnalyzers(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*Text, error)
	// go tool fix -describe <analyzer>
	DescribeFixAnalyzer(ctx context.Context, in *Text, opts ...grpc.CallOption) (*Text, error)
	// go fmt / gofmt
	Format(ctx context.Context, in *GoFormatRequest, opts ...grpc.CallOption) (*Text, error)
	// go get
	Get(ctx context.Context, in *GoGetRequest, opts ...grpc.CallOption) (*Text, error)
	// go install
	Install(ctx context.Context, in *GoInstallRequest, opts ...grpc.CallOption) (*Text, error)
	// go list
	List(ctx context.Context, in *GoListRequest, opts ...grpc.CallOption) (*Text, error)
	// go env
	Env(ctx context.Context, in *GoEnvRequest, opts ...grpc.CallOption) (*Text, error)
	// go build
	Build(ctx context.Context, in *GoBuildRequest, opts ...grpc.CallOption) (*Text, error)
	// go run
	Run(ctx context.Context, in *GoRunRequest, opts ...grpc.CallOption) (*Text, error)
	// go test
	Test(ctx context.Context, in *GoTestRequest, opts ...grpc.CallOption) (*Text, error)
	// go generate
	Generate(ctx context.Context, in *GoGenerateRequest, opts ...grpc.CallOption) (*Text, error)
	// go vet
	Vet(ctx context.Context, in *GoVetRequest, opts ...grpc.CallOption) (*Text, error)
	// go tool
	Tool(ctx context.Context, in *GoToolRequest, opts ...grpc.CallOption) (*Text, error)
	// go help [topic]
	Help(ctx context.Context, in *Text, opts ...grpc.CallOption) (*Text, error)
	// go version
	Version(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*Text, error)
}

type goClient struct {
	cc grpc.ClientConnInterface
}

func NewGoClient(cc grpc.ClientConnInterface) GoClient {
	return &goClient{cc}
}

func (c *goClient) Command(ctx context.Context, in *Text, opts ...grpc.CallOption) (*Text, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Text)
	err := c.cc.Invoke(ctx, Go_Command_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goClient) Doc(ctx context.Context, in *GoDocQuery, opts ...grpc.CallOption) (*Text, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Text)
	err := c.cc.Invoke(ctx, Go_Doc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goClient) Fix(ctx context.Context, in *GoFixQuery, opts ...grpc.CallOption) (*Text, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Text)
	err := c.cc.Invoke(ctx, Go_Fix_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goClient) ListFixAnalyzers(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*Text, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Text)
	err := c.cc.Invoke(ctx, Go_ListFixAnalyzers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goClient) DescribeFixAnalyzer(ctx context.Context, in *Text, opts ...grpc.CallOption) (*Text, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Text)
	err := c.cc.Invoke(ctx, Go_DescribeFixAnalyzer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goClient) Format(ctx context.Context, in *GoFormatRequest, opts ...grpc.CallOption) (*Text, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Text)
	err := c.cc.Invoke(ctx, Go_Format_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goClient) Get(ctx context.Context, in *GoGetRequest, opts ...grpc.CallOption) (*Text, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Text)
	err := c.cc.Invoke(ctx, Go_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goClient) Install(ctx context.Context, in *GoInstallRequest, opts ...grpc.CallOption) (*Text, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Text)
	err := c.cc.Invoke(ctx, Go_Install_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goClient) List(ctx context.Context, in *GoListRequest, opts ...grpc.CallOption) (*Text, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Text)
	err := c.cc.Invoke(ctx, Go_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goClient) Env(ctx context.Context, in *GoEnvRequest, opts ...grpc.CallOption) (*Text, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Text)
	err := c.cc.Invoke(ctx, Go_Env_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goClient) Build(ctx context.Context, in *GoBuildRequest, opts ...grpc.CallOption) (*Text, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Text)
	err := c.cc.Invoke(ctx, Go_Build_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goClient) Run(ctx context.Context, in *GoRunRequest, opts ...grpc.CallOption) (*Text, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Text)
	err := c.cc.Invoke(ctx, Go_Run_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goClient) Test(ctx context.Context, in *GoTestRequest, opts ...grpc.CallOption) (*Text, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Text)
	err := c.cc.Invoke(ctx, Go_Test_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goClient) Generate(ctx context.Context, in *GoGenerateRequest, opts ...grpc.CallOption) (*Text, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Text)
	err := c.cc.Invoke(ctx, Go_Generate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goClient) Vet(ctx context.Context, in *GoVetRequest, opts ...grpc.CallOption) (*Text, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Text)
	err := c.cc.Invoke(ctx, Go_Vet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goClient) Tool(ctx context.Context, in *GoToolRequest, opts ...grpc.CallOption) (*Text, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Text)
	err := c.cc.Invoke(ctx, Go_Tool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goClient) Help(ctx context.Context, in *Text, opts ...grpc.CallOption) (*Text, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Text)
	err := c.cc.Invoke(ctx, Go_Help_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goClient) Version(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*Text, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Text)
	err := c.cc.Invoke(ctx, Go_Version_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoServer is the server API for Go service.
// All implementations must embed UnimplementedGoServer
// for forward compatibility.
//
// Wrapper for https://pkg.go.dev/cmd/go for programmatic, remote, or reflective interaction with the Go compiler and development ecosystem
// Go intentionally doesn't expose this stuff as a package, which makes it harder to automate or use with tool-calling agents or remote development environments
// We can embed the binary in a Go package, provide more structured access via an API, internally translate that into commands, and invoke it via a loader, subprocess, etc :)
type GoServer interface {
	// IMPORTANT - general escape hatch that runs arbitrary go subcommands
	// wrap the Commander from https://github.com/accretional/runrpc
	Command(context.Context, *Text) (*Text, error)
	// go doc
	Doc(context.Context, *GoDocQuery) (*Text, error)
	// go fix
	Fix(context.Context, *GoFixQuery) (*Text, error)
	// go tool fix -list (list available fix analyzers)
	ListFixAnalyzers(context.Context, *Nothing) (*Text, error)
	// go tool fix -describe <analyzer>
	DescribeFixAnalyzer(context.Context, *Text) (*Text, error)
	// go fmt / gofmt
	Format(context.Context, *GoFormatRequest) (*Text, error)
	// go get
	Get(context.Context, *GoGetRequest) (*Text, error)
	// go install
	Install(context.Context, *GoInstallRequest) (*Text, error)
	// go list
	List(context.Context, *GoListRequest) (*Text, error)
	// go env
	Env(context.Context, *GoEnvRequest) (*Text, error)
	// go build
	Build(context.Context, *GoBuildRequest) (*Text, error)
	// go run
	Run(context.Context, *GoRunRequest) (*Text, error)
	// go test
	Test(context.Context, *GoTestRequest) (*Text, error)
	// go generate
	Generate(context.Context, *GoGenerateRequest) (*Text, error)
	// go vet
	Vet(context.Context, *GoVetRequest) (*Text, error)
	// go tool
	Tool(context.Context, *GoToolRequest) (*Text, error)
	// go help [topic]
	Help(context.Context, *Text) (*Text, error)
	// go version
	Version(context.Context, *Nothing) (*Text, error)
	mustEmbedUnimplementedGoServer()
}

// UnimplementedGoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGoServer struct{}

func (UnimplementedGoServer) Command(context.Context, *Text) (*Text, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Command not implemented")
}
func (UnimplementedGoServer) Doc(context.Context, *GoDocQuery) (*Text, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Doc not implemented")
}
func (UnimplementedGoServer) Fix(context.Context, *GoFixQuery) (*Text, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fix not implemented")
}
func (UnimplementedGoServer) ListFixAnalyzers(context.Context, *Nothing) (*Text, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFixAnalyzers not implemented")
}
func (UnimplementedGoServer) DescribeFixAnalyzer(context.Context, *Text) (*Text, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeFixAnalyzer not implemented")
}
func (UnimplementedGoServer) Format(context.Context, *GoFormatRequest) (*Text, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Format not implemented")
}
func (UnimplementedGoServer) Get(context.Context, *GoGetRequest) (*Text, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedGoServer) Install(context.Context, *GoInstallRequest) (*Text, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Install not implemented")
}
func (UnimplementedGoServer) List(context.Context, *GoListRequest) (*Text, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedGoServer) Env(context.Context, *GoEnvRequest) (*Text, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Env not implemented")
}
func (UnimplementedGoServer) Build(context.Context, *GoBuildRequest) (*Text, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Build not implemented")
}
func (UnimplementedGoServer) Run(context.Context, *GoRunRequest) (*Text, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedGoServer) Test(context.Context, *GoTestRequest) (*Text, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Test not implemented")
}
func (UnimplementedGoServer) Generate(context.Context, *GoGenerateRequest) (*Text, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedGoServer) Vet(context.Context, *GoVetRequest) (*Text, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Vet not implemented")
}
func (UnimplementedGoServer) Tool(context.Context, *GoToolRequest) (*Text, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Tool not implemented")
}
func (UnimplementedGoServer) Help(context.Context, *Text) (*Text, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Help not implemented")
}
func (UnimplementedGoServer) Version(context.Context, *Nothing) (*Text, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedGoServer) mustEmbedUnimplementedGoServer() {}
func (UnimplementedGoServer) testEmbeddedByValue()            {}

// UnsafeGoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoServer will
// result in compilation errors.
type UnsafeGoServer interface {
	mustEmbedUnimplementedGoServer()
}

func RegisterGoServer(s grpc.ServiceRegistrar, srv GoServer) {
	// If the following call pancis, it indicates UnimplementedGoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Go_ServiceDesc, srv)
}

func _Go_Command_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Text)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoServer).Command(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Go_Command_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoServer).Command(ctx, req.(*Text))
	}
	return interceptor(ctx, in, info, handler)
}

func _Go_Doc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoDocQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoServer).Doc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Go_Doc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoServer).Doc(ctx, req.(*GoDocQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Go_Fix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoFixQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoServer).Fix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Go_Fix_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoServer).Fix(ctx, req.(*GoFixQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Go_ListFixAnalyzers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Nothing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoServer).ListFixAnalyzers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Go_ListFixAnalyzers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoServer).ListFixAnalyzers(ctx, req.(*Nothing))
	}
	return interceptor(ctx, in, info, handler)
}

func _Go_DescribeFixAnalyzer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Text)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoServer).DescribeFixAnalyzer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Go_DescribeFixAnalyzer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoServer).DescribeFixAnalyzer(ctx, req.(*Text))
	}
	return interceptor(ctx, in, info, handler)
}

func _Go_Format_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoFormatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoServer).Format(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Go_Format_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoServer).Format(ctx, req.(*GoFormatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Go_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Go_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoServer).Get(ctx, req.(*GoGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Go_Install_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoInstallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoServer).Install(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Go_Install_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoServer).Install(ctx, req.(*GoInstallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Go_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Go_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoServer).List(ctx, req.(*GoListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Go_Env_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoEnvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoServer).Env(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Go_Env_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoServer).Env(ctx, req.(*GoEnvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Go_Build_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoServer).Build(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Go_Build_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoServer).Build(ctx, req.(*GoBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Go_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Go_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoServer).Run(ctx, req.(*GoRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Go_Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoTestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoServer).Test(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Go_Test_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoServer).Test(ctx, req.(*GoTestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Go_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoGenerateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Go_Generate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoServer).Generate(ctx, req.(*GoGenerateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Go_Vet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoVetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoServer).Vet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Go_Vet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoServer).Vet(ctx, req.(*GoVetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Go_Tool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoServer).Tool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Go_Tool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoServer).Tool(ctx, req.(*GoToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Go_Help_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Text)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoServer).Help(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Go_Help_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoServer).Help(ctx, req.(*Text))
	}
	return interceptor(ctx, in, info, handler)
}

func _Go_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Nothing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Go_Version_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoServer).Version(ctx, req.(*Nothing))
	}
	return interceptor(ctx, in, info, handler)
}

// Go_ServiceDesc is the grpc.ServiceDesc for Go service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Go_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gluon.Go",
	HandlerType: (*GoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Command",
			Handler:    _Go_Command_Handler,
		},
		{
			MethodName: "Doc",
			Handler:    _Go_Doc_Handler,
		},
		{
			MethodName: "Fix",
			Handler:    _Go_Fix_Handler,
		},
		{
			MethodName: "ListFixAnalyzers",
			Handler:    _Go_ListFixAnalyzers_Handler,
		},
		{
			MethodName: "DescribeFixAnalyzer",
			Handler:    _Go_DescribeFixAnalyzer_Handler,
		},
		{
			MethodName: "Format",
			Handler:    _Go_Format_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Go_Get_Handler,
		},
		{
			MethodName: "Install",
			Handler:    _Go_Install_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Go_List_Handler,
		},
		{
			MethodName: "Env",
			Handler:    _Go_Env_Handler,
		},
		{
			MethodName: "Build",
			Handler:    _Go_Build_Handler,
		},
		{
			MethodName: "Run",
			Handler:    _Go_Run_Handler,
		},
		{
			MethodName: "Test",
			Handler:    _Go_Test_Handler,
		},
		{
			MethodName: "Generate",
			Handler:    _Go_Generate_Handler,
		},
		{
			MethodName: "Vet",
			Handler:    _Go_Vet_Handler,
		},
		{
			MethodName: "Tool",
			Handler:    _Go_Tool_Handler,
		},
		{
			MethodName: "Help",
			Handler:    _Go_Help_Handler,
		},
		{
			MethodName: "Version",
			Handler:    _Go_Version_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "go.proto",
}

const (
	GoMod_Download_FullMethodName = "/gluon.GoMod/Download"
	GoMod_Edit_FullMethodName     = "/gluon.GoMod/Edit"
	GoMod_Graph_FullMethodName    = "/gluon.GoMod/Graph"
	GoMod_Init_FullMethodName     = "/gluon.GoMod/Init"
	GoMod_Tidy_FullMethodName     = "/gluon.GoMod/Tidy"
	GoMod_Vendor_FullMethodName   = "/gluon.GoMod/Vendor"
	GoMod_Verify_FullMethodName   = "/gluon.GoMod/Verify"
	GoMod_Why_FullMethodName      = "/gluon.GoMod/Why"
)

// GoModClient is the client API for GoMod service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// https://go.dev/ref/mod
type GoModClient interface {
	// go mod download
	Download(ctx context.Context, in *GoModDownloadRequest, opts ...grpc.CallOption) (*Text, error)
	// go mod edit
	Edit(ctx context.Context, in *GoModEditRequest, opts ...grpc.CallOption) (*Text, error)
	// go mod graph
	Graph(ctx context.Context, in *GoModGraphRequest, opts ...grpc.CallOption) (*Text, error)
	// go mod init
	Init(ctx context.Context, in *GoModInitRequest, opts ...grpc.CallOption) (*Text, error)
	// go mod tidy
	Tidy(ctx context.Context, in *GoModTidyRequest, opts ...grpc.CallOption) (*Text, error)
	// go mod vendor
	Vendor(ctx context.Context, in *GoModVendorRequest, opts ...grpc.CallOption) (*Text, error)
	// go mod verify
	Verify(ctx context.Context, in *GoModVerifyRequest, opts ...grpc.CallOption) (*Text, error)
	// go mod why
	Why(ctx context.Context, in *GoModWhyRequest, opts ...grpc.CallOption) (*Text, error)
}

type goModClient struct {
	cc grpc.ClientConnInterface
}

func NewGoModClient(cc grpc.ClientConnInterface) GoModClient {
	return &goModClient{cc}
}

func (c *goModClient) Download(ctx context.Context, in *GoModDownloadRequest, opts ...grpc.CallOption) (*Text, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Text)
	err := c.cc.Invoke(ctx, GoMod_Download_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goModClient) Edit(ctx context.Context, in *GoModEditRequest, opts ...grpc.CallOption) (*Text, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Text)
	err := c.cc.Invoke(ctx, GoMod_Edit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goModClient) Graph(ctx context.Context, in *GoModGraphRequest, opts ...grpc.CallOption) (*Text, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Text)
	err := c.cc.Invoke(ctx, GoMod_Graph_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goModClient) Init(ctx context.Context, in *GoModInitRequest, opts ...grpc.CallOption) (*Text, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Text)
	err := c.cc.Invoke(ctx, GoMod_Init_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goModClient) Tidy(ctx context.Context, in *GoModTidyRequest, opts ...grpc.CallOption) (*Text, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Text)
	err := c.cc.Invoke(ctx, GoMod_Tidy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goModClient) Vendor(ctx context.Context, in *GoModVendorRequest, opts ...grpc.CallOption) (*Text, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Text)
	err := c.cc.Invoke(ctx, GoMod_Vendor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goModClient) Verify(ctx context.Context, in *GoModVerifyRequest, opts ...grpc.CallOption) (*Text, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Text)
	err := c.cc.Invoke(ctx, GoMod_Verify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goModClient) Why(ctx context.Context, in *GoModWhyRequest, opts ...grpc.CallOption) (*Text, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Text)
	err := c.cc.Invoke(ctx, GoMod_Why_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoModServer is the server API for GoMod service.
// All implementations must embed UnimplementedGoModServer
// for forward compatibility.
//
// https://go.dev/ref/mod
type GoModServer interface {
	// go mod download
	Download(context.Context, *GoModDownloadRequest) (*Text, error)
	// go mod edit
	Edit(context.Context, *GoModEditRequest) (*Text, error)
	// go mod graph
	Graph(context.Context, *GoModGraphRequest) (*Text, error)
	// go mod init
	Init(context.Context, *GoModInitRequest) (*Text, error)
	// go mod tidy
	Tidy(context.Context, *GoModTidyRequest) (*Text, error)
	// go mod vendor
	Vendor(context.Context, *GoModVendorRequest) (*Text, error)
	// go mod verify
	Verify(context.Context, *GoModVerifyRequest) (*Text, error)
	// go mod why
	Why(context.Context, *GoModWhyRequest) (*Text, error)
	mustEmbedUnimplementedGoModServer()
}

// UnimplementedGoModServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGoModServer struct{}

func (UnimplementedGoModServer) Download(context.Context, *GoModDownloadRequest) (*Text, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Download not implemented")
}
func (UnimplementedGoModServer) Edit(context.Context, *GoModEditRequest) (*Text, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Edit not implemented")
}
func (UnimplementedGoModServer) Graph(context.Context, *GoModGraphRequest) (*Text, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Graph not implemented")
}
func (UnimplementedGoModServer) Init(context.Context, *GoModInitRequest) (*Text, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedGoModServer) Tidy(context.Context, *GoModTidyRequest) (*Text, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Tidy not implemented")
}
func (UnimplementedGoModServer) Vendor(context.Context, *GoModVendorRequest) (*Text, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Vendor not implemented")
}
func (UnimplementedGoModServer) Verify(context.Context, *GoModVerifyRequest) (*Text, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Verify not implemented")
}
func (UnimplementedGoModServer) Why(context.Context, *GoModWhyRequest) (*Text, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Why not implemented")
}
func (UnimplementedGoModServer) mustEmbedUnimplementedGoModServer() {}
func (UnimplementedGoModServer) testEmbeddedByValue()               {}

// UnsafeGoModServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoModServer will
// result in compilation errors.
type UnsafeGoModServer interface {
	mustEmbedUnimplementedGoModServer()
}

func RegisterGoModServer(s grpc.ServiceRegistrar, srv GoModServer) {
	// If the following call pancis, it indicates UnimplementedGoModServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GoMod_ServiceDesc, srv)
}

func _GoMod_Download_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoModDownloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoModServer).Download(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoMod_Download_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoModServer).Download(ctx, req.(*GoModDownloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoMod_Edit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoModEditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoModServer).Edit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoMod_Edit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoModServer).Edit(ctx, req.(*GoModEditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoMod_Graph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoModGraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoModServer).Graph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoMod_Graph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoModServer).Graph(ctx, req.(*GoModGraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoMod_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoModInitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoModServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoMod_Init_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoModServer).Init(ctx, req.(*GoModInitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoMod_Tidy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoModTidyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoModServer).Tidy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoMod_Tidy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoModServer).Tidy(ctx, req.(*GoModTidyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoMod_Vendor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoModVendorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoModServer).Vendor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoMod_Vendor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoModServer).Vendor(ctx, req.(*GoModVendorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoMod_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoModVerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoModServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoMod_Verify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoModServer).Verify(ctx, req.(*GoModVerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoMod_Why_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoModWhyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoModServer).Why(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoMod_Why_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoModServer).Why(ctx, req.(*GoModWhyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GoMod_ServiceDesc is the grpc.ServiceDesc for GoMod service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoMod_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gluon.GoMod",
	HandlerType: (*GoModServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Download",
			Handler:    _GoMod_Download_Handler,
		},
		{
			MethodName: "Edit",
			Handler:    _GoMod_Edit_Handler,
		},
		{
			MethodName: "Graph",
			Handler:    _GoMod_Graph_Handler,
		},
		{
			MethodName: "Init",
			Handler:    _GoMod_Init_Handler,
		},
		{
			MethodName: "Tidy",
			Handler:    _GoMod_Tidy_Handler,
		},
		{
			MethodName: "Vendor",
			Handler:    _GoMod_Vendor_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _GoMod_Verify_Handler,
		},
		{
			MethodName: "Why",
			Handler:    _GoMod_Why_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "go.proto",
}
