// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: grammar.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GrammarDescriptor represents a complete grammar defined in EBNF notation.
// It pairs the lexical configuration (how to read the EBNF) with the
// production rules that define the language.
type GrammarDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Lexical structure of the EBNF notation used to write this grammar.
	Lex *LexDescriptor `protobuf:"bytes,1,opt,name=lex,proto3" json:"lex,omitempty"`
	// Production rules that define the grammar.
	// TODO: Define fields for ProductionDescriptor once AST node
	// representation is settled.
	Productions   []*ProductionDescriptor `protobuf:"bytes,2,rep,name=productions,proto3" json:"productions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrammarDescriptor) Reset() {
	*x = GrammarDescriptor{}
	mi := &file_grammar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrammarDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrammarDescriptor) ProtoMessage() {}

func (x *GrammarDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_grammar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrammarDescriptor.ProtoReflect.Descriptor instead.
func (*GrammarDescriptor) Descriptor() ([]byte, []int) {
	return file_grammar_proto_rawDescGZIP(), []int{0}
}

func (x *GrammarDescriptor) GetLex() *LexDescriptor {
	if x != nil {
		return x.Lex
	}
	return nil
}

func (x *GrammarDescriptor) GetProductions() []*ProductionDescriptor {
	if x != nil {
		return x.Productions
	}
	return nil
}

// ProductionDescriptor represents a single EBNF production rule.
// For example: Identifier = letter { letter | digit } .
//
// TODO: Add fields once ASTNodeDescriptor is designed. Expected fields:
//
//	string name = 1;         // production name (e.g. "Identifier")
//	string raw = 2;          // raw EBNF text of the expression
//	ASTNodeDescriptor body = 3; // parsed expression tree
type ProductionDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductionDescriptor) Reset() {
	*x = ProductionDescriptor{}
	mi := &file_grammar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductionDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductionDescriptor) ProtoMessage() {}

func (x *ProductionDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_grammar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductionDescriptor.ProtoReflect.Descriptor instead.
func (*ProductionDescriptor) Descriptor() ([]byte, []int) {
	return file_grammar_proto_rawDescGZIP(), []int{1}
}

var File_grammar_proto protoreflect.FileDescriptor

const file_grammar_proto_rawDesc = "" +
	"\n" +
	"\rgrammar.proto\x12\x05gluon\x1a\tlex.proto\"z\n" +
	"\x11GrammarDescriptor\x12&\n" +
	"\x03lex\x18\x01 \x01(\v2\x14.gluon.LexDescriptorR\x03lex\x12=\n" +
	"\vproductions\x18\x02 \x03(\v2\x1b.gluon.ProductionDescriptorR\vproductions\"\x16\n" +
	"\x14ProductionDescriptorB!Z\x1fgithub.com/accretional/gluon/pbb\x06proto3"

var (
	file_grammar_proto_rawDescOnce sync.Once
	file_grammar_proto_rawDescData []byte
)

func file_grammar_proto_rawDescGZIP() []byte {
	file_grammar_proto_rawDescOnce.Do(func() {
		file_grammar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grammar_proto_rawDesc), len(file_grammar_proto_rawDesc)))
	})
	return file_grammar_proto_rawDescData
}

var file_grammar_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grammar_proto_goTypes = []any{
	(*GrammarDescriptor)(nil),    // 0: gluon.GrammarDescriptor
	(*ProductionDescriptor)(nil), // 1: gluon.ProductionDescriptor
	(*LexDescriptor)(nil),        // 2: gluon.LexDescriptor
}
var file_grammar_proto_depIdxs = []int32{
	2, // 0: gluon.GrammarDescriptor.lex:type_name -> gluon.LexDescriptor
	1, // 1: gluon.GrammarDescriptor.productions:type_name -> gluon.ProductionDescriptor
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_grammar_proto_init() }
func file_grammar_proto_init() {
	if File_grammar_proto != nil {
		return
	}
	file_lex_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grammar_proto_rawDesc), len(file_grammar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grammar_proto_goTypes,
		DependencyIndexes: file_grammar_proto_depIdxs,
		MessageInfos:      file_grammar_proto_msgTypes,
	}.Build()
	File_grammar_proto = out.File
	file_grammar_proto_goTypes = nil
	file_grammar_proto_depIdxs = nil
}
