// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: language.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LanguageDescriptor defines a programming language in terms of its grammar,
// version, and compiler. This is the top-level entry point for describing
// a language that gluon can transpile to/from.
type LanguageDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable name of the language (e.g. "Go", "Protocol Buffers").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Version of the language specification this descriptor covers.
	Version *VersionDescriptor `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Formal grammar of the language in EBNF.
	Grammar *GrammarDescriptor `protobuf:"bytes,3,opt,name=grammar,proto3" json:"grammar,omitempty"`
	// Compiler or code generator for this language.
	Compiler      *Compiler `protobuf:"bytes,4,opt,name=compiler,proto3" json:"compiler,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LanguageDescriptor) Reset() {
	*x = LanguageDescriptor{}
	mi := &file_language_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LanguageDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LanguageDescriptor) ProtoMessage() {}

func (x *LanguageDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_language_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LanguageDescriptor.ProtoReflect.Descriptor instead.
func (*LanguageDescriptor) Descriptor() ([]byte, []int) {
	return file_language_proto_rawDescGZIP(), []int{0}
}

func (x *LanguageDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LanguageDescriptor) GetVersion() *VersionDescriptor {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *LanguageDescriptor) GetGrammar() *GrammarDescriptor {
	if x != nil {
		return x.Grammar
	}
	return nil
}

func (x *LanguageDescriptor) GetCompiler() *Compiler {
	if x != nil {
		return x.Compiler
	}
	return nil
}

// VersionDescriptor identifies a specific version of a language spec.
type VersionDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Major version number.
	Major int32 `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	// Minor version number.
	Minor int32 `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	// Patch version number.
	Patch int32 `protobuf:"varint,3,opt,name=patch,proto3" json:"patch,omitempty"`
	// Version string as written in the spec (e.g. "go1.26", "proto3").
	Label         string `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionDescriptor) Reset() {
	*x = VersionDescriptor{}
	mi := &file_language_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionDescriptor) ProtoMessage() {}

func (x *VersionDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_language_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionDescriptor.ProtoReflect.Descriptor instead.
func (*VersionDescriptor) Descriptor() ([]byte, []int) {
	return file_language_proto_rawDescGZIP(), []int{1}
}

func (x *VersionDescriptor) GetMajor() int32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *VersionDescriptor) GetMinor() int32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

func (x *VersionDescriptor) GetPatch() int32 {
	if x != nil {
		return x.Patch
	}
	return 0
}

func (x *VersionDescriptor) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

// Compiler describes how to compile or generate code for a language.
type Compiler struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Compiler_Uri
	//	*Compiler_Binary
	Kind          isCompiler_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Compiler) Reset() {
	*x = Compiler{}
	mi := &file_language_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Compiler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Compiler) ProtoMessage() {}

func (x *Compiler) ProtoReflect() protoreflect.Message {
	mi := &file_language_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Compiler.ProtoReflect.Descriptor instead.
func (*Compiler) Descriptor() ([]byte, []int) {
	return file_language_proto_rawDescGZIP(), []int{2}
}

func (x *Compiler) GetKind() isCompiler_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Compiler) GetUri() string {
	if x != nil {
		if x, ok := x.Kind.(*Compiler_Uri); ok {
			return x.Uri
		}
	}
	return ""
}

func (x *Compiler) GetBinary() []byte {
	if x != nil {
		if x, ok := x.Kind.(*Compiler_Binary); ok {
			return x.Binary
		}
	}
	return nil
}

type isCompiler_Kind interface {
	isCompiler_Kind()
}

type Compiler_Uri struct {
	// URI pointing to a compiler binary or service (e.g. "go", "protoc",
	// or a full path like "/usr/local/go/bin/go").
	Uri string `protobuf:"bytes,1,opt,name=uri,proto3,oneof"`
}

type Compiler_Binary struct {
	// Embedded compiler binary (for hermetic/self-contained builds).
	Binary []byte `protobuf:"bytes,2,opt,name=binary,proto3,oneof"`
}

func (*Compiler_Uri) isCompiler_Kind() {}

func (*Compiler_Binary) isCompiler_Kind() {}

var File_language_proto protoreflect.FileDescriptor

const file_language_proto_rawDesc = "" +
	"\n" +
	"\x0elanguage.proto\x12\x05gluon\x1a\rgrammar.proto\"\xbd\x01\n" +
	"\x12LanguageDescriptor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x122\n" +
	"\aversion\x18\x02 \x01(\v2\x18.gluon.VersionDescriptorR\aversion\x122\n" +
	"\agrammar\x18\x03 \x01(\v2\x18.gluon.GrammarDescriptorR\agrammar\x12+\n" +
	"\bcompiler\x18\x04 \x01(\v2\x0f.gluon.CompilerR\bcompiler\"k\n" +
	"\x11VersionDescriptor\x12\x14\n" +
	"\x05major\x18\x01 \x01(\x05R\x05major\x12\x14\n" +
	"\x05minor\x18\x02 \x01(\x05R\x05minor\x12\x14\n" +
	"\x05patch\x18\x03 \x01(\x05R\x05patch\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\"@\n" +
	"\bCompiler\x12\x12\n" +
	"\x03uri\x18\x01 \x01(\tH\x00R\x03uri\x12\x18\n" +
	"\x06binary\x18\x02 \x01(\fH\x00R\x06binaryB\x06\n" +
	"\x04kindB!Z\x1fgithub.com/accretional/gluon/pbb\x06proto3"

var (
	file_language_proto_rawDescOnce sync.Once
	file_language_proto_rawDescData []byte
)

func file_language_proto_rawDescGZIP() []byte {
	file_language_proto_rawDescOnce.Do(func() {
		file_language_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_language_proto_rawDesc), len(file_language_proto_rawDesc)))
	})
	return file_language_proto_rawDescData
}

var file_language_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_language_proto_goTypes = []any{
	(*LanguageDescriptor)(nil), // 0: gluon.LanguageDescriptor
	(*VersionDescriptor)(nil),  // 1: gluon.VersionDescriptor
	(*Compiler)(nil),           // 2: gluon.Compiler
	(*GrammarDescriptor)(nil),  // 3: gluon.GrammarDescriptor
}
var file_language_proto_depIdxs = []int32{
	1, // 0: gluon.LanguageDescriptor.version:type_name -> gluon.VersionDescriptor
	3, // 1: gluon.LanguageDescriptor.grammar:type_name -> gluon.GrammarDescriptor
	2, // 2: gluon.LanguageDescriptor.compiler:type_name -> gluon.Compiler
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_language_proto_init() }
func file_language_proto_init() {
	if File_language_proto != nil {
		return
	}
	file_grammar_proto_init()
	file_language_proto_msgTypes[2].OneofWrappers = []any{
		(*Compiler_Uri)(nil),
		(*Compiler_Binary)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_language_proto_rawDesc), len(file_language_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_language_proto_goTypes,
		DependencyIndexes: file_language_proto_depIdxs,
		MessageInfos:      file_language_proto_msgTypes,
	}.Build()
	File_language_proto = out.File
	file_language_proto_goTypes = nil
	file_language_proto_depIdxs = nil
}
