// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: lex.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LexDescriptor defines the lexical structure of an EBNF-based grammar
// notation. Each field is an int32 Unicode code point for the character
// that serves that role in the notation.
//
// For example, standard EBNF uses '=' (61) for definition, '|' (124) for
// alternation, '.' (46) for termination, etc.
//
// This allows a single lexer implementation to handle different EBNF
// variants (Go's spec notation, proto's notation, ISO 14977 EBNF) by
// swapping the LexDescriptor configuration.
type LexDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whitespace characters (typically space, tab, newline, carriage return).
	Whitespace []int32 `protobuf:"varint,1,rep,packed,name=whitespace,proto3" json:"whitespace,omitempty"`
	// Definition operator: separates production name from its expression.
	// Standard EBNF: '=' (61). Some notations use '::=' or ':'.
	Definition int32 `protobuf:"varint,2,opt,name=definition,proto3" json:"definition,omitempty"`
	// Concatenation operator: separates sequential terms.
	// Standard EBNF: ',' (44). Go/proto EBNF: implicit (juxtaposition).
	// Set to 0 when concatenation is implicit.
	Concatenation int32 `protobuf:"varint,3,opt,name=concatenation,proto3" json:"concatenation,omitempty"`
	// Termination: marks the end of a production rule.
	// Standard EBNF: ';' (59). Go EBNF: '.' (46). Proto: ';' (59).
	Termination int32 `protobuf:"varint,4,opt,name=termination,proto3" json:"termination,omitempty"`
	// Alternation: separates alternative choices.
	// Universally: '|' (124).
	Alternation int32 `protobuf:"varint,5,opt,name=alternation,proto3" json:"alternation,omitempty"`
	// Optional brackets: enclose optional expressions (0 or 1 times).
	// Standard/Go EBNF: '[' (91) and ']' (93).
	OptionalLhs int32 `protobuf:"varint,6,opt,name=optional_lhs,json=optionalLhs,proto3" json:"optional_lhs,omitempty"`
	OptionalRhs int32 `protobuf:"varint,7,opt,name=optional_rhs,json=optionalRhs,proto3" json:"optional_rhs,omitempty"`
	// Repetition brackets: enclose repeated expressions (0 to n times).
	// Standard/Go EBNF: '{' (123) and '}' (125).
	RepetitionLhs int32 `protobuf:"varint,8,opt,name=repetition_lhs,json=repetitionLhs,proto3" json:"repetition_lhs,omitempty"`
	RepetitionRhs int32 `protobuf:"varint,9,opt,name=repetition_rhs,json=repetitionRhs,proto3" json:"repetition_rhs,omitempty"`
	// Grouping brackets: enclose grouped expressions.
	// Standard/Go EBNF: '(' (40) and ')' (41).
	GroupingLhs int32 `protobuf:"varint,10,opt,name=grouping_lhs,json=groupingLhs,proto3" json:"grouping_lhs,omitempty"`
	GroupingRhs int32 `protobuf:"varint,11,opt,name=grouping_rhs,json=groupingRhs,proto3" json:"grouping_rhs,omitempty"`
	// Terminal delimiter: character used to quote terminal symbols.
	// Standard EBNF: '"' (34) or "'" (39). Go also uses '`' (96).
	Terminal int32 `protobuf:"varint,12,opt,name=terminal,proto3" json:"terminal,omitempty"`
	// Comment delimiters: characters that open and close comments.
	// Standard EBNF: '(' (40) paired with '*' (42) for '(*', then
	// '*' (42) paired with ')' (41) for '*)'.
	// Go EBNF uses '/' (47) paired with '*' (42) for '/* ... */'.
	CommentLhs    int32 `protobuf:"varint,13,opt,name=comment_lhs,json=commentLhs,proto3" json:"comment_lhs,omitempty"`
	CommentRhs    int32 `protobuf:"varint,14,opt,name=comment_rhs,json=commentRhs,proto3" json:"comment_rhs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LexDescriptor) Reset() {
	*x = LexDescriptor{}
	mi := &file_lex_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LexDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LexDescriptor) ProtoMessage() {}

func (x *LexDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_lex_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LexDescriptor.ProtoReflect.Descriptor instead.
func (*LexDescriptor) Descriptor() ([]byte, []int) {
	return file_lex_proto_rawDescGZIP(), []int{0}
}

func (x *LexDescriptor) GetWhitespace() []int32 {
	if x != nil {
		return x.Whitespace
	}
	return nil
}

func (x *LexDescriptor) GetDefinition() int32 {
	if x != nil {
		return x.Definition
	}
	return 0
}

func (x *LexDescriptor) GetConcatenation() int32 {
	if x != nil {
		return x.Concatenation
	}
	return 0
}

func (x *LexDescriptor) GetTermination() int32 {
	if x != nil {
		return x.Termination
	}
	return 0
}

func (x *LexDescriptor) GetAlternation() int32 {
	if x != nil {
		return x.Alternation
	}
	return 0
}

func (x *LexDescriptor) GetOptionalLhs() int32 {
	if x != nil {
		return x.OptionalLhs
	}
	return 0
}

func (x *LexDescriptor) GetOptionalRhs() int32 {
	if x != nil {
		return x.OptionalRhs
	}
	return 0
}

func (x *LexDescriptor) GetRepetitionLhs() int32 {
	if x != nil {
		return x.RepetitionLhs
	}
	return 0
}

func (x *LexDescriptor) GetRepetitionRhs() int32 {
	if x != nil {
		return x.RepetitionRhs
	}
	return 0
}

func (x *LexDescriptor) GetGroupingLhs() int32 {
	if x != nil {
		return x.GroupingLhs
	}
	return 0
}

func (x *LexDescriptor) GetGroupingRhs() int32 {
	if x != nil {
		return x.GroupingRhs
	}
	return 0
}

func (x *LexDescriptor) GetTerminal() int32 {
	if x != nil {
		return x.Terminal
	}
	return 0
}

func (x *LexDescriptor) GetCommentLhs() int32 {
	if x != nil {
		return x.CommentLhs
	}
	return 0
}

func (x *LexDescriptor) GetCommentRhs() int32 {
	if x != nil {
		return x.CommentRhs
	}
	return 0
}

var File_lex_proto protoreflect.FileDescriptor

const file_lex_proto_rawDesc = "" +
	"\n" +
	"\tlex.proto\x12\x05gluon\"\xf1\x03\n" +
	"\rLexDescriptor\x12\x1e\n" +
	"\n" +
	"whitespace\x18\x01 \x03(\x05R\n" +
	"whitespace\x12\x1e\n" +
	"\n" +
	"definition\x18\x02 \x01(\x05R\n" +
	"definition\x12$\n" +
	"\rconcatenation\x18\x03 \x01(\x05R\rconcatenation\x12 \n" +
	"\vtermination\x18\x04 \x01(\x05R\vtermination\x12 \n" +
	"\valternation\x18\x05 \x01(\x05R\valternation\x12!\n" +
	"\foptional_lhs\x18\x06 \x01(\x05R\voptionalLhs\x12!\n" +
	"\foptional_rhs\x18\a \x01(\x05R\voptionalRhs\x12%\n" +
	"\x0erepetition_lhs\x18\b \x01(\x05R\rrepetitionLhs\x12%\n" +
	"\x0erepetition_rhs\x18\t \x01(\x05R\rrepetitionRhs\x12!\n" +
	"\fgrouping_lhs\x18\n" +
	" \x01(\x05R\vgroupingLhs\x12!\n" +
	"\fgrouping_rhs\x18\v \x01(\x05R\vgroupingRhs\x12\x1a\n" +
	"\bterminal\x18\f \x01(\x05R\bterminal\x12\x1f\n" +
	"\vcomment_lhs\x18\r \x01(\x05R\n" +
	"commentLhs\x12\x1f\n" +
	"\vcomment_rhs\x18\x0e \x01(\x05R\n" +
	"commentRhsB!Z\x1fgithub.com/accretional/gluon/pbb\x06proto3"

var (
	file_lex_proto_rawDescOnce sync.Once
	file_lex_proto_rawDescData []byte
)

func file_lex_proto_rawDescGZIP() []byte {
	file_lex_proto_rawDescOnce.Do(func() {
		file_lex_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lex_proto_rawDesc), len(file_lex_proto_rawDesc)))
	})
	return file_lex_proto_rawDescData
}

var file_lex_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_lex_proto_goTypes = []any{
	(*LexDescriptor)(nil), // 0: gluon.LexDescriptor
}
var file_lex_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lex_proto_init() }
func file_lex_proto_init() {
	if File_lex_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lex_proto_rawDesc), len(file_lex_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lex_proto_goTypes,
		DependencyIndexes: file_lex_proto_depIdxs,
		MessageInfos:      file_lex_proto_msgTypes,
	}.Build()
	File_lex_proto = out.File
	file_lex_proto_goTypes = nil
	file_lex_proto_depIdxs = nil
}
