// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: metaparser.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_metaparser_proto protoreflect.FileDescriptor

const file_metaparser_proto_rawDesc = "" +
	"\n" +
	"\x10metaparser.proto\x12\x05gluon\x1a google/protobuf/descriptor.proto\x1a\x0elanguage.proto2V\n" +
	"\n" +
	"Metaparser\x12H\n" +
	"\x05Proto\x12\x19.gluon.LanguageDescriptor\x1a$.google.protobuf.FileDescriptorProtoB!Z\x1fgithub.com/accretional/gluon/pbb\x06proto3"

var file_metaparser_proto_goTypes = []any{
	(*LanguageDescriptor)(nil),               // 0: gluon.LanguageDescriptor
	(*descriptorpb.FileDescriptorProto)(nil), // 1: google.protobuf.FileDescriptorProto
}
var file_metaparser_proto_depIdxs = []int32{
	0, // 0: gluon.Metaparser.Proto:input_type -> gluon.LanguageDescriptor
	1, // 1: gluon.Metaparser.Proto:output_type -> google.protobuf.FileDescriptorProto
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_metaparser_proto_init() }
func file_metaparser_proto_init() {
	if File_metaparser_proto != nil {
		return
	}
	file_language_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metaparser_proto_rawDesc), len(file_metaparser_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metaparser_proto_goTypes,
		DependencyIndexes: file_metaparser_proto_depIdxs,
	}.Build()
	File_metaparser_proto = out.File
	file_metaparser_proto_goTypes = nil
	file_metaparser_proto_depIdxs = nil
}
