// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: metaparser.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Metaparser_Proto_FullMethodName = "/gluon.Metaparser/Proto"
)

// MetaparserClient is the client API for Metaparser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Metaparser turns a LanguageDescriptor (EBNF grammar) into a
// FileDescriptorProto: one message per production, with alt→oneof,
// rep→repeated, opt→optional, quoted terminals → keyword messages
// (suffixed `_Kw` to avoid collision with nonterminal field names of
// the same base), and nonterminals → fields typed as the referenced
// production message.
type MetaparserClient interface {
	Proto(ctx context.Context, in *LanguageDescriptor, opts ...grpc.CallOption) (*descriptorpb.FileDescriptorProto, error)
}

type metaparserClient struct {
	cc grpc.ClientConnInterface
}

func NewMetaparserClient(cc grpc.ClientConnInterface) MetaparserClient {
	return &metaparserClient{cc}
}

func (c *metaparserClient) Proto(ctx context.Context, in *LanguageDescriptor, opts ...grpc.CallOption) (*descriptorpb.FileDescriptorProto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(descriptorpb.FileDescriptorProto)
	err := c.cc.Invoke(ctx, Metaparser_Proto_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetaparserServer is the server API for Metaparser service.
// All implementations must embed UnimplementedMetaparserServer
// for forward compatibility.
//
// Metaparser turns a LanguageDescriptor (EBNF grammar) into a
// FileDescriptorProto: one message per production, with alt→oneof,
// rep→repeated, opt→optional, quoted terminals → keyword messages
// (suffixed `_Kw` to avoid collision with nonterminal field names of
// the same base), and nonterminals → fields typed as the referenced
// production message.
type MetaparserServer interface {
	Proto(context.Context, *LanguageDescriptor) (*descriptorpb.FileDescriptorProto, error)
	mustEmbedUnimplementedMetaparserServer()
}

// UnimplementedMetaparserServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetaparserServer struct{}

func (UnimplementedMetaparserServer) Proto(context.Context, *LanguageDescriptor) (*descriptorpb.FileDescriptorProto, error) {
	return nil, status.Error(codes.Unimplemented, "method Proto not implemented")
}
func (UnimplementedMetaparserServer) mustEmbedUnimplementedMetaparserServer() {}
func (UnimplementedMetaparserServer) testEmbeddedByValue()                    {}

// UnsafeMetaparserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetaparserServer will
// result in compilation errors.
type UnsafeMetaparserServer interface {
	mustEmbedUnimplementedMetaparserServer()
}

func RegisterMetaparserServer(s grpc.ServiceRegistrar, srv MetaparserServer) {
	// If the following call panics, it indicates UnimplementedMetaparserServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Metaparser_ServiceDesc, srv)
}

func _Metaparser_Proto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LanguageDescriptor)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaparserServer).Proto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metaparser_Proto_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaparserServer).Proto(ctx, req.(*LanguageDescriptor))
	}
	return interceptor(ctx, in, info, handler)
}

// Metaparser_ServiceDesc is the grpc.ServiceDesc for Metaparser service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Metaparser_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gluon.Metaparser",
	HandlerType: (*MetaparserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Proto",
			Handler:    _Metaparser_Proto_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metaparser.proto",
}
