// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: repos.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GithubRepo identifies a repository on GitHub.
type GithubRepo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GithubRepo) Reset() {
	*x = GithubRepo{}
	mi := &file_repos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GithubRepo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GithubRepo) ProtoMessage() {}

func (x *GithubRepo) ProtoReflect() protoreflect.Message {
	mi := &file_repos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GithubRepo.ProtoReflect.Descriptor instead.
func (*GithubRepo) Descriptor() ([]byte, []int) {
	return file_repos_proto_rawDescGZIP(), []int{0}
}

func (x *GithubRepo) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *GithubRepo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Repo identifies a source code repository from any supported host.
type Repo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Source:
	//
	//	*Repo_Gh
	Source        isRepo_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repo) Reset() {
	*x = Repo{}
	mi := &file_repos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repo) ProtoMessage() {}

func (x *Repo) ProtoReflect() protoreflect.Message {
	mi := &file_repos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repo.ProtoReflect.Descriptor instead.
func (*Repo) Descriptor() ([]byte, []int) {
	return file_repos_proto_rawDescGZIP(), []int{1}
}

func (x *Repo) GetSource() isRepo_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Repo) GetGh() *GithubRepo {
	if x != nil {
		if x, ok := x.Source.(*Repo_Gh); ok {
			return x.Gh
		}
	}
	return nil
}

type isRepo_Source interface {
	isRepo_Source()
}

type Repo_Gh struct {
	Gh *GithubRepo `protobuf:"bytes,1,opt,name=gh,proto3,oneof"`
}

func (*Repo_Gh) isRepo_Source() {}

// RepoList is a collection of repositories.
type RepoList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repos         []*Repo                `protobuf:"bytes,1,rep,name=repos,proto3" json:"repos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepoList) Reset() {
	*x = RepoList{}
	mi := &file_repos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoList) ProtoMessage() {}

func (x *RepoList) ProtoReflect() protoreflect.Message {
	mi := &file_repos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoList.ProtoReflect.Descriptor instead.
func (*RepoList) Descriptor() ([]byte, []int) {
	return file_repos_proto_rawDescGZIP(), []int{2}
}

func (x *RepoList) GetRepos() []*Repo {
	if x != nil {
		return x.Repos
	}
	return nil
}

var File_repos_proto protoreflect.FileDescriptor

const file_repos_proto_rawDesc = "" +
	"\n" +
	"\vrepos.proto\x12\x05gluon\"6\n" +
	"\n" +
	"GithubRepo\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"5\n" +
	"\x04Repo\x12#\n" +
	"\x02gh\x18\x01 \x01(\v2\x11.gluon.GithubRepoH\x00R\x02ghB\b\n" +
	"\x06source\"-\n" +
	"\bRepoList\x12!\n" +
	"\x05repos\x18\x01 \x03(\v2\v.gluon.RepoR\x05reposB!Z\x1fgithub.com/accretional/gluon/pbb\x06proto3"

var (
	file_repos_proto_rawDescOnce sync.Once
	file_repos_proto_rawDescData []byte
)

func file_repos_proto_rawDescGZIP() []byte {
	file_repos_proto_rawDescOnce.Do(func() {
		file_repos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_repos_proto_rawDesc), len(file_repos_proto_rawDesc)))
	})
	return file_repos_proto_rawDescData
}

var file_repos_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_repos_proto_goTypes = []any{
	(*GithubRepo)(nil), // 0: gluon.GithubRepo
	(*Repo)(nil),       // 1: gluon.Repo
	(*RepoList)(nil),   // 2: gluon.RepoList
}
var file_repos_proto_depIdxs = []int32{
	0, // 0: gluon.Repo.gh:type_name -> gluon.GithubRepo
	1, // 1: gluon.RepoList.repos:type_name -> gluon.Repo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_repos_proto_init() }
func file_repos_proto_init() {
	if File_repos_proto != nil {
		return
	}
	file_repos_proto_msgTypes[1].OneofWrappers = []any{
		(*Repo_Gh)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_repos_proto_rawDesc), len(file_repos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_repos_proto_goTypes,
		DependencyIndexes: file_repos_proto_depIdxs,
		MessageInfos:      file_repos_proto_msgTypes,
	}.Build()
	File_repos_proto = out.File
	file_repos_proto_goTypes = nil
	file_repos_proto_depIdxs = nil
}
