// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: trace.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TraceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Binary        string                 `protobuf:"bytes,1,opt,name=binary,proto3" json:"binary,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceRequest) Reset() {
	*x = TraceRequest{}
	mi := &file_trace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceRequest) ProtoMessage() {}

func (x *TraceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceRequest.ProtoReflect.Descriptor instead.
func (*TraceRequest) Descriptor() ([]byte, []int) {
	return file_trace_proto_rawDescGZIP(), []int{0}
}

func (x *TraceRequest) GetBinary() string {
	if x != nil {
		return x.Binary
	}
	return ""
}

func (x *TraceRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type TraceEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Caller        string                 `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`
	Callee        string                 `protobuf:"bytes,2,opt,name=callee,proto3" json:"callee,omitempty"`
	GoroutineId   int64                  `protobuf:"varint,3,opt,name=goroutine_id,json=goroutineId,proto3" json:"goroutine_id,omitempty"` // 0 if goroutine ID is not available. Mainly if Go version < 1.17
	TimestampNs   int64                  `protobuf:"varint,4,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceEvent) Reset() {
	*x = TraceEvent{}
	mi := &file_trace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceEvent) ProtoMessage() {}

func (x *TraceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_trace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceEvent.ProtoReflect.Descriptor instead.
func (*TraceEvent) Descriptor() ([]byte, []int) {
	return file_trace_proto_rawDescGZIP(), []int{1}
}

func (x *TraceEvent) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

func (x *TraceEvent) GetCallee() string {
	if x != nil {
		return x.Callee
	}
	return ""
}

func (x *TraceEvent) GetGoroutineId() int64 {
	if x != nil {
		return x.GoroutineId
	}
	return 0
}

func (x *TraceEvent) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

var File_trace_proto protoreflect.FileDescriptor

const file_trace_proto_rawDesc = "" +
	"\n" +
	"\vtrace.proto\x12\x05gluon\":\n" +
	"\fTraceRequest\x12\x16\n" +
	"\x06binary\x18\x01 \x01(\tR\x06binary\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\"\x82\x01\n" +
	"\n" +
	"TraceEvent\x12\x16\n" +
	"\x06caller\x18\x01 \x01(\tR\x06caller\x12\x16\n" +
	"\x06callee\x18\x02 \x01(\tR\x06callee\x12!\n" +
	"\fgoroutine_id\x18\x03 \x01(\x03R\vgoroutineId\x12!\n" +
	"\ftimestamp_ns\x18\x04 \x01(\x03R\vtimestampNs29\n" +
	"\x06Ptrace\x12/\n" +
	"\x03Run\x12\x13.gluon.TraceRequest\x1a\x11.gluon.TraceEvent0\x012;\n" +
	"\bBPFTrace\x12/\n" +
	"\x03Run\x12\x13.gluon.TraceRequest\x1a\x11.gluon.TraceEvent0\x01B!Z\x1fgithub.com/accretional/gluon/pbb\x06proto3"

var (
	file_trace_proto_rawDescOnce sync.Once
	file_trace_proto_rawDescData []byte
)

func file_trace_proto_rawDescGZIP() []byte {
	file_trace_proto_rawDescOnce.Do(func() {
		file_trace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trace_proto_rawDesc), len(file_trace_proto_rawDesc)))
	})
	return file_trace_proto_rawDescData
}

var file_trace_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_trace_proto_goTypes = []any{
	(*TraceRequest)(nil), // 0: gluon.TraceRequest
	(*TraceEvent)(nil),   // 1: gluon.TraceEvent
}
var file_trace_proto_depIdxs = []int32{
	0, // 0: gluon.Ptrace.Run:input_type -> gluon.TraceRequest
	0, // 1: gluon.BPFTrace.Run:input_type -> gluon.TraceRequest
	1, // 2: gluon.Ptrace.Run:output_type -> gluon.TraceEvent
	1, // 3: gluon.BPFTrace.Run:output_type -> gluon.TraceEvent
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_trace_proto_init() }
func file_trace_proto_init() {
	if File_trace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trace_proto_rawDesc), len(file_trace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_trace_proto_goTypes,
		DependencyIndexes: file_trace_proto_depIdxs,
		MessageInfos:      file_trace_proto_msgTypes,
	}.Build()
	File_trace_proto = out.File
	file_trace_proto_goTypes = nil
	file_trace_proto_depIdxs = nil
}
