// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: trace.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Ptrace_Run_FullMethodName = "/gluon.Ptrace/Run"
)

// PtraceClient is the client API for Ptrace service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PtraceClient interface {
	Run(ctx context.Context, in *TraceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TraceEvent], error)
}

type ptraceClient struct {
	cc grpc.ClientConnInterface
}

func NewPtraceClient(cc grpc.ClientConnInterface) PtraceClient {
	return &ptraceClient{cc}
}

func (c *ptraceClient) Run(ctx context.Context, in *TraceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TraceEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Ptrace_ServiceDesc.Streams[0], Ptrace_Run_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TraceRequest, TraceEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Ptrace_RunClient = grpc.ServerStreamingClient[TraceEvent]

// PtraceServer is the server API for Ptrace service.
// All implementations must embed UnimplementedPtraceServer
// for forward compatibility.
type PtraceServer interface {
	Run(*TraceRequest, grpc.ServerStreamingServer[TraceEvent]) error
	mustEmbedUnimplementedPtraceServer()
}

// UnimplementedPtraceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPtraceServer struct{}

func (UnimplementedPtraceServer) Run(*TraceRequest, grpc.ServerStreamingServer[TraceEvent]) error {
	return status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedPtraceServer) mustEmbedUnimplementedPtraceServer() {}
func (UnimplementedPtraceServer) testEmbeddedByValue()                {}

// UnsafePtraceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PtraceServer will
// result in compilation errors.
type UnsafePtraceServer interface {
	mustEmbedUnimplementedPtraceServer()
}

func RegisterPtraceServer(s grpc.ServiceRegistrar, srv PtraceServer) {
	// If the following call panics, it indicates UnimplementedPtraceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Ptrace_ServiceDesc, srv)
}

func _Ptrace_Run_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TraceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PtraceServer).Run(m, &grpc.GenericServerStream[TraceRequest, TraceEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Ptrace_RunServer = grpc.ServerStreamingServer[TraceEvent]

// Ptrace_ServiceDesc is the grpc.ServiceDesc for Ptrace service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ptrace_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gluon.Ptrace",
	HandlerType: (*PtraceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Run",
			Handler:       _Ptrace_Run_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "trace.proto",
}

const (
	BPFTrace_Run_FullMethodName = "/gluon.BPFTrace/Run"
)

// BPFTraceClient is the client API for BPFTrace service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BPFTraceClient interface {
	Run(ctx context.Context, in *TraceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TraceEvent], error)
}

type bPFTraceClient struct {
	cc grpc.ClientConnInterface
}

func NewBPFTraceClient(cc grpc.ClientConnInterface) BPFTraceClient {
	return &bPFTraceClient{cc}
}

func (c *bPFTraceClient) Run(ctx context.Context, in *TraceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TraceEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BPFTrace_ServiceDesc.Streams[0], BPFTrace_Run_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TraceRequest, TraceEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BPFTrace_RunClient = grpc.ServerStreamingClient[TraceEvent]

// BPFTraceServer is the server API for BPFTrace service.
// All implementations must embed UnimplementedBPFTraceServer
// for forward compatibility.
type BPFTraceServer interface {
	Run(*TraceRequest, grpc.ServerStreamingServer[TraceEvent]) error
	mustEmbedUnimplementedBPFTraceServer()
}

// UnimplementedBPFTraceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBPFTraceServer struct{}

func (UnimplementedBPFTraceServer) Run(*TraceRequest, grpc.ServerStreamingServer[TraceEvent]) error {
	return status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedBPFTraceServer) mustEmbedUnimplementedBPFTraceServer() {}
func (UnimplementedBPFTraceServer) testEmbeddedByValue()                  {}

// UnsafeBPFTraceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BPFTraceServer will
// result in compilation errors.
type UnsafeBPFTraceServer interface {
	mustEmbedUnimplementedBPFTraceServer()
}

func RegisterBPFTraceServer(s grpc.ServiceRegistrar, srv BPFTraceServer) {
	// If the following call panics, it indicates UnimplementedBPFTraceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BPFTrace_ServiceDesc, srv)
}

func _BPFTrace_Run_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TraceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BPFTraceServer).Run(m, &grpc.GenericServerStream[TraceRequest, TraceEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BPFTrace_RunServer = grpc.ServerStreamingServer[TraceEvent]

// BPFTrace_ServiceDesc is the grpc.ServiceDesc for BPFTrace service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BPFTrace_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gluon.BPFTrace",
	HandlerType: (*BPFTraceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Run",
			Handler:       _BPFTrace_Run_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "trace.proto",
}
